import { randomUUID } from 'node:crypto';
import type { Pool } from 'pg';
import { validateEditingDecisionEventV1, validateIntelligentEditPresetV1, validateIntelligentEditRecommendationV1, validateIntelligentPlannerConfigV1, type EditingDecisionEventType, type EditingDecisionEventV1, type IntelligentEditPresetV1, type IntelligentEditRecommendationV1, type IntelligentPlannerConfigV1 } from '../../../contracts/src/index.js';

export interface CreatePresetInput { id?: string; projectId?: string | null; name: string; config: IntelligentPlannerConfigV1; enabled?: boolean; }
export interface CreateRecommendationInput { id?: string; projectId: string; planId: string; presetId?: string | null; profile: string; confidence: number; alternatives?: string[]; limitations?: string[]; evidence?: Record<string, unknown>; }
export interface CreateDecisionEventInput { id?: string; projectId: string; planId: string; sentenceId?: string | null; eventType: EditingDecisionEventType; previousCandidateId?: string | null; nextCandidateId?: string | null; previousShotId?: string | null; nextShotId?: string | null; evidence?: Record<string, unknown>; }

function array(value: unknown): string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string') : []; }
function record(value: unknown): Record<string, unknown> { return value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function mapPreset(row: Record<string, unknown>): IntelligentEditPresetV1 { const value = { schemaVersion: 'INTELLIGENT_EDIT_PRESET_V1' as const, id: String(row.id), projectId: row.project_id ? String(row.project_id) : null, name: String(row.name), config: row.config as IntelligentPlannerConfigV1, enabled: Boolean(row.enabled), createdAt: new Date(String(row.created_at)).toISOString() }; validateIntelligentEditPresetV1(value); return value; }
function mapRecommendation(row: Record<string, unknown>): IntelligentEditRecommendationV1 { const value: IntelligentEditRecommendationV1 = { schemaVersion: 'INTELLIGENT_EDIT_RECOMMENDATION_V1', id: String(row.id), projectId: String(row.project_id), planId: String(row.plan_id), presetId: row.preset_id ? String(row.preset_id) : null, profile: String(row.profile), confidence: Number(row.confidence), alternatives: array(row.alternatives), limitations: array(row.limitations), evidence: record(row.evidence), status: String(row.status) as IntelligentEditRecommendationV1['status'], createdAt: new Date(String(row.created_at)).toISOString() }; validateIntelligentEditRecommendationV1(value); return value; }
function mapEvent(row: Record<string, unknown>): EditingDecisionEventV1 { const value: EditingDecisionEventV1 = { schemaVersion: 'EDITING_DECISION_EVENT_V1', id: String(row.id), projectId: String(row.project_id), planId: String(row.plan_id), sentenceId: row.sentence_id ? String(row.sentence_id) : null, eventType: String(row.event_type) as EditingDecisionEventType, previousCandidateId: row.previous_candidate_id ? String(row.previous_candidate_id) : null, nextCandidateId: row.next_candidate_id ? String(row.next_candidate_id) : null, previousShotId: row.previous_shot_id ? String(row.previous_shot_id) : null, nextShotId: row.next_shot_id ? String(row.next_shot_id) : null, evidence: record(row.evidence), createdAt: new Date(String(row.created_at)).toISOString() }; validateEditingDecisionEventV1(value); return value; }

export class IntelligentDecisionService {
  constructor(private readonly db: Pool) {}
  async createPreset(input: CreatePresetInput): Promise<IntelligentEditPresetV1> { validateIntelligentPlannerConfigV1(input.config); const result = await this.db.query('insert into intelligent_edit_presets (id,project_id,name,config,enabled) values ($1,$2,$3,$4,$5) returning *', [input.id || `preset-${randomUUID()}`, input.projectId || null, input.name.trim(), JSON.stringify(input.config), input.enabled ?? true]); return mapPreset(result.rows[0] as Record<string, unknown>); }
  async listPresets(projectId: string): Promise<IntelligentEditPresetV1[]> { const result = await this.db.query('select * from intelligent_edit_presets where project_id is null or project_id=$1 order by project_id nulls first,name', [projectId]); return result.rows.map((row) => mapPreset(row as Record<string, unknown>)); }
  async createDecisionEvent(input: CreateDecisionEventInput): Promise<EditingDecisionEventV1> {
    const plan = await this.db.query('select id from intelligent_edit_plans where id=$1 and project_id=$2', [input.planId, input.projectId]);
    if (!plan.rows[0]) throw new Error('INTELLIGENT_PLAN_NOT_FOUND');
    for (const [candidateId, label] of [[input.previousCandidateId, 'previous'], [input.nextCandidateId, 'next']] as const) if (candidateId) { const candidate = await this.db.query('select id from intelligent_edit_candidates where id=$1 and plan_id=$2', [candidateId, input.planId]); if (!candidate.rows[0]) throw new Error(`INTELLIGENT_${label.toUpperCase()}_CANDIDATE_NOT_FOUND`); }
    const result = await this.db.query('insert into editing_decision_events (id,project_id,plan_id,sentence_id,event_type,previous_candidate_id,next_candidate_id,previous_shot_id,next_shot_id,evidence) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *', [input.id || `decision-${randomUUID()}`, input.projectId, input.planId, input.sentenceId || null, input.eventType, input.previousCandidateId || null, input.nextCandidateId || null, input.previousShotId || null, input.nextShotId || null, JSON.stringify(input.evidence || {})]);
    return mapEvent(result.rows[0] as Record<string, unknown>);
  }
  async listDecisionEvents(projectId: string, planId: string): Promise<EditingDecisionEventV1[]> { const result = await this.db.query('select * from editing_decision_events where project_id=$1 and plan_id=$2 order by created_at,id', [projectId, planId]); return result.rows.map((row) => mapEvent(row as Record<string, unknown>)); }
  async createRecommendation(input: CreateRecommendationInput): Promise<IntelligentEditRecommendationV1> {
    const plan = await this.db.query('select id from intelligent_edit_plans where id=$1 and project_id=$2', [input.planId, input.projectId]); if (!plan.rows[0]) throw new Error('INTELLIGENT_PLAN_NOT_FOUND');
    if (input.presetId) { const preset = await this.db.query('select id from intelligent_edit_presets where id=$1 and (project_id is null or project_id=$2)', [input.presetId, input.projectId]); if (!preset.rows[0]) throw new Error('INTELLIGENT_PRESET_NOT_FOUND'); }
    const result = await this.db.query('insert into intelligent_edit_recommendations (id,project_id,plan_id,preset_id,profile,confidence,alternatives,limitations,evidence) values ($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *', [input.id || `recommendation-${randomUUID()}`, input.projectId, input.planId, input.presetId || null, input.profile.trim(), input.confidence, JSON.stringify(input.alternatives || []), JSON.stringify(input.limitations || []), JSON.stringify(input.evidence || {})]); return mapRecommendation(result.rows[0] as Record<string, unknown>);
  }
  async buildRecommendation(projectId: string, planId: string, presetId?: string | null): Promise<IntelligentEditRecommendationV1> {
    const plan = await this.db.query('select quality from intelligent_edit_plans where id=$1 and project_id=$2', [planId, projectId]); if (!plan.rows[0]) throw new Error('INTELLIGENT_PLAN_NOT_FOUND');
    const quality = record(plan.rows[0].quality); const events = await this.listDecisionEvents(projectId, planId); const issues = Array.isArray(quality.issues) ? quality.issues.map(String) : []; const replacements = events.filter((event) => event.eventType === 'SHOT_REPLACED');
    const alternatives: string[] = []; const limitations: string[] = []; const reasons: string[] = [];
    if (issues.includes('HIGH_ASSET_REPETITION') || issues.includes('HIGH_SHOT_REPETITION')) { alternatives.push('increase-diversity-weight'); reasons.push('plan_quality_repetition'); }
    if (issues.includes('LOW_SEMANTIC_MATCH')) { alternatives.push('review-script-sentence'); limitations.push('semantic-match-below-threshold'); reasons.push('plan_quality_semantic'); }
    if (replacements.length >= 2) { alternatives.push('prefer-alternative-shot-types'); reasons.push('repeated-shot-replacement'); }
    const confidence = Math.max(0.2, Math.min(0.95, 0.45 + reasons.length * 0.12));
    return this.createRecommendation({ projectId, planId, ...(presetId === undefined ? {} : { presetId }), profile: reasons.includes('plan_quality_repetition') ? 'DIVERSITY_FIRST' : replacements.length ? 'SHOT_ALTERNATIVE_PREFERENCE' : 'REVIEW_PLAN', confidence, alternatives, limitations, evidence: { source: 'RecommendationBuilder', planQuality: quality, decisionEventCount: events.length, replacementCount: replacements.length, reasons } });
  }
  async listRecommendations(projectId: string, planId: string): Promise<IntelligentEditRecommendationV1[]> { const result = await this.db.query('select * from intelligent_edit_recommendations where project_id=$1 and plan_id=$2 order by created_at desc,id desc', [projectId, planId]); return result.rows.map((row) => mapRecommendation(row as Record<string, unknown>)); }
}
