import { randomUUID } from 'node:crypto';
import type { Pool } from 'pg';
import { validateIntelligentEditRecommendationV1, type IntelligentEditPresetV1, type IntelligentEditRecommendationV1, type IntelligentPlannerConfigV1 } from '../../../contracts/src/index.js';

export interface CreatePresetInput { id?: string; projectId?: string | null; name: string; config: IntelligentPlannerConfigV1; enabled?: boolean; }
export interface CreateRecommendationInput { id?: string; projectId: string; planId: string; presetId?: string | null; profile: string; confidence: number; alternatives?: string[]; limitations?: string[]; evidence?: Record<string, unknown>; }

function array(value: unknown): string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string') : []; }
function mapPreset(row: Record<string, unknown>): IntelligentEditPresetV1 { return { schemaVersion: 'INTELLIGENT_EDIT_PRESET_V1', id: String(row.id), projectId: row.project_id ? String(row.project_id) : null, name: String(row.name), config: row.config as IntelligentPlannerConfigV1, enabled: Boolean(row.enabled), createdAt: new Date(String(row.created_at)).toISOString() }; }
function mapRecommendation(row: Record<string, unknown>): IntelligentEditRecommendationV1 { const value: IntelligentEditRecommendationV1 = { schemaVersion: 'INTELLIGENT_EDIT_RECOMMENDATION_V1', id: String(row.id), projectId: String(row.project_id), planId: String(row.plan_id), presetId: row.preset_id ? String(row.preset_id) : null, profile: String(row.profile), confidence: Number(row.confidence), alternatives: array(row.alternatives), limitations: array(row.limitations), evidence: row.evidence && typeof row.evidence === 'object' && !Array.isArray(row.evidence) ? row.evidence as Record<string, unknown> : {}, status: String(row.status) as IntelligentEditRecommendationV1['status'], createdAt: new Date(String(row.created_at)).toISOString() }; validateIntelligentEditRecommendationV1(value); return value; }

export class IntelligentDecisionService {
  constructor(private readonly db: Pool) {}
  async createPreset(input: CreatePresetInput): Promise<IntelligentEditPresetV1> { const result = await this.db.query('insert into intelligent_edit_presets (id,project_id,name,config,enabled) values ($1,$2,$3,$4,$5) returning *', [input.id || `preset-${randomUUID()}`, input.projectId || null, input.name.trim(), JSON.stringify(input.config), input.enabled ?? true]); return mapPreset(result.rows[0] as Record<string, unknown>); }
  async listPresets(projectId: string): Promise<IntelligentEditPresetV1[]> { const result = await this.db.query('select * from intelligent_edit_presets where project_id is null or project_id=$1 order by project_id nulls first,name', [projectId]); return result.rows.map((row) => mapPreset(row as Record<string, unknown>)); }
  async createRecommendation(input: CreateRecommendationInput): Promise<IntelligentEditRecommendationV1> { const plan = await this.db.query('select id from intelligent_edit_plans where id=$1 and project_id=$2', [input.planId, input.projectId]); if (!plan.rows[0]) throw new Error('INTELLIGENT_PLAN_NOT_FOUND'); const result = await this.db.query('insert into intelligent_edit_recommendations (id,project_id,plan_id,preset_id,profile,confidence,alternatives,limitations,evidence) values ($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *', [input.id || `recommendation-${randomUUID()}`, input.projectId, input.planId, input.presetId || null, input.profile.trim(), input.confidence, JSON.stringify(input.alternatives || []), JSON.stringify(input.limitations || []), JSON.stringify(input.evidence || {})]); return mapRecommendation(result.rows[0] as Record<string, unknown>); }
  async listRecommendations(projectId: string, planId: string): Promise<IntelligentEditRecommendationV1[]> { const result = await this.db.query('select * from intelligent_edit_recommendations where project_id=$1 and plan_id=$2 order by created_at desc,id desc', [projectId, planId]); return result.rows.map((row) => mapRecommendation(row as Record<string, unknown>)); }
}
