packages:
  - apps/*
  - workers/*
  - packages/*
  - packages/modules/*
allowBuilds:
  '@embedded-postgres/windows-x64': true
  electron-winstaller: true
  esbuild: true
  ffmpeg-static: true
minimumReleaseAgeExclude:
  - electron@44.5.0
