'use client';

import { useRouter } from 'next/navigation';
import { useState, type FormEvent } from 'react';

type Item = { title: string; script: string; voicePath: string };
export function WorkbenchForm({ mode }: { mode: 'SCRIPT' | 'MIX' }) {
  const router = useRouter(); const [script, setScript] = useState(''); const [voicePath, setVoicePath] = useState(''); const [items, setItems] = useState<Item[]>([{ title: '', script: '', voicePath: '' }]); const [roots, setRoots] = useState(['']); const [outputRoot, setOutputRoot] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const addRoot = () => setRoots((current) => [...current, '']); const removeRoot = (index: number) => setRoots((current) => current.length === 1 ? current : current.filter((_, itemIndex) => itemIndex !== index));
  const submit = async (event?: FormEvent, forceTest = false) => { event?.preventDefault(); setBusy(true); setMessage(''); try { const payload = { mode, script: mode === 'SCRIPT' ? script : undefined, ...(mode === 'SCRIPT' && voicePath.trim() ? { voicePath: voicePath.trim() } : {}), items: mode === 'MIX' ? items.filter((item) => item.script.trim()).map((item) => ({ title: item.title.trim() || undefined, script: item.script.trim(), ...(item.voicePath.trim() ? { voicePath: item.voicePath.trim() } : {}) })) : undefined, testOnly: mode === 'MIX' && forceTest, sourceRoots: roots.map((root) => root.trim()).filter(Boolean), ...(outputRoot.trim() ? { outputRoot: outputRoot.trim() } : {}) }; const response = await fetch('/api/v1/edit/sessions', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json() as { batchId?: string; error?: { message?: string } }; if (!response.ok || !data.batchId) throw new Error(data.error?.message || '剪辑任务创建失败。'); router.push(`/edit/history?batch=${encodeURIComponent(data.batchId)}`); } catch (error) { setMessage(error instanceof Error ? error.message : '剪辑任务创建失败。'); } finally { setBusy(false); } };
  return <form className="edit-form" onSubmit={(event) => void submit(event)}><section className="card"><div className="section-title"><h2>1. 文案与音频</h2><span>{mode === 'MIX' ? `${items.length} 条任务` : '自动识别段落'}</span></div>{mode === 'SCRIPT' ? <><label>输入视频文案<textarea value={script} onChange={(event) => setScript(event.target.value)} placeholder="把要表达的内容粘贴到这里……" required /></label><label>配音文件路径（可选）<input value={voicePath} onChange={(event) => setVoicePath(event.target.value)} placeholder="例如：F:\\音频\\旁白.mp3" /></label></> : <>{items.map((item, index) => <div className="batch-row" key={index}><label>任务 {index + 1} 标题<input value={item.title} onChange={(event) => setItems((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, title: event.target.value } : row))} placeholder="可选" /></label><label>文案<textarea value={item.script} onChange={(event) => setItems((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, script: event.target.value } : row))} placeholder="输入这一条视频的文案" required /></label><label>配音路径<input value={item.voicePath} onChange={(event) => setItems((current) => current.map((row, rowIndex) => rowIndex === index ? { ...row, voicePath: event.target.value } : row))} placeholder="可选" /></label>{items.length > 1 && <button type="button" onClick={() => setItems((current) => current.filter((_, rowIndex) => rowIndex !== index))}>删除这条</button>}</div>)}<button type="button" className="secondary-action" onClick={() => setItems((current) => [...current, { title: '', script: '', voicePath: '' }])}>+ 添加一条</button><p className="muted">配音文件会在服务端授权根目录内校验并导入当前剪辑任务。</p></>}</section><section className="card"><div className="section-title"><h2>2. 素材文件夹</h2><span>支持多个目录</span></div>{roots.map((root, index) => <div className="folder-row" key={index}><label><span>素材目录 {index + 1}</span><input value={root} onChange={(event) => setRoots((current) => current.map((value, rootIndex) => rootIndex === index ? event.target.value : value))} placeholder="例如：F:\\素材\\商品" required /></label>{roots.length > 1 && <button type="button" onClick={() => removeRoot(index)}>删除</button>}</div>)}<button type="button" className="secondary-action" onClick={addRoot}>+ 添加素材文件夹</button><p className="muted">提交后会验证目录、扫描视频并合并去重；目录必须位于服务端授权根目录内。</p></section><section className="card"><div className="section-title"><h2>3. 输出位置</h2><span>可选</span></div><label>输出文件夹<input value={outputRoot} onChange={(event) => setOutputRoot(event.target.value)} placeholder="例如：F:\\ContentOS输出\\2026-09-18" /></label><p className="muted">输出目录必须位于 CONTENTOS_OUTPUT_ROOTS 允许范围内，完成后可一键导出。</p></section>{message && <p className="form-error">{message}</p>}{mode === 'MIX' && <button type="button" className="secondary-action" onClick={() => void submit(undefined, true)} disabled={busy}>生成 1 条测试</button>}<button className="primary-action" type="submit" disabled={busy}>{busy ? '正在准备素材……' : mode === 'SCRIPT' ? '开始剪辑' : '开始全部混剪'}</button></form>;
}
