'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';

type VoiceProfile = { id: string; name: string; provider: string; language: string; referenceAssetId: string | null; status: string };
type AvatarClip = { id: string; name: string; assetId: string; status: string; durationMs: number | null };
type AvatarProfile = { id: string; name: string; ownerName: string; clips: AvatarClip[] };
type Generation = { id: string; status: string; text?: string; outputAssetId?: string | null; error?: { message?: string } | null; jobId?: string };
type Capabilities = { speech?: { status?: string; providerId?: string; voiceClone?: boolean; emotion?: boolean; speed?: boolean; languages?: string[] }; avatar?: { status?: string; providerId?: string; requiresPublicUrl?: boolean } };

const terminal = new Set(['SUCCEEDED', 'FAILED', 'CANCELLED']);
async function readError(response: Response): Promise<string> { try { const body = await response.json() as { error?: { message?: string } }; return body.error?.message || '请求失败'; } catch { return '请求失败'; } }

export default function DigitalHumanWorkspacePage() {
  const { id: projectId } = useParams<{ id: string }>();
  const [voices, setVoices] = useState<VoiceProfile[]>([]); const [avatars, setAvatars] = useState<AvatarProfile[]>([]); const [speeches, setSpeeches] = useState<Generation[]>([]); const [avatarGenerations, setAvatarGenerations] = useState<Generation[]>([]);
  const [voiceId, setVoiceId] = useState(''); const [avatarId, setAvatarId] = useState(''); const [clipId, setClipId] = useState(''); const [speechAssetId, setSpeechAssetId] = useState(''); const [script, setScript] = useState(''); const [voiceName, setVoiceName] = useState(''); const [referenceAssetId, setReferenceAssetId] = useState(''); const [avatarName, setAvatarName] = useState(''); const [ownerName, setOwnerName] = useState(''); const [clipName, setClipName] = useState(''); const [clipAssetId, setClipAssetId] = useState(''); const [clipDurationMs, setClipDurationMs] = useState('');
  const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(''); const [capabilities, setCapabilities] = useState<Capabilities>({}); const selectedAvatar = useMemo(() => avatars.find((avatar) => avatar.id === avatarId), [avatars, avatarId]);

  const refresh = useCallback(async () => {
    const [capabilityResponse, voiceResponse, avatarResponse, speechResponse, generationResponse] = await Promise.all([fetch(`/api/v1/projects/${projectId}/digital-human/capabilities`), fetch(`/api/v1/projects/${projectId}/digital-human/voices`), fetch(`/api/v1/projects/${projectId}/digital-human/avatars`), fetch(`/api/v1/projects/${projectId}/digital-human/speech-generations`), fetch(`/api/v1/projects/${projectId}/digital-human/avatar-generations`)]);
    if (capabilityResponse.ok) setCapabilities(await capabilityResponse.json() as Capabilities);
    if (voiceResponse.ok) { const next = (await voiceResponse.json() as { items: VoiceProfile[] }).items; setVoices(next); if (!voiceId && next[0]) setVoiceId(next[0].id); }
    if (avatarResponse.ok) { const next = (await avatarResponse.json() as { items: AvatarProfile[] }).items; setAvatars(next); if (!avatarId && next[0]) setAvatarId(next[0].id); }
    if (speechResponse.ok) { const next = (await speechResponse.json() as { items: Generation[] }).items; setSpeeches(next); const latest = next.find((item) => item.status === 'SUCCEEDED' && item.outputAssetId); if (!speechAssetId && latest?.outputAssetId) setSpeechAssetId(latest.outputAssetId); }
    if (generationResponse.ok) setAvatarGenerations((await generationResponse.json() as { items: Generation[] }).items);
  }, [projectId, voiceId, avatarId, speechAssetId]);
  useEffect(() => { void refresh(); }, [refresh]);
  useEffect(() => { const active = speeches.some((item) => !terminal.has(item.status)) || avatarGenerations.some((item) => !terminal.has(item.status)); if (!active) return; const timer = window.setInterval(() => { void refresh(); }, 1_000); return () => window.clearInterval(timer); }, [speeches, avatarGenerations, refresh]);

  const createVoice = async () => { setBusy(true); setNotice(''); try { const response = await fetch(`/api/v1/projects/${projectId}/digital-human/voices`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: voiceName.trim(), ...(referenceAssetId.trim() ? { referenceAssetId: referenceAssetId.trim() } : {}) }) }); if (!response.ok) throw new Error(await readError(response)); const voice = await response.json() as VoiceProfile; setVoiceId(voice.id); setVoiceName(''); setReferenceAssetId(''); setNotice('音色已创建。'); await refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : '音色创建失败。'); } finally { setBusy(false); } };
  const createAvatar = async () => { setBusy(true); setNotice(''); try { const response = await fetch(`/api/v1/projects/${projectId}/digital-human/avatars`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: avatarName.trim(), ownerName: ownerName.trim() }) }); if (!response.ok) throw new Error(await readError(response)); const avatar = await response.json() as AvatarProfile; setAvatarId(avatar.id); setAvatarName(''); setOwnerName(''); setNotice('人物 Profile 已创建，请继续添加底片。'); await refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : '人物创建失败。'); } finally { setBusy(false); } };
  const createClip = async () => { setBusy(true); setNotice(''); try { const response = await fetch(`/api/v1/projects/${projectId}/digital-human/avatar-clips`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ avatarProfileId: avatarId, assetId: clipAssetId.trim(), name: clipName.trim(), ...(clipDurationMs.trim() ? { durationMs: Number(clipDurationMs) } : {}) }) }); if (!response.ok) throw new Error(await readError(response)); const clip = await response.json() as AvatarClip; setClipId(clip.id); setClipName(''); setClipAssetId(''); setClipDurationMs(''); setNotice('人物底片已创建。'); await refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : '底片创建失败。'); } finally { setBusy(false); } };
  const generateSpeech = async () => { setBusy(true); setNotice(''); try { const response = await fetch(`/api/v1/projects/${projectId}/digital-human/speech-generations`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ voiceProfileId: voiceId, text: script }) }); if (!response.ok) throw new Error(await readError(response)); setNotice('配音 Job 已提交，页面会自动刷新状态。'); setScript(''); await refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : '配音提交失败。'); } finally { setBusy(false); } };
  const sendAvatarToEdit = async (generationId: string) => { setBusy(true); setNotice(''); try { const response = await fetch(`/api/v1/projects/${projectId}/digital-human/avatar-generations/${generationId}/edit-manifest`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ includeSubtitles: true }) }); if (!response.ok) throw new Error(await readError(response)); const result = await response.json() as { editUrl?: string }; setNotice('已创建现有视频工作台的 Edit Manifest 和 Render Job。'); if (result.editUrl) window.location.assign(result.editUrl); } catch (error) { setNotice(error instanceof Error ? error.message : '进入视频工作台失败。'); } finally { setBusy(false); } };
  const generateAvatar = async () => { setBusy(true); setNotice(''); try { const response = await fetch(`/api/v1/projects/${projectId}/digital-human/avatar-generations`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ avatarProfileId: avatarId, avatarClipId: clipId, speechAssetId }) }); if (!response.ok) throw new Error(await readError(response)); setNotice('数字人 Job 已提交，页面会自动刷新状态。'); await refresh(); } catch (error) { setNotice(error instanceof Error ? error.message : '数字人提交失败。'); } finally { setBusy(false); } };

  return <main className="shell project-workspace">
    <div className="workspace-header"><div><p className="eyebrow">Digital Human V1 / Project {projectId}</p><h1>数字人工作台</h1><p className="muted">声音 → 数字人 → 成片。生成任务进入 durable Job，结果回到 Asset。</p></div><Link className="module-nav-link" href={`/projects/${projectId}`}>返回项目</Link></div>
    {notice && <section className="card status" role="status">{notice}</section>}
    <section className="card"><strong>运行能力</strong><span className="muted">语音：{capabilities.speech?.status || '检测中'}{capabilities.speech?.providerId ? ` · ${capabilities.speech.providerId}` : ''} · 数字人：{capabilities.avatar?.status || '检测中'}{capabilities.avatar?.providerId ? ` · ${capabilities.avatar.providerId}` : ''}</span></section>
    <div className="workspace-grid">
      <section className="card"><h2>① 声音</h2><label>已有音色<select value={voiceId} onChange={(event) => setVoiceId(event.target.value)}><option value="">请选择</option>{voices.map((voice) => <option key={voice.id} value={voice.id}>{voice.name} · {voice.status}</option>)}</select></label><details><summary>创建 Voice Profile</summary><label>名称<input value={voiceName} onChange={(event) => setVoiceName(event.target.value)} placeholder="例如：董哥" /></label><label>参考音频 Asset ID<input value={referenceAssetId} onChange={(event) => setReferenceAssetId(event.target.value)} placeholder="从素材页复制 AUDIO Asset ID" /></label><button type="button" disabled={busy || !voiceName.trim()} onClick={() => void createVoice()}>创建音色</button></details><label>文案<textarea value={script} onChange={(event) => setScript(event.target.value)} placeholder="输入需要生成的口播文案" /></label><button type="button" disabled={busy || !voiceId || !script.trim()} onClick={() => void generateSpeech()}>生成配音</button><div className="revision-list">{speeches.slice(0, 5).map((item) => <div key={item.id}><strong>{item.status}</strong><small>{item.text || item.id}</small>{item.outputAssetId && <><audio controls preload="none" src={`/api/v1/projects/${projectId}/assets/${item.outputAssetId}/content`} /><small><a href={`/api/v1/projects/${projectId}/digital-human/speech-generations/${item.id}/subtitles?format=srt`}>下载 SRT</a> · <a href={`/api/v1/projects/${projectId}/digital-human/speech-generations/${item.id}/subtitles?format=ass`}>下载 ASS</a></small></>}</div>)}</div></section>
      <section className="card"><h2>② 数字人</h2><label>人物<select value={avatarId} onChange={(event) => { setAvatarId(event.target.value); setClipId(''); }}><option value="">请选择</option>{avatars.map((avatar) => <option key={avatar.id} value={avatar.id}>{avatar.name} · {avatar.ownerName}</option>)}</select></label><details><summary>创建 Avatar Profile</summary><label>人物名称<input value={avatarName} onChange={(event) => setAvatarName(event.target.value)} placeholder="例如：品牌主持人" /></label><label>归属人<input value={ownerName} onChange={(event) => setOwnerName(event.target.value)} placeholder="可选" /></label><button type="button" disabled={busy || !avatarName.trim()} onClick={() => void createAvatar()}>创建人物</button></details><details><summary>添加人物底片</summary><label>视频 Asset ID<input value={clipAssetId} onChange={(event) => setClipAssetId(event.target.value)} placeholder="从素材页复制 VIDEO Asset ID" /></label><label>底片名称<input value={clipName} onChange={(event) => setClipName(event.target.value)} placeholder="例如：正面站姿" /></label><label>时长（毫秒）<input type="number" min="1" value={clipDurationMs} onChange={(event) => setClipDurationMs(event.target.value)} placeholder="可选" /></label><button type="button" disabled={busy || !avatarId || !clipAssetId.trim() || !clipName.trim()} onClick={() => void createClip()}>添加底片</button></details><label>底片<select value={clipId} onChange={(event) => setClipId(event.target.value)}><option value="">请选择</option>{selectedAvatar?.clips.map((clip) => <option key={clip.id} value={clip.id}>{clip.name}{clip.durationMs ? ` · ${Math.round(clip.durationMs / 1000)}s` : ''}</option>)}</select></label><label>配音 Asset ID<input value={speechAssetId} onChange={(event) => setSpeechAssetId(event.target.value)} placeholder="选择上方成功生成的音频，或粘贴 Asset ID" /></label><button type="button" disabled={busy || !avatarId || !clipId || !speechAssetId} onClick={() => void generateAvatar()}>生成数字人</button><div className="revision-list">{avatarGenerations.slice(0, 5).map((item) => <div key={item.id}><strong>{item.status}</strong><small>{item.error?.message || item.id}</small>{item.outputAssetId && <><video controls preload="none" src={`/api/v1/projects/${projectId}/assets/${item.outputAssetId}/content`} /><button type="button" disabled={busy} onClick={() => void sendAvatarToEdit(item.id)}>进入视频工作台</button></>}</div>)}</div></section>
      <section className="card"><h2>③ 成片</h2><p className="muted">数字人视频生成后，继续使用现有视频剪辑工作台完成字幕、BGM、画幅和 Render。</p><Link className="module-nav-link" href={`/projects/${projectId}/video`}>打开视频工作台</Link><p className="muted">SRT、ASS 与 Edit Manifest 字幕 cue 已由生成结果提供，可在视频工作台继续合成。</p></section>
    </div>
  </main>;
}
