import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdir, mkdtemp, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { createDatabase, migrateUp } from '../../packages/database/src/index.js';
import { ProjectService } from '../../packages/modules/project/src/index.js';
import { DirectorV1Service } from '../../packages/modules/director/src/index.js';
import { AssetService, AssetCatalogService, LocalMediaSourceService } from '../../packages/modules/asset/src/index.js';
import { JobService } from '../../packages/modules/job/src/index.js';
import { VideoAdjustmentService, VideoService } from '../../packages/modules/video/src/index.js';
import { LocalStorageProvider } from '../../packages/infrastructure/storage/src/index.js';
import { generateFixtureVideo, probeMedia } from '../../packages/infrastructure/ffmpeg/src/index.js';
import { buildApi } from '../../apps/api/src/app.js';
import { createVideoWorker } from '../../workers/video-worker/src/main.js';

const databaseUrl = process.env.DATABASE_URL || 'postgresql://contentos_dev:change-me@127.0.0.1:55432/contentos_test';
const ffmpegPath = process.env.FFMPEG_PATH || 'ffmpeg';
const ffprobePath = process.env.FFPROBE_PATH || 'ffprobe';

async function waitForJob(jobs: JobService, id: string): Promise<Awaited<ReturnType<JobService['get']>>> {
  const deadline = Date.now() + 30_000;
  while (Date.now() < deadline) { const job = await jobs.get(id); if (job && ['SUCCEEDED', 'FAILED', 'CANCELLED'].includes(job.state)) return job; await new Promise((resolve) => setTimeout(resolve, 40)); }
  return jobs.get(id);
}

test('Auto Edit V1 API and local vertical slice use durable scan, pool, edits and exact render', async () => {
  const root = await mkdtemp(join(tmpdir(), 'contentos-auto-edit-v1-')); const previousRoots = process.env.CONTENTOS_LOCAL_MEDIA_ROOTS; process.env.CONTENTOS_LOCAL_MEDIA_ROOTS = root;
  const db = await createDatabase(databaseUrl); await migrateUp(db); const project = await new ProjectService(db).create(`Auto Edit API ${randomUUID()}`); const director = new DirectorV1Service(db); const brief = await director.createBrief(project.id, { topic: '零售扩张', targetPlatform: '短视频', channelPositioning: '商业观察', targetDurationSeconds: 30, contentType: '知识', audience: '经营者', coreThesis: '先验证再扩张', tone: '清晰', ctaGoal: '收藏', referenceMaterial: '调研', mustInclude: ['欧洲'], mustAvoid: ['夸大'], requirements: {}, createdBy: 'integration' }); const scriptAggregate = await director.createScript(project.id, brief.id); const acceptedScript = await director.createScriptRevision(project.id, scriptAggregate.id, { origin: 'MANUAL', title: '零售扩张', titleCandidates: ['零售扩张'], coverText: '零售扩张', topicKeywords: ['零售'], hook: '欧洲零售扩张。', body: '折扣门店增长？数据图表变化！顾客购物增加。', cta: '收藏。', createdBy: 'integration' }); await director.acceptScript(project.id, acceptedScript.id); const storage = new LocalStorageProvider(join(root, 'storage')); const jobs = new JobService(db); const catalog = new AssetCatalogService(db); const video = new VideoService(db, storage, jobs, catalog); const localMedia = new LocalMediaSourceService({ db, allowedRoots: [root], ffprobePath }); const assets = new AssetService(db, storage, (path) => probeMedia(path, ffprobePath)); const app = await buildApi({ db, storage }); const worker = createVideoWorker({ db, storage, jobs, assets, video, localMedia, ffmpegPath, ffprobePath, workerId: `auto-edit-${randomUUID()}`, pollIntervalMs: 20 });
  const fixtureDir = join(root, '素材'); await mkdir(fixtureDir, { recursive: true }); for (const [name, color] of [['欧洲门店.mp4', 'blue'], ['折扣货架.mp4', 'red'], ['数据图表.mp4', 'green'], ['顾客购物.mp4', 'yellow'], ['仓库补货.mp4', 'purple']] as const) await generateFixtureVideo(join(fixtureDir, name), ffmpegPath, color, 3);
  try {
    await worker.start();
    const currentScript = await app.inject({ method: 'GET', url: `/api/v1/projects/${project.id}/video/current-script` }); assert.equal(currentScript.statusCode, 200); assert.equal(currentScript.json().scriptRevisionId, acceptedScript.id); assert.match(currentScript.json().body, /欧洲零售扩张/);
    const preview = await app.inject({ method: 'POST', url: '/api/v1/video/sentence-preview', payload: { script: '欧洲零售扩张。折扣门店增长？数据图表变化！顾客购物增加。收藏。' } }); assert.equal(preview.statusCode, 200); assert.equal(preview.json().items.length, 5);
    const forbidden = await app.inject({ method: 'POST', url: '/api/v1/video/local-media/scan', payload: { projectId: project.id, sourceRoot: 'C:\\Windows', recursive: true } }); assert.equal(forbidden.statusCode, 403);
    const scanResponse = await app.inject({ method: 'POST', url: '/api/v1/video/local-media/scan', payload: { projectId: project.id, sourceRoot: fixtureDir, recursive: true } }); assert.equal(scanResponse.statusCode, 202, scanResponse.body); const scanJob = scanResponse.json(); const scanCompleted = await waitForJob(jobs, scanJob.jobId); assert.equal(scanCompleted?.state, 'SUCCEEDED');
    const scan = await app.inject({ method: 'GET', url: `/api/v1/video/local-media/scans/${scanJob.scanId}?projectId=${project.id}` }); assert.equal(scan.statusCode, 200); assert.equal(scan.json().files.length, 5); assert.equal('sourcePath' in scan.json().files[0], false); assert.equal(scan.json().progress.available, 5); const selectedLocalIds = scan.json().files.filter((file: { available: boolean }, index: number) => file.available && index < 3).map((file: { relativePath: string }) => `${scanJob.sourceRootId}:${file.relativePath}`);
    const subsetPlanResponse = await app.inject({ method: 'POST', url: `/api/v1/projects/${project.id}/video/montage-plans`, payload: { mode: 'SCRIPT', script: '欧洲门店。折扣货架。', scanId: scanJob.scanId, selectedLocalMediaIds: selectedLocalIds, seed: 7, minClipDurationMs: 1_000, maxClipDurationMs: 2_000 } }); assert.equal(subsetPlanResponse.statusCode, 201, subsetPlanResponse.body); assert.ok(subsetPlanResponse.json().manifest.timeline.every((clip: { assetId: string }) => selectedLocalIds.includes(clip.assetId)));
    const scriptPlanResponse = await app.inject({ method: 'POST', url: `/api/v1/projects/${project.id}/video/montage-plans`, payload: { mode: 'SCRIPT', script: currentScript.json().body, scanId: scanJob.scanId, seed: 7, minClipDurationMs: 1_000, maxClipDurationMs: 2_000 } }); assert.equal(scriptPlanResponse.statusCode, 201, scriptPlanResponse.body); const scriptPlan = scriptPlanResponse.json(); assert.equal(scriptPlan.manifest.timeline.length, 5); assert.equal(scriptPlan.manifest.metadata.editMode, 'SCRIPT'); assert.equal(scriptPlan.manifest.metadata.localMediaSourceRootId, scanJob.sourceRootId); assert.equal(scriptPlan.manifest.metadata.localMediaScanId, scanJob.scanId);
    const rematch = await app.inject({ method: 'POST', url: `/api/v1/projects/${project.id}/video/adjustments`, payload: { parentManifestId: scriptPlan.id, operations: [{ type: 'REMATCH', clipIndex: 0, seed: 9 }], createdBy: 'integration', idempotencyKey: `rematch-${randomUUID()}` } }); assert.equal(rematch.statusCode, 201, rematch.body); const rematched = rematch.json(); assert.notEqual(rematched.manifest.timeline[0].assetId, scriptPlan.manifest.timeline[0].assetId); assert.equal(rematched.manifest.timeline.length, 5); assert.ok(rematched.manifest.timeline[0].matching);
    const scriptRender = await app.inject({ method: 'POST', url: `/api/v1/projects/${project.id}/video/manifests/${rematched.id}/render` }); assert.equal(scriptRender.statusCode, 201, scriptRender.body); const scriptRendered = await waitForJob(jobs, scriptRender.json().id); assert.equal(scriptRendered?.state, 'SUCCEEDED'); assert.ok((scriptRendered?.result as { outputAssetId?: string })?.outputAssetId);
    const planResponse = await app.inject({ method: 'POST', url: `/api/v1/projects/${project.id}/video/montage-plans`, payload: { mode: 'RANDOM', script: currentScript.json().body, scanId: scanJob.scanId, seed: 7, minClipDurationMs: 1_000, maxClipDurationMs: 2_000 } }); assert.equal(planResponse.statusCode, 201, planResponse.body); const plan = planResponse.json(); assert.equal(plan.manifest.timeline.length, 5); assert.equal(plan.manifest.metadata.editMode, 'RANDOM');
    const reroll = await app.inject({ method: 'POST', url: `/api/v1/projects/${project.id}/video/adjustments`, payload: { parentManifestId: plan.id, operations: [{ type: 'REROLL', clipIndex: 0, seed: 9 }], createdBy: 'integration', idempotencyKey: `reroll-${randomUUID()}` } }); assert.equal(reroll.statusCode, 201, reroll.body); const rerolled = reroll.json(); assert.notEqual(rerolled.revision, plan.revision); assert.equal(rerolled.manifest.timeline.length, 5);
    const replacementId = `${scanJob.sourceRootId}:折扣货架.mp4`;
    const replace = await app.inject({ method: 'POST', url: `/api/v1/projects/${project.id}/video/adjustments`, payload: { parentManifestId: rerolled.id, operations: [{ type: 'REPLACE', clipIndex: 0, assetId: replacementId }], createdBy: 'integration', idempotencyKey: `replace-${randomUUID()}` } }); assert.equal(replace.statusCode, 201, replace.body);
    const content = await app.inject({ method: 'GET', url: `/api/v1/video/local-media/content?projectId=${project.id}&sourceRootId=${scanJob.sourceRootId}&fileId=${encodeURIComponent(replacementId)}`, headers: { range: 'bytes=0-15' } }); assert.equal(content.statusCode, 206); assert.match(content.headers['content-type'] || '', /^video\//); const normalContent = await app.inject({ method: 'GET', url: `/api/v1/video/local-media/content?projectId=${project.id}&sourceRootId=${scanJob.sourceRootId}&fileId=${encodeURIComponent(replacementId)}` }); assert.equal(normalContent.statusCode, 200); assert.ok(Number(normalContent.headers['content-length']) > 0); const traversal = await app.inject({ method: 'GET', url: `/api/v1/video/local-media/content?projectId=${project.id}&sourceRootId=${scanJob.sourceRootId}&fileId=${encodeURIComponent(`${scanJob.sourceRootId}:../secret.mp4`)}` }); assert.equal(traversal.statusCode, 404); const wrongRoot = await app.inject({ method: 'GET', url: `/api/v1/video/local-media/content?projectId=${project.id}&sourceRootId=other-root&fileId=${encodeURIComponent(replacementId)}` }); assert.equal(wrongRoot.statusCode, 404);
    const render = await app.inject({ method: 'POST', url: `/api/v1/projects/${project.id}/video/manifests/${replace.json().id}/render` }); assert.equal(render.statusCode, 201, render.body); const rendered = await waitForJob(jobs, render.json().id); assert.equal(rendered?.state, 'SUCCEEDED'); assert.ok((rendered?.result as { outputAssetId?: string })?.outputAssetId); await rm(join(fixtureDir, '折扣货架.mp4')); const deleted = await app.inject({ method: 'GET', url: `/api/v1/video/local-media/content?projectId=${project.id}&sourceRootId=${scanJob.sourceRootId}&fileId=${encodeURIComponent(replacementId)}` }); assert.equal(deleted.statusCode, 404);
  } finally {
    await worker.shutdown('test'); await app.close(); await db.query('delete from job_events where job_id in (select id from jobs where project_id = $1)', [project.id]); await db.query('delete from job_attempts where job_id in (select id from jobs where project_id = $1)', [project.id]); await db.query('delete from renders where project_id = $1', [project.id]); await db.query('delete from jobs where project_id = $1', [project.id]); await db.query('delete from edit_manifests where project_id = $1', [project.id]); await db.query('delete from local_media_scans where project_id = $1', [project.id]); await db.query('delete from project_assets where project_id = $1', [project.id]); await db.query('delete from assets where project_id = $1', [project.id]); await db.query('delete from director_project_state where project_id = $1', [project.id]); await db.query('delete from director_script_revisions where project_id = $1', [project.id]); await db.query('delete from director_scripts where project_id = $1', [project.id]); await db.query('delete from director_briefs where project_id = $1', [project.id]); await db.query('delete from content_projects where id = $1', [project.id]); await db.end(); await rm(root, { recursive: true, force: true }); if (previousRoots === undefined) delete process.env.CONTENTOS_LOCAL_MEDIA_ROOTS; else process.env.CONTENTOS_LOCAL_MEDIA_ROOTS = previousRoots;
  }
});

test('mixed project branding and local content plan, adjust and render', async () => {
  const root = await mkdtemp(join(tmpdir(), 'contentos-auto-edit-mixed-')); const previousRoots = process.env.CONTENTOS_LOCAL_MEDIA_ROOTS; process.env.CONTENTOS_LOCAL_MEDIA_ROOTS = root;
  const db = await createDatabase(databaseUrl); await migrateUp(db); const project = await new ProjectService(db).create(`Mixed Auto Edit ${randomUUID()}`); const storage = new LocalStorageProvider(join(root, 'storage')); const jobs = new JobService(db); const catalog = new AssetCatalogService(db); const video = new VideoService(db, storage, jobs, catalog); const localMedia = new LocalMediaSourceService({ db, allowedRoots: [root], ffprobePath }); const assets = new AssetService(db, storage, (path) => probeMedia(path, ffprobePath)); const app = await buildApi({ db, storage }); const worker = createVideoWorker({ db, storage, jobs, assets, video, localMedia, ffmpegPath, ffprobePath, workerId: `auto-edit-mixed-${randomUUID()}`, pollIntervalMs: 20 });
  const fixtureDir = join(root, 'local'); await mkdir(fixtureDir, { recursive: true });
  try {
    await generateFixtureVideo(join(fixtureDir, 'local-a.mp4'), ffmpegPath, 'blue', 3); await generateFixtureVideo(join(fixtureDir, 'local-b.mp4'), ffmpegPath, 'green', 3); await generateFixtureVideo(join(fixtureDir, 'local-c.mp4'), ffmpegPath, 'red', 3);
    const introPath = join(root, 'project-intro.mp4'); const outroPath = join(root, 'project-outro.mp4'); await generateFixtureVideo(introPath, ffmpegPath, 'black', 1); await generateFixtureVideo(outroPath, ffmpegPath, 'white', 1);
    const intro = await assets.importFile({ projectId: project.id, sourcePath: introPath, kind: 'VIDEO' }); const outro = await assets.importFile({ projectId: project.id, sourcePath: outroPath, kind: 'VIDEO' });
    await worker.start(); const scanResponse = await app.inject({ method: 'POST', url: '/api/v1/video/local-media/scan', payload: { projectId: project.id, sourceRoot: fixtureDir, recursive: true } }); assert.equal(scanResponse.statusCode, 202); const scanJob = scanResponse.json(); assert.equal((await waitForJob(jobs, scanJob.jobId))?.state, 'SUCCEEDED');
    const scan = await app.inject({ method: 'GET', url: `/api/v1/video/local-media/scans/${scanJob.scanId}?projectId=${project.id}` }); const localIds = scan.json().files.filter((file: { available: boolean }) => file.available).map((file: { relativePath: string }) => `${scanJob.sourceRootId}:${file.relativePath}`); assert.equal(localIds.length, 3);
    const plan = await app.inject({ method: 'POST', url: `/api/v1/projects/${project.id}/video/montage-plans`, payload: { mode: 'SCRIPT', script: '第一句话。第二句话。', scanId: scanJob.scanId, selectedLocalMediaIds: localIds, videoAssetIds: [], introAssetId: intro.id, outroAssetId: outro.id, minClipDurationMs: 1000, maxClipDurationMs: 2000, preferUnusedMedia: true } }); assert.equal(plan.statusCode, 201, plan.body); const planned = plan.json(); assert.equal(planned.manifest.timeline[0].assetId, intro.id); assert.equal(planned.manifest.timeline.at(-1).assetId, outro.id); assert.ok(planned.manifest.timeline.slice(1, -1).every((clip: { assetId: string }) => localIds.includes(clip.assetId)));
    const replacement = localIds.find((id: string) => id !== planned.manifest.timeline[1].assetId) || localIds[0]; const adjusted = await app.inject({ method: 'POST', url: `/api/v1/projects/${project.id}/video/adjustments`, payload: { parentManifestId: planned.id, operations: [{ type: 'REMATCH', clipIndex: 1, seed: 4 }, { type: 'REPLACE', clipIndex: 2, assetId: replacement }, { type: 'TRIM', clipIndex: 1, sourceInMs: 0, durationMs: 1000 }], createdBy: 'integration', idempotencyKey: `mixed-${randomUUID()}` } }); assert.equal(adjusted.statusCode, 201, adjusted.body); const revised = adjusted.json(); assert.equal(revised.manifest.timeline[0].assetId, intro.id); assert.equal(revised.manifest.timeline.at(-1).assetId, outro.id);
    const render = await app.inject({ method: 'POST', url: `/api/v1/projects/${project.id}/video/manifests/${revised.id}/render` }); assert.equal(render.statusCode, 201); const rendered = await waitForJob(jobs, render.json().id); assert.equal(rendered?.state, 'SUCCEEDED', (rendered?.error as { message?: string } | null)?.message); assert.ok((rendered?.result as { outputAssetId?: string })?.outputAssetId);
  } finally { await worker.shutdown('test'); await app.close(); await db.query('delete from job_events where job_id in (select id from jobs where project_id = $1)', [project.id]); await db.query('delete from job_attempts where job_id in (select id from jobs where project_id = $1)', [project.id]); await db.query('delete from renders where project_id = $1', [project.id]); await db.query('delete from jobs where project_id = $1', [project.id]); await db.query('delete from edit_manifests where project_id = $1', [project.id]); await db.query('delete from local_media_scans where project_id = $1', [project.id]); await db.query('delete from project_assets where project_id = $1', [project.id]); await db.query('delete from assets where project_id = $1', [project.id]); await db.query('delete from content_projects where id = $1', [project.id]); await db.end(); await rm(root, { recursive: true, force: true }); if (previousRoots === undefined) delete process.env.CONTENTOS_LOCAL_MEDIA_ROOTS; else process.env.CONTENTOS_LOCAL_MEDIA_ROOTS = previousRoots; }
});
