'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { ClipInspector } from '../../../../components/video/clip-inspector';
import { ClipPreview } from '../../../../components/video/clip-preview';
import { EditModeSelector, type EditMode } from '../../../../components/video/edit-mode-selector';
import { LocalMediaScanStatus } from '../../../../components/video/local-media-scan-status';
import { ManifestTimeline } from '../../../../components/video/manifest-timeline';
import { ScriptSourceSelector } from '../../../../components/video/script-source-selector';
import { StatusBadge } from '../../../_components/status-badge';

// Protocol names remain internal: TRIM / REMOVE / REORDER / REPLACE / REROLL / REMATCH / EDIT_MANIFEST_V0.
// Compatibility contract: video/manifests, video/adjustments, 生成视频调整版本, 创建精确渲染 Job, idempotencyKey.
type Asset = { id: string; kind: string; lifecycle: string; byteSize: number; originalName: string; metadata: { durationMs?: number; width?: number; height?: number; tags?: string[] } };
type LocalFile = { fileName: string; relativePath: string; durationMs: number; width: number; height: number; format: string; available: boolean };
type Clip = { assetId: string; sourceInMs: number; durationMs: number; transition?: 'cut' | 'fade'; sentenceIndex?: number; sentenceText?: string; sceneId?: string; matching?: { matchedKeywords: string[]; matchScore: number; fallback: boolean; matchingReason: string } };
type Manifest = { id: string; revision: number; status: 'PERSISTED' | 'SUPERSEDED'; manifest: { timeline: Clip[]; seed: number; metadata?: { editMode?: 'SCRIPT' | 'RANDOM'; localMediaSourceRootId?: string; localMediaScanId?: string } } };
type Snapshot = { sourceAssets: Asset[]; currentRender: { renderId: string; outputAssetId: string; status: string } | null; renderHistory: Array<{ renderId: string; outputAssetId?: string; status: string }>; job: { id: string; state: string; attemptCount: number; maxAttempts: number } | null; approval: { status: string } | null };
type ScriptInfo = { scriptRevisionId: string; revision: number; title: string; body: string; status: string };
type Scan = { id: string; sourceRootId: string; status: string; progress: { discovered?: number; analyzed?: number; available?: number; unavailable?: number }; files: LocalFile[] };
type ApiError = { error?: { message?: string } };
const activeJobs = new Set(['QUEUED', 'RUNNING', 'RETRY_WAIT', 'CANCEL_REQUESTED']);
async function responseMessage(response: Response, fallback: string): Promise<string> { try { return (await response.json() as ApiError).error?.message || fallback; } catch { return fallback; } }

export default function VideoPage({ params }: { params: { id: string } }) {
  const projectId = params.id;
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const [manifests, setManifests] = useState<Manifest[]>([]); const [manifest, setManifest] = useState<Manifest | null>(null);
  const [mode, setMode] = useState<EditMode | null>(null); const [scriptSource, setScriptSource] = useState<'PROJECT' | 'CUSTOM'>('PROJECT'); const [script, setScript] = useState(''); const [scriptInfo, setScriptInfo] = useState<ScriptInfo | null>(null); const [scriptDirty, setScriptDirty] = useState(false); const [scriptCount, setScriptCount] = useState(0);
  const [sourceRoot, setSourceRoot] = useState(''); const [recursive, setRecursive] = useState(true); const [scan, setScan] = useState<Scan | null>(null); const [selectedAssets, setSelectedAssets] = useState<string[]>([]); const [selectedClip, setSelectedClip] = useState<number | null>(null); const [operations, setOperations] = useState<Array<Record<string, unknown>>>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [seed, setSeed] = useState(1); const [minClipSeconds, setMinClipSeconds] = useState(2); const [maxClipSeconds, setMaxClipSeconds] = useState(5); const [editIdempotencyKey, setEditIdempotencyKey] = useState('');

  const loadScript = useCallback(async () => { const response = await fetch(`/api/v1/projects/${projectId}/video/current-script`); if (!response.ok) { setScriptInfo(null); return false; } const next = await response.json() as ScriptInfo; setScriptInfo(next); if (!scriptDirty) setScript(next.body); return true; }, [projectId, scriptDirty]);
  const refresh = useCallback(async () => { const response = await fetch(`/api/v1/projects/${projectId}/video`); if (!response.ok) { setMessage(await responseMessage(response, '视频工作台读取失败。')); return; } const next = await response.json() as Snapshot; setSnapshot(next); const manifestsResponse = await fetch(`/api/v1/projects/${projectId}/video/manifests`); if (manifestsResponse.ok) { const data = await manifestsResponse.json() as { items: Manifest[] }; setManifests(data.items); setManifest((current) => current || data.items.find((item) => item.status === 'PERSISTED') || data.items[0] || null); } if (selectedAssets.length === 0 && next.sourceAssets.length) setSelectedAssets([next.sourceAssets[0]!.id]); }, [projectId, selectedAssets.length]);
  useEffect(() => { void refresh(); void loadScript(); }, [refresh, loadScript]);
  useEffect(() => { if (!snapshot?.job || !activeJobs.has(snapshot.job.state)) return; const timer = window.setInterval(() => void refresh(), 1000); return () => window.clearInterval(timer); }, [snapshot?.job?.id, snapshot?.job?.state, refresh]);
  useEffect(() => { if (!script.trim()) { setScriptCount(0); return; } const timer = window.setTimeout(() => { void fetch('/api/v1/video/sentence-preview', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ script }) }).then((response) => response.ok ? response.json() as Promise<{ items: unknown[] }> : null).then((data) => setScriptCount(data?.items.length || 0)); }, 180); return () => window.clearTimeout(timer); }, [script]);
  useEffect(() => { const scanId = manifest?.manifest.metadata?.localMediaScanId; if (!scanId) return; void fetch(`/api/v1/video/local-media/scans/${scanId}?projectId=${encodeURIComponent(projectId)}`).then((response) => response.ok ? response.json() as Promise<Scan> : null).then((next) => { if (next) setScan(next); }); }, [manifest?.id, manifest?.manifest.metadata?.localMediaScanId, projectId]);
  const currentClip = manifest && selectedClip !== null ? manifest.manifest.timeline[selectedClip] : undefined;
  const readyAssets = useMemo(() => snapshot?.sourceAssets.filter((asset) => asset.lifecycle === 'READY') || [], [snapshot]); const jobRunning = Boolean(snapshot?.job && activeJobs.has(snapshot.job.state));
  const localAssets = useMemo(() => scan?.files.filter((file) => file.available).map((file) => ({ id: `${scan.sourceRootId}:${file.relativePath}`, originalName: file.fileName, durationMs: file.durationMs })) || [], [scan]);
  const replacementAssets = useMemo(() => [...readyAssets.map((asset) => ({ id: asset.id, originalName: asset.originalName, durationMs: Number(asset.metadata.durationMs || 0) })), ...localAssets], [readyAssets, localAssets]);
  const clipSource = useMemo(() => { if (!currentClip) return undefined; const rootId = manifest?.manifest.metadata?.localMediaSourceRootId; if (rootId && currentClip.assetId.startsWith(`${rootId}:`)) return `/api/v1/video/local-media/content?projectId=${encodeURIComponent(projectId)}&sourceRootId=${encodeURIComponent(rootId)}&fileId=${encodeURIComponent(currentClip.assetId)}`; return `/api/v1/projects/${projectId}/assets/${encodeURIComponent(currentClip.assetId)}/content`; }, [currentClip, manifest, projectId]);

  const chooseMode = (next: 'SCRIPT' | 'RANDOM') => { setMode(next); if (next === 'SCRIPT' && scriptSource === 'PROJECT') void loadScript(); };
  const chooseScriptSource = (next: 'PROJECT' | 'CUSTOM') => { setScriptSource(next); setScriptDirty(false); if (next === 'PROJECT') void loadScript(); else setScript(''); };
  const toggleAsset = (id: string) => setSelectedAssets((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const scanFolder = async () => { if (!sourceRoot.trim()) { setMessage('请先输入素材文件夹路径。'); return; } setBusy(true); const response = await fetch('/api/v1/video/local-media/scan', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ projectId, sourceRoot: sourceRoot.trim(), recursive }) }); setBusy(false); if (!response.ok) { setMessage(await responseMessage(response, '素材文件夹扫描失败。')); return; } const created = await response.json() as { scanId: string; sourceRootId: string; jobId: string; state: string; progress: Scan['progress'] }; setScan({ id: created.scanId, sourceRootId: created.sourceRootId, status: created.state, progress: created.progress || {}, files: [] }); setMessage('已创建扫描任务，正在分析素材……'); const poll = async (): Promise<void> => { const statusResponse = await fetch(`/api/v1/video/local-media/scans/${created.scanId}?projectId=${encodeURIComponent(projectId)}`); if (!statusResponse.ok) return; const next = await statusResponse.json() as Scan; setScan(next); if (['QUEUED', 'RUNNING'].includes(next.status)) window.setTimeout(() => void poll(), 700); else setMessage(next.status === 'SUCCEEDED' ? `扫描完成：可用 ${next.progress.available || next.files.filter((file) => file.available).length} 个视频。` : '素材扫描未完成，请重试。'); }; void poll(); };
  const previewSentences = async () => { const response = await fetch('/api/v1/video/sentence-preview', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ script }) }); setMessage(response.ok ? `已拆分为 ${(await response.json() as { items: unknown[] }).items.length} 个句子，每句对应一个镜头。` : await responseMessage(response, '拆句失败。')); };
  const createPlan = async () => { if (!mode || !script.trim()) { setMessage('请输入脚本文案。'); return; } if (mode === 'SCRIPT' && scriptSource === 'PROJECT' && !scriptInfo) { setMessage('当前项目暂无可用脚本，请先到脚本与分镜完成脚本。'); return; } setBusy(true); const response = await fetch(`/api/v1/projects/${projectId}/video/montage-plans`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ mode, script, seed, minClipDurationMs: minClipSeconds * 1000, maxClipDurationMs: maxClipSeconds * 1000, ...(scan?.status === 'SUCCEEDED' ? { scanId: scan.id } : sourceRoot.trim() ? { sourceRoot: sourceRoot.trim(), recursive } : { videoAssetIds: selectedAssets }) }) }); setBusy(false); if (!response.ok) { setMessage(await responseMessage(response, '剪辑方案生成失败。')); return; } const data = await response.json() as Manifest; setManifest(data); setSelectedClip(0); setMessage(`已生成 ${data.manifest.timeline.length} 个镜头，请逐句检查素材。`); await refresh(); };
  const createVersion = async () => { if (!manifest || operations.length === 0) return; setBusy(true); const idempotencyKey = editIdempotencyKey || `ui-${globalThis.crypto.randomUUID()}`; setEditIdempotencyKey(idempotencyKey); const response = await fetch(`/api/v1/projects/${projectId}/video/adjustments`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ parentManifestId: manifest.id, operations, createdBy: 'operator', idempotencyKey }) }); setBusy(false); if (!response.ok) { setMessage(await responseMessage(response, '视频调整版本创建失败。')); return; } setManifest(await response.json() as Manifest); setOperations([]); setEditIdempotencyKey(''); setMessage('新的剪辑版本已创建。'); await refresh(); };
  const renderManifest = async () => { if (!manifest) return; setBusy(true); const response = await fetch(`/api/v1/projects/${projectId}/video/manifests/${manifest.id}/render`, { method: 'POST' }); setBusy(false); setMessage(response.ok ? '生成任务已排队。' : await responseMessage(response, '生成成片失败。')); await refresh(); };
  const createLegacyRenderJob = async () => { const response = await fetch(`/api/v1/projects/${projectId}/video/jobs`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ videoAssetIds: selectedAssets, seed, plannerType: 'RANDOM' }) }); setMessage(response.ok ? '生成任务已排队。' : await responseMessage(response, '生成任务创建失败。')); await refresh(); };
  const cancelJob = async () => { if (!snapshot?.job) return; const response = await fetch(`/api/v1/projects/${projectId}/video/jobs/${snapshot.job.id}/cancel`, { method: 'POST' }); setMessage(response.ok ? '已请求取消生成任务。' : '取消失败。'); await refresh(); };
  const sendToApproval = async () => { if (!snapshot?.currentRender) return; const target = snapshot.currentRender; const response = await fetch(`/api/v1/projects/${projectId}/approvals`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ targetType: 'RENDER', targetId: target.renderId, targetRevisionId: target.outputAssetId, status: 'PENDING', approver: 'operator', evidence: { source: 'video-workspace' } }) }); setMessage(response.ok ? '成片已送往审批。' : await responseMessage(response, '提交审批失败。')); await refresh(); };

  return <main className="shell"><header><p className="eyebrow">项目 / {projectId}</p><h1>视频剪辑</h1><p className="muted">按脚本剪辑或随机混剪；脚本文案、镜头和时间线始终一一对应。</p><nav className="module-nav"><Link href={`/projects/${projectId}/assets`}>素材库</Link><Link href={`/projects/${projectId}/director`}>脚本与分镜</Link><Link href={`/projects/${projectId}/approvals`}>审批</Link></nav></header>
    <EditModeSelector mode={mode} onSelect={chooseMode} />
    {mode && <section className="card montage-entry"><div className="section-title"><h2>{mode === 'SCRIPT' ? '按脚本剪辑' : '随机混剪'}</h2><span>一句话一个镜头 ✓</span></div>{mode === 'SCRIPT' && <ScriptSourceSelector projectId={projectId} source={scriptSource} revision={scriptInfo?.revision} sentenceCount={scriptCount} available={Boolean(scriptInfo)} onSelect={chooseScriptSource} />}<label>脚本文案<textarea value={script} onChange={(event) => { setScript(event.target.value); setScriptDirty(true); }} placeholder={scriptSource === 'PROJECT' ? '当前项目脚本会自动载入。' : '粘贴脚本文案，支持中文、英文和换行。'} /></label>{mode === 'RANDOM' && <div className="random-settings"><label>最短镜头（秒）<input type="number" min={1} value={minClipSeconds} onChange={(event) => setMinClipSeconds(Number(event.target.value))} /></label><label>最长镜头（秒）<input type="number" min={1} value={maxClipSeconds} onChange={(event) => setMaxClipSeconds(Number(event.target.value))} /></label><label className="inline-check"><input type="checkbox" checked readOnly />避免连续使用同一素材</label><label className="inline-check"><input type="checkbox" checked readOnly />尽量减少重复素材</label></div>}<div className="entry-actions"><button type="button" onClick={() => void previewSentences()} disabled={busy || !script.trim()}>预览拆句</button><label>素材文件夹<input value={sourceRoot} onChange={(event) => { setSourceRoot(event.target.value); setScan(null); }} placeholder="输入已授权的本地文件夹路径" /><button type="button" onClick={() => void scanFolder()} disabled={busy}>扫描文件夹</button></label><label className="inline-check"><input type="checkbox" checked={recursive} onChange={(event) => setRecursive(event.target.checked)} />包含子文件夹 ✓</label><button type="button" onClick={() => void createPlan()} disabled={busy || !script.trim() || (!scan && !sourceRoot.trim() && selectedAssets.length === 0)}>生成剪辑方案</button></div>{scan && <LocalMediaScanStatus status={scan.status} discovered={scan.progress.discovered || scan.files.length} analyzed={scan.progress.analyzed || scan.files.length} available={scan.progress.available || scan.files.filter((file) => file.available).length} />}</section>}
    <section className="grid"><section className="card"><div className="section-title"><h2>素材池</h2><span>{scan?.status === 'SUCCEEDED' ? `${localAssets.length} 个本地素材` : `${readyAssets.length} 个项目素材`}</span></div>{scan?.status === 'SUCCEEDED' ? <div className="asset-list">{localAssets.map((asset) => <label className="checkbox-row" key={asset.id}><input type="checkbox" checked={selectedAssets.includes(asset.id)} onChange={() => toggleAsset(asset.id)} />{asset.originalName}<small>{asset.durationMs}ms</small></label>)}</div> : readyAssets.length ? readyAssets.map((asset) => <label className="checkbox-row" key={asset.id}><input type="checkbox" checked={selectedAssets.includes(asset.id)} onChange={() => toggleAsset(asset.id)} />{asset.originalName}</label>) : <p className="muted">请先在素材库上传视频，或扫描授权素材文件夹。</p>}<details><summary>高级设置</summary><label>随机种子<input type="number" value={seed} onChange={(event) => setSeed(Number(event.target.value))} disabled={jobRunning || busy} /></label><p className="muted">输出：1080×1920 · 9:16 · 30fps</p><button type="button" onClick={() => void createLegacyRenderJob()} disabled={busy || jobRunning || selectedAssets.length === 0}>生成任务</button></details></section><section className="card"><div className="section-title"><h2>成片预览</h2><span>{snapshot?.job ? <StatusBadge status={snapshot.job.state} /> : '未生成'}</span></div>{snapshot?.job && <p className="status">生成任务 · {snapshot.job.attemptCount}/{snapshot.job.maxAttempts} 次尝试</p>}{snapshot?.currentRender && <><video controls preload="metadata" src={`/api/v1/projects/${projectId}/assets/${snapshot.currentRender.outputAssetId}/content`} /><button type="button" onClick={() => void sendToApproval()} disabled={Boolean(snapshot.approval)}>送往审批</button></>}{!snapshot?.currentRender && <p className="muted">生成成片后会在这里预览。</p>}{jobRunning && <button type="button" onClick={() => void cancelJob()}>取消生成任务</button>}</section></section>
    <section className="card editor-card"><div className="section-title"><h2>脚本 / 镜头 / 时间线</h2><span>{manifests.length} 个剪辑版本</span></div>{manifest ? <><div className="editor-columns"><div className="sentence-list">{manifest.manifest.timeline.map((clip, index) => <button type="button" key={`${clip.sceneId || clip.assetId}-${index}`} className={selectedClip === index ? 'selected' : ''} onClick={() => setSelectedClip(index)}>镜头 {String(index + 1).padStart(2, '0')}<span>{clip.sentenceText || '未记录文案'}</span><small>{clip.matching?.fallback ? '规则兜底' : '已匹配'} · {clip.durationMs}ms</small></button>)}</div><div><h3>当前镜头预览</h3>{currentClip ? <><ClipPreview src={clipSource} sourceInMs={currentClip.sourceInMs} durationMs={currentClip.durationMs} label={currentClip.assetId} /><p className="muted">起点 {currentClip.sourceInMs}ms · 时长 {currentClip.durationMs}ms · 结束 {currentClip.sourceInMs + currentClip.durationMs}ms</p></> : <p className="feedback">选择镜头后预览源素材</p>}</div><div><h3>镜头设置</h3><ClipInspector clip={currentClip} index={selectedClip} clipCount={manifest.manifest.timeline.length} replacementAssets={replacementAssets} mode={manifest.manifest.metadata?.editMode || mode || 'RANDOM'} editable={manifest.status !== 'SUPERSEDED'} busy={busy} onOperation={(operation) => setOperations((current) => [...current, operation])} />{currentClip?.matching && <p className="matching-info">匹配信息：{currentClip.matching.matchingReason}（{currentClip.matching.matchScore}分）</p>}</div></div><ManifestTimeline clips={manifest.manifest.timeline} selectedIndex={selectedClip} onSelect={setSelectedClip} />{operations.length > 0 && <p className="status">待提交调整：{operations.length} 项</p>}<button type="button" onClick={() => void createVersion()} disabled={busy || operations.length === 0 || manifest.status === 'SUPERSEDED'}>生成剪辑版本</button><button type="button" onClick={() => void renderManifest()} disabled={busy || operations.length > 0}>生成成片</button><div className="version-list">{manifests.map((item) => <button type="button" key={item.id} onClick={() => setManifest(item)}><span data-testid="Manifest v">剪辑版本 v{item.revision}</span> · <StatusBadge status={item.status} /></button>)}</div></> : <p className="muted">选择上方剪辑方式并生成方案。</p>}{message && <p className="status">{message}</p>}</section>
    <section className="card"><div className="section-title"><h2>历史成片</h2><span>{snapshot?.renderHistory.length || 0} 条</span></div><ul className="revision-list">{snapshot?.renderHistory.map((item, index) => <li key={item.renderId}><strong>成片 {index + 1}</strong><StatusBadge status={item.status} /></li>)}</ul></section>
  </main>;
}
