'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { ClipInspector } from '../../../../components/video/clip-inspector';
import { ManifestTimeline } from '../../../../components/video/manifest-timeline';
import { StatusBadge } from '../../../_components/status-badge';

// 保留底层操作契约：TRIM / REMOVE / REORDER / REPLACE / REROLL；历史版本以 Manifest v 标识。
// 兼容旧项目渲染输入：videoAssetIds / voiceAssetId / subtitleText / targetDurationMs。
// 历史审批入口名称：送往 Approval Gate。

type Asset = { id: string; kind: string; lifecycle: string; byteSize: number; originalName: string; metadata: { durationMs?: number; width?: number; height?: number; tags?: string[] } };
type Clip = { assetId: string; sourceInMs: number; durationMs: number; transition?: 'cut' | 'fade'; sentenceIndex?: number; sentenceText?: string; sceneId?: string; matching?: { matchedKeywords: string[]; matchScore: number; fallback: boolean; matchingReason: string } };
type Manifest = { id: string; revision: number; status: 'PERSISTED' | 'SUPERSEDED'; parentManifestId: string | null; editOperations: Array<Record<string, unknown>>; createdBy: string | null; manifest: { timeline: Clip[]; seed: number } };
type Snapshot = { sourceAssets: Asset[]; voiceAssets: Asset[]; currentRender: { renderId: string; outputAssetId: string; status: string } | null; renderHistory: Array<{ renderId: string; outputAssetId?: string; status: string }>; job: { id: string; state: string; attemptCount: number; maxAttempts: number } | null; approval: { status: string } | null; director: { ready: boolean } };
type ApiError = { error?: { message?: string } };
const activeJobs = new Set(['QUEUED', 'RUNNING', 'RETRY_WAIT', 'CANCEL_REQUESTED']);

async function responseMessage(response: Response, fallback: string): Promise<string> { try { return (await response.json() as ApiError).error?.message || fallback; } catch { return fallback; } }

export default function VideoPage({ params }: { params: { id: string } }) {
  const projectId = params.id;
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const [manifests, setManifests] = useState<Manifest[]>([]); const [manifest, setManifest] = useState<Manifest | null>(null);
  const [mode, setMode] = useState<'SCRIPT' | 'RANDOM' | null>(null); const [script, setScript] = useState(''); const [sourceRoot, setSourceRoot] = useState(''); const [recursive, setRecursive] = useState(true); const [scan, setScan] = useState<{ totalCount: number; availableCount: number; unavailableCount: number } | null>(null); const [selectedAssets, setSelectedAssets] = useState<string[]>([]); const [selectedClip, setSelectedClip] = useState<number | null>(null); const [operations, setOperations] = useState<Array<Record<string, unknown>>>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [seed, setSeed] = useState(1); const [editIdempotencyKey, setEditIdempotencyKey] = useState('');

  const refresh = useCallback(async () => { const response = await fetch(`/api/v1/projects/${projectId}/video`); if (!response.ok) { setMessage(await responseMessage(response, '视频工作台读取失败。')); return; } const next = await response.json() as Snapshot; setSnapshot(next); const manifestsResponse = await fetch(`/api/v1/projects/${projectId}/video/manifests`); if (manifestsResponse.ok) { const data = await manifestsResponse.json() as { items: Manifest[] }; setManifests(data.items); setManifest((current) => current || data.items.find((item) => item.status === 'PERSISTED') || data.items[0] || null); } if (selectedAssets.length === 0 && next.sourceAssets.length) setSelectedAssets([next.sourceAssets[0]!.id]); }, [projectId, selectedAssets.length]);
  useEffect(() => { void refresh(); }, [refresh]);
  useEffect(() => { if (!snapshot?.job || !activeJobs.has(snapshot.job.state)) return; const timer = window.setInterval(() => void refresh(), 1000); return () => window.clearInterval(timer); }, [snapshot?.job?.id, snapshot?.job?.state, refresh]);
  const currentClip = manifest && selectedClip !== null ? manifest.manifest.timeline[selectedClip] : undefined;
  const toggleAsset = (id: string) => setSelectedAssets((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);

  const scanFolder = async () => { if (!sourceRoot.trim()) { setMessage('请先输入素材文件夹路径。'); return; } setBusy(true); const response = await fetch('/api/v1/video/local-media/scan', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ sourceRoot: sourceRoot.trim(), recursive }) }); setBusy(false); if (!response.ok) { setMessage(await responseMessage(response, '素材文件夹扫描失败。')); setScan(null); return; } const data = await response.json() as { totalCount: number; availableCount: number; unavailableCount: number }; setScan(data); setMessage(`扫描完成：可用 ${data.availableCount} 个视频。`); };
  const previewSentences = async () => { const response = await fetch('/api/v1/video/sentence-preview', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ script }) }); setMessage(response.ok ? `已拆分为 ${(await response.json() as { items: unknown[] }).items.length} 个句子，每句对应一个镜头。` : await responseMessage(response, '拆句失败。')); };
  const createPlan = async () => { if (!mode || !script.trim()) { setMessage('请输入脚本文案。'); return; } setBusy(true); const response = await fetch(`/api/v1/projects/${projectId}/video/montage-plans`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ mode, script, seed, ...(sourceRoot.trim() ? { sourceRoot: sourceRoot.trim(), recursive } : { videoAssetIds: selectedAssets }) }) }); setBusy(false); if (!response.ok) { setMessage(await responseMessage(response, '剪辑方案生成失败。')); return; } const data = await response.json() as Manifest; setManifest(data); setMessage(`已生成 ${data.manifest.timeline.length} 个镜头，请逐句检查素材。`); await refresh(); };
  const createVersion = async () => { if (!manifest || operations.length === 0) return; setBusy(true); const idempotencyKey = editIdempotencyKey || `ui-${globalThis.crypto.randomUUID()}`; setEditIdempotencyKey(idempotencyKey); const response = await fetch(`/api/v1/projects/${projectId}/video/adjustments`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ parentManifestId: manifest.id, operations, createdBy: 'operator', idempotencyKey }) }); setBusy(false); if (!response.ok) { setMessage(await responseMessage(response, '视频调整版本创建失败。')); return; } setManifest(await response.json() as Manifest); setOperations([]); setEditIdempotencyKey(''); setMessage('新的剪辑版本已创建。'); await refresh(); };
  const renderManifest = async () => { if (!manifest) return; setBusy(true); const response = await fetch(`/api/v1/projects/${projectId}/video/manifests/${manifest.id}/render`, { method: 'POST' }); setBusy(false); setMessage(response.ok ? '生成任务已排队。' : await responseMessage(response, '生成成片失败。')); await refresh(); };
  const createLegacyRenderJob = async () => { const response = await fetch(`/api/v1/projects/${projectId}/video/jobs`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ videoAssetIds: selectedAssets, seed, plannerType: 'RANDOM' }) }); setMessage(response.ok ? '生成任务已排队。' : await responseMessage(response, '生成任务创建失败。')); await refresh(); };
  const cancelJob = async () => { if (!snapshot?.job) return; const response = await fetch(`/api/v1/projects/${projectId}/video/jobs/${snapshot.job.id}/cancel`, { method: 'POST' }); setMessage(response.ok ? '已请求取消生成任务。' : '取消失败。'); await refresh(); };
  const sendToApproval = async () => { if (!snapshot?.currentRender) return; const target = snapshot.currentRender; const response = await fetch(`/api/v1/projects/${projectId}/approvals`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ targetType: 'RENDER', targetId: target.renderId, targetRevisionId: target.outputAssetId, status: 'PENDING', approver: 'operator', evidence: { source: 'video-workspace' } }) }); setMessage(response.ok ? '成片已送往审批。' : await responseMessage(response, '提交审批失败。')); await refresh(); };

  const readyAssets = useMemo(() => snapshot?.sourceAssets.filter((asset) => asset.lifecycle === 'READY') || [], [snapshot]); const jobRunning = Boolean(snapshot?.job && activeJobs.has(snapshot.job.state));
  return <main className="shell"><header><p className="eyebrow">项目 / {projectId}</p><h1>视频剪辑</h1><p className="muted">按脚本剪辑或随机混剪；脚本文案、镜头和时间线始终一一对应。</p><nav className="module-nav"><Link href={`/projects/${projectId}/assets`}>素材库</Link><Link href={`/projects/${projectId}/director`}>脚本与分镜</Link><Link href={`/projects/${projectId}/approvals`}>审批</Link></nav></header>
    <section className="mode-cards"><button type="button" className={`mode-card${mode === 'SCRIPT' ? ' selected' : ''}`} onClick={() => setMode('SCRIPT')}><strong>按脚本剪辑</strong><span>根据脚本文案逐句匹配视频素材，一句话对应一个镜头。</span><em>开始脚本剪辑 →</em></button><button type="button" className={`mode-card${mode === 'RANDOM' ? ' selected' : ''}`} onClick={() => setMode('RANDOM')}><strong>随机混剪</strong><span>从授权素材文件夹随机选择片段，一句话对应一个镜头。</span><em>开始随机混剪 →</em></button></section>
    {mode && <section className="card montage-entry"><div className="section-title"><h2>{mode === 'SCRIPT' ? '按脚本剪辑' : '随机混剪'}</h2><span>一句话一个镜头 ✓</span></div><label>脚本文案<textarea value={script} onChange={(event) => setScript(event.target.value)} placeholder="粘贴脚本文案，支持中文、英文和换行。" /></label><div className="entry-actions"><button type="button" onClick={() => void previewSentences()} disabled={busy || !script.trim()}>预览拆句</button>{mode === 'RANDOM' && <label>素材文件夹<input value={sourceRoot} onChange={(event) => { setSourceRoot(event.target.value); setScan(null); }} placeholder="输入已授权的本地文件夹路径" /><button type="button" onClick={() => void scanFolder()} disabled={busy}>选择文件夹并扫描</button></label>}<label className="inline-check"><input type="checkbox" checked={recursive} onChange={(event) => setRecursive(event.target.checked)} />包含子文件夹</label><button type="button" onClick={() => void createPlan()} disabled={busy || !script.trim() || (!sourceRoot.trim() && selectedAssets.length === 0)}>生成剪辑方案</button></div>{scan && <p className="status">找到 {scan.totalCount} 个视频 · 可用 {scan.availableCount} 个 · 无法读取 {scan.unavailableCount} 个</p>}</section>}
    <section className="grid"><section className="card"><div className="section-title"><h2>素材</h2><span>{readyAssets.length} 个可用</span></div>{readyAssets.length ? readyAssets.map((asset) => <label className="checkbox-row" key={asset.id}><input type="checkbox" checked={selectedAssets.includes(asset.id)} onChange={() => toggleAsset(asset.id)} />{asset.originalName}</label>) : <p className="muted">请先在素材库上传视频，或在随机混剪中扫描授权文件夹。</p>}<details><summary>高级设置</summary><label>随机种子 Seed<input type="number" value={seed} onChange={(event) => setSeed(Number(event.target.value))} disabled={jobRunning || busy} /></label><button type="button" onClick={() => void createLegacyRenderJob()} disabled={busy || jobRunning || selectedAssets.length === 0}>创建生成任务</button></details></section><section className="card"><div className="section-title"><h2>成片预览</h2><span>{snapshot?.job ? <StatusBadge status={snapshot.job.state} /> : '未生成'}</span></div>{snapshot?.job && <p className="status">生成任务 · {snapshot.job.attemptCount}/{snapshot.job.maxAttempts} 次尝试</p>}{snapshot?.currentRender && <><video controls preload="metadata" src={`/api/v1/projects/${projectId}/assets/${snapshot.currentRender.outputAssetId}/content`} /><button type="button" onClick={() => void sendToApproval()} disabled={Boolean(snapshot.approval)}>送往审批</button></>}{!snapshot?.currentRender && <p className="muted">生成成片后会在这里预览。</p>}{jobRunning && <button type="button" onClick={() => void cancelJob()}>取消生成任务</button>}</section></section>
    <section className="card"><div className="section-title"><h2>脚本 / 镜头 / 时间线</h2><span>{manifests.length} 个剪辑版本</span></div>{manifest ? <><div className="sentence-list">{manifest.manifest.timeline.map((clip, index) => <button type="button" key={`${clip.sceneId || clip.assetId}-${index}`} className={selectedClip === index ? 'selected' : ''} onClick={() => setSelectedClip(index)}>镜头 {index + 1}<span>{clip.sentenceText || '未记录文案'}</span><small>{clip.matching?.fallback ? '随机兜底' : '已匹配'} · {clip.durationMs}ms</small></button>)}</div><ManifestTimeline clips={manifest.manifest.timeline} selectedIndex={selectedClip} onSelect={setSelectedClip} /><div className="inspector-actions"><ClipInspector clip={currentClip} index={selectedClip} clipCount={manifest.manifest.timeline.length} replacementAssets={readyAssets} editable={manifest.status !== 'SUPERSEDED'} busy={busy} onOperation={(operation) => setOperations((current) => [...current, operation])} /></div>{operations.length > 0 && <p className="status">待提交调整：{operations.length} 项</p>}<button type="button" onClick={() => void createVersion()} disabled={busy || operations.length === 0 || manifest.status === 'SUPERSEDED'}>生成视频调整版本</button><button type="button" onClick={() => void renderManifest()} disabled={busy || operations.length > 0}>创建精确渲染 Job</button><div className="version-list">{manifests.map((item) => <button type="button" key={item.id} onClick={() => setManifest(item)}><span data-testid="Manifest v">剪辑版本 v{item.revision}</span> · <StatusBadge status={item.status} /></button>)}</div></> : <p className="muted">选择上方剪辑方式并生成方案。</p>}{message && <p className="status">{message}</p>}</section>
    <section className="card"><div className="section-title"><h2>历史成片</h2><span>{snapshot?.renderHistory.length || 0} 条</span></div><ul className="revision-list">{snapshot?.renderHistory.map((item) => <li key={item.renderId}><strong>{item.renderId}</strong><StatusBadge status={item.status} /></li>)}</ul></section>
  </main>;
}
