'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';

type Project = { id: string; name: string; status: string; metadata?: { topic?: string; targetPlatform?: string; targetAccount?: string; plannedDate?: string } };
const projectStatusLabel: Record<string, string> = { DRAFT: '草稿', IN_PRODUCTION: '制作中', READY_TO_PUBLISH: '待发布', PUBLISHED: '已发布', ARCHIVED: '已归档' };
export default function ContentPlanPage() {
  const [items, setItems] = useState<Project[]>([]); const [filters, setFilters] = useState({ plannedDateFrom: '', plannedDateTo: '', account: '', platform: '', status: '' }); const [message, setMessage] = useState('');
  const refresh = useCallback(async () => { const params = new URLSearchParams(Object.entries(filters).filter(([, value]) => value)); const response = await fetch(`/api/v1/projects?${params}`); if (!response.ok) { setMessage('内容计划读取失败。'); return; } setItems((await response.json() as { items: Project[] }).items); }, [filters]);
  useEffect(() => { void refresh(); }, [refresh]);
  return <main className="shell"><header><p className="eyebrow">ContentOS / 内容计划</p><h1>内容计划</h1><p className="muted">以列表、日期和状态管理近期计划，不引入复杂日历。</p><nav className="module-nav"><Link href="/">项目中心</Link></nav></header><section className="card"><div className="grid"><label>开始日期<input type="date" value={filters.plannedDateFrom} onChange={(event) => setFilters({ ...filters, plannedDateFrom: event.target.value })} /></label><label>结束日期<input type="date" value={filters.plannedDateTo} onChange={(event) => setFilters({ ...filters, plannedDateTo: event.target.value })} /></label><label>账号<input value={filters.account} onChange={(event) => setFilters({ ...filters, account: event.target.value })} placeholder="目标账号" /></label><label>平台<select value={filters.platform} onChange={(event) => setFilters({ ...filters, platform: event.target.value })}><option value="">全部平台</option><option value="douyin">抖音</option><option value="wechat_channels">视频号</option></select></label><label>状态<select value={filters.status} onChange={(event) => setFilters({ ...filters, status: event.target.value })}><option value="">全部状态</option>{Object.entries(projectStatusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div><button type="button" onClick={() => void refresh()}>应用筛选</button></section>{message && <p className="feedback">{message}</p>}<section className="card"><div className="section-title"><h2>计划项目</h2><span>{items.length} 个</span></div>{items.length === 0 ? <p className="muted">没有匹配的计划项目。</p> : <ul className="project-list">{items.map((project) => <li key={project.id}><Link href={`/projects/${project.id}`}><span><strong>{project.metadata?.plannedDate || '未排期'} · {project.name}</strong><small>{project.metadata?.topic || '未填写选题'} · {project.metadata?.targetPlatform || '未指定平台'} · {project.metadata?.targetAccount || '未指定账号'}</small></span><small>{projectStatusLabel[project.status] || project.status}</small></Link></li>)}</ul>}</section></main>;
}
