'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { AssetCard, type VideoAsset } from '../../../components/video/asset-card';
import { MediaPreview } from '../../../components/video/media-preview';
import { ManifestTimeline, type TimelineClip } from '../../../components/video/manifest-timeline';
import { ClipInspector } from '../../../components/video/clip-inspector';
import { StatusBadge } from '../../_components/status-badge';
import { LoadingState } from '../../_components/feedback-state';

type Session = { id: string; workspaceId: string; voiceAssetId: string | null; currentManifestId: string | null };
type Manifest = { id: string; revision: number; status?: string; manifest: { timeline: TimelineClip[] } };
type ImportRecord = { id: string; state: string; originalName: string; kind: string; outputAssetId?: string | null; errorMessage?: string | null };
type ApiError = { error?: { message?: string } };
async function responseMessage(response: Response, fallback: string) { try { return (await response.json() as ApiError).error?.message || fallback; } catch { return fallback; } }

export default function StandaloneQuickEditPage() {
  const [session, setSession] = useState<Session | null>(null); const [assets, setAssets] = useState<VideoAsset[]>([]); const [imports, setImports] = useState<ImportRecord[]>([]); const [manifest, setManifest] = useState<Manifest | null>(null); const [selectedAssetId, setSelectedAssetId] = useState<string>(); const [selectedClip, setSelectedClip] = useState<number | null>(null);
  const [seed, setSeed] = useState(1); const [targetDurationMs, setTargetDurationMs] = useState(30000); const [minClipDurationMs, setMinClipDurationMs] = useState(2000); const [maxClipDurationMs, setMaxClipDurationMs] = useState(8000); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [renderState, setRenderState] = useState('');
  const createSession = async () => { setBusy(true); const response = await fetch('/api/v1/video/quick-edits', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ seed, targetDurationMs, minClipDurationMs, maxClipDurationMs }) }); setBusy(false); if (!response.ok) { setMessage(await responseMessage(response, '创建快速剪辑失败。')); return; } setSession(await response.json() as Session); setMessage('已创建草稿会话，请从左侧选择素材。'); };
  const refreshAssets = useCallback(async () => { if (!session) return; const response = await fetch(`/api/v1/video/quick-edits/${session.id}/assets`); if (!response.ok) return; const data = await response.json() as { items: VideoAsset[]; imports: ImportRecord[] }; setAssets(data.items.map((asset) => ({ ...asset, contentUrl: `/api/v1/video/quick-edits/${session.id}/assets/${asset.id}/content` }))); setImports(data.imports); }, [session]);
  useEffect(() => { void refreshAssets(); }, [refreshAssets]);
  useEffect(() => { if (!session || !imports.some((item) => ['STAGED', 'QUEUED', 'PROCESSING'].includes(item.state))) return; const timer = window.setInterval(() => void refreshAssets(), 1200); return () => window.clearInterval(timer); }, [session, imports, refreshAssets]);
  const upload = async (event: React.ChangeEvent<HTMLInputElement>) => { if (!session || !event.target.files?.length) return; setBusy(true); const results: string[] = []; for (const file of Array.from(event.target.files)) { const form = new FormData(); form.append('file', file); const response = await fetch(`/api/v1/video/quick-edits/${session.id}/assets`, { method: 'POST', body: form }); results.push(response.ok ? `${file.name} 已排队` : `${file.name}：${await responseMessage(response, '上传失败')}`); } setBusy(false); setMessage(results.join('；')); event.target.value = ''; await refreshAssets(); };
  const plan = async () => { if (!session) return; setBusy(true); const response = await fetch(`/api/v1/video/quick-edits/${session.id}/plan`, { method: 'POST' }); setBusy(false); if (!response.ok) { setMessage(await responseMessage(response, '生成计划失败。')); return; } setManifest(await response.json() as Manifest); setSelectedClip(0); setMessage('Manifest 计划已生成。'); };
  const performAdjustment = async (operation: Record<string, unknown>) => { if (!session || !manifest) return; setBusy(true); const response = await fetch(`/api/v1/video/quick-edits/${session.id}/adjustments`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ operations: [operation], createdBy: 'operator' }) }); setBusy(false); if (!response.ok) { setMessage(await responseMessage(response, '调整失败。')); return; } setManifest(await response.json() as Manifest); setMessage('已创建新的 Manifest Revision。'); };
  const render = async () => { if (!session || !manifest) return; setBusy(true); const response = await fetch(`/api/v1/video/quick-edits/${session.id}/manifests/${manifest.id}/render`, { method: 'POST' }); setBusy(false); if (!response.ok) { setMessage(await responseMessage(response, '渲染入队失败。')); return; } const job = await response.json() as { state?: string }; setRenderState(job.state || 'QUEUED'); setMessage('Render Job 已入队，Video Worker 正在处理。'); };
  const selectedAsset = useMemo(() => assets.find((asset) => asset.id === selectedAssetId), [assets, selectedAssetId]); const selectedClipData = manifest && selectedClip !== null ? manifest.manifest.timeline[selectedClip] : undefined;
  if (!session) return <main className="shell"><div className="page-header"><p className="eyebrow">Video / Standalone</p><h1>快速剪辑</h1><p className="muted">创建草稿会话后，从素材库选择视频和配音，生成可调整的 Random Montage。</p></div><section className="card quick-start"><h2>新建快速剪辑</h2><div className="form-grid"><label>Seed<input type="number" value={seed} onChange={(event) => setSeed(Number(event.target.value))} /></label><label>目标时长（ms）<input type="number" value={targetDurationMs} onChange={(event) => setTargetDurationMs(Number(event.target.value))} /></label><label>最短镜头（ms）<input type="number" value={minClipDurationMs} onChange={(event) => setMinClipDurationMs(Number(event.target.value))} /></label><label>最长镜头（ms）<input type="number" value={maxClipDurationMs} onChange={(event) => setMaxClipDurationMs(Number(event.target.value))} /></label></div><button type="button" onClick={() => void createSession()} disabled={busy}>创建草稿会话</button></section></main>;
  return <main className="shell"><div className="page-header"><p className="eyebrow">Video / Standalone · Draft</p><div className="page-header-row"><div><h1>快速剪辑工作台</h1><p className="muted">三栏编辑工作台：素材库 → 预览与时间线 → 镜头 Inspector。</p></div><div className="page-actions"><StatusBadge status={manifest ? 'READY' : 'PENDING'} /></div></div></div><section className="workspace-grid"><section className="card"><div className="section-title"><h2>素材库</h2><span>{assets.length} 个素材</span></div><label className="upload-box">上传视频 / 配音<input type="file" accept="video/*,audio/*" multiple onChange={(event) => void upload(event)} disabled={busy} /></label>{imports.length > 0 && <div className="asset-list">{imports.map((item) => <div className="asset-card" key={item.id}><strong>{item.originalName}</strong><span className="asset-meta">{item.kind} · <StatusBadge status={item.state} /></span></div>)}</div>}{assets.length === 0 ? <LoadingState text="上传素材后会自动导入并显示在这里。" /> : <div className="asset-list">{assets.map((asset) => <AssetCard key={asset.id} asset={asset} selected={selectedAssetId === asset.id} onSelect={() => setSelectedAssetId(asset.id)} />)}</div>}</section><section className="card"><div className="section-title"><h2>预览 / 时间线</h2><span>{manifest ? `Manifest v${manifest.revision}` : '等待计划'}</span></div><MediaPreview url={selectedAsset?.contentUrl} kind={selectedAsset?.kind || 'VIDEO'} label={selectedAsset?.originalName} /><ManifestTimeline clips={manifest?.manifest.timeline || []} selectedIndex={selectedClip} onSelect={setSelectedClip} /><div className="toolbar"><button type="button" onClick={() => void plan()} disabled={busy || assets.filter((asset) => asset.kind === 'VIDEO' && asset.lifecycle === 'READY').length === 0 || Boolean(manifest)}>Generate Plan</button><button type="button" onClick={() => void render()} disabled={busy || !manifest}>Render 成品</button></div>{renderState && <p className="status">Render 状态：{renderState}</p>}</section><section className="card"><div className="section-title"><h2>镜头 Inspector</h2><span>{selectedClipData ? `镜头 ${(selectedClip || 0) + 1}` : '未选择'}</span></div><ClipInspector clip={selectedClipData} index={selectedClip} onOperation={(operation) => void performAdjustment(operation)} />{message && <p className="status">{message}</p>}<details><summary>会话详情</summary><p className="muted">Session {session.id}<br />Workspace {session.workspaceId}</p></details></section></section></main>;
}
