'use client';

import Link from 'next/link';
import { useState } from 'react';

type Session = { id: string; workspaceId: string; sourceAssetIds: string[]; voiceAssetId: string | null; seed: number; targetDurationMs: number | null; currentManifestId: string | null };
type Manifest = { id: string; revision: number; manifest: { timeline: Array<{ assetId: string; sourceInMs: number; durationMs: number }>; workspaceId?: string } };

async function message(response: Response, fallback: string): Promise<string> { try { const body = await response.json() as { error?: { message?: string } }; return body.error?.message || fallback; } catch { return fallback; } }

export default function StandaloneQuickEditPage() {
  const [assetIds, setAssetIds] = useState(''); const [voiceAssetId, setVoiceAssetId] = useState(''); const [seed, setSeed] = useState(1); const [session, setSession] = useState<Session | null>(null); const [manifest, setManifest] = useState<Manifest | null>(null); const [messageText, setMessageText] = useState(''); const [busy, setBusy] = useState(false);
  const create = async () => { setBusy(true); const response = await fetch('/api/v1/video/quick-edits', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ sourceAssetIds: assetIds.split(/[ ,\n]/).map((value) => value.trim()).filter(Boolean), ...(voiceAssetId ? { voiceAssetId } : {}), seed }) }); setBusy(false); if (!response.ok) { setMessageText(await message(response, '创建快速剪辑失败。')); return; } setSession(await response.json() as Session); setMessageText('Standalone 工作区已创建，不会创建 Content Project。'); };
  const upload = async (event: React.ChangeEvent<HTMLInputElement>) => { if (!session || !event.target.files?.length) return; setBusy(true); const results: string[] = []; for (const file of Array.from(event.target.files)) { const form = new FormData(); form.append('file', file); const response = await fetch(`/api/v1/video/quick-edits/${session.id}/assets`, { method: 'POST', body: form }); results.push(response.ok ? `${file.name} 已排队` : `${file.name}：${await message(response, '上传失败')}`); } setBusy(false); setMessageText(results.join('；')); event.target.value = ''; };
  const plan = async () => { if (!session) return; setBusy(true); const response = await fetch(`/api/v1/video/quick-edits/${session.id}/plan`, { method: 'POST' }); setBusy(false); if (!response.ok) { setMessageText(await message(response, '生成计划失败。')); return; } setManifest(await response.json() as Manifest); setMessageText('Manifest V1 已生成。'); };
  const render = async () => { if (!session || !manifest) return; setBusy(true); const response = await fetch(`/api/v1/video/quick-edits/${session.id}/manifests/${manifest.id}/render`, { method: 'POST' }); setBusy(false); setMessageText(response.ok ? 'Render Job 已入队，将由 Video Worker 执行。' : await message(response, '渲染入队失败。')); };
  return <main className="shell"><header><p className="eyebrow">Video / Standalone</p><h1>快速剪辑 / Standalone Quick Edit</h1><p className="muted">无需 Content Project：视频素材 + Voice → Random Montage → Manifest → 调整 → Render。</p><nav className="module-nav"><Link href="/">返回总控台</Link><Link href="/projects">项目视频</Link></nav></header><section className="grid"><section className="card"><div className="section-title"><h2>素材输入</h2><span>{session ? '已创建' : '待创建'}</span></div><label>READY 视频 Asset ID（逗号或换行分隔，可先留空）<textarea value={assetIds} onChange={(event) => setAssetIds(event.target.value)} placeholder="asset-..." disabled={busy || Boolean(session)} /></label><label>READY Voice Asset ID（可选）<input value={voiceAssetId} onChange={(event) => setVoiceAssetId(event.target.value)} disabled={busy || Boolean(session)} /></label><label>Seed<input type="number" value={seed} onChange={(event) => setSeed(Number(event.target.value))} disabled={busy || Boolean(session)} /></label><button type="button" onClick={() => void create()} disabled={busy || Boolean(session)}>创建 Standalone 工作区</button>{session && <><p className="status">Workspace {session.workspaceId}</p><label>批量上传 Video / Voice<input type="file" accept="video/*,audio/*" multiple onChange={(event) => void upload(event)} disabled={busy || Boolean(manifest)} /></label><p className="muted">上传会进入 Asset Import / Asset Worker，处理完成为 READY 后再生成计划。</p><button type="button" onClick={() => void plan()} disabled={busy || Boolean(manifest)}>Generate Plan</button></>}</section><section className="card"><div className="section-title"><h2>Manifest 预览</h2><span>{manifest ? `v${manifest.revision}` : '—'}</span></div>{manifest ? <><ol className="revision-list">{manifest.manifest.timeline.map((clip, index) => <li key={`${manifest.id}-${index}`}><strong>镜头 {index + 1}</strong><span>{clip.assetId} · {clip.durationMs}ms · sourceIn {clip.sourceInMs}ms</span></li>)}</ol><p className="muted">后续调整通过共享 Video Adjustment 层创建新的 Manifest Revision。</p><button type="button" onClick={() => void render()} disabled={busy}>Render 指定 Manifest</button></> : <p className="muted">创建工作区并准备 READY 素材后点击 Generate Plan。</p>}{messageText && <p className="status">{messageText}</p>}</section></section></main>;
}
