import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { isPortOpen, isProcessAlive, probeRuntimeIdentity, resolveRuntimeConfig, resolveRuntimePaths, RuntimeStateStore, type DoctorReport, type RuntimeIdentity, type RuntimeLog, type RuntimeResult, type RuntimeStatus, type ServiceStatus } from '../../../packages/runtime-core/src/index.js';

export interface RuntimeClientOptions { appRoot?: string; env?: Record<string, string | undefined>; controlPort?: number; token?: string; }
type ReadyOptions = { timeoutMs?: number | undefined; expectedInstanceId?: string | undefined };
type StartOptions = { safeMode?: boolean | undefined; timeoutMs?: number | undefined };

export class RuntimeClient {
  private readonly store: RuntimeStateStore;
  private readonly env: Record<string, string | undefined>;
  constructor(private readonly options: RuntimeClientOptions = {}) { this.env = { ...process.env, ...(options.env || {}), ...(options.appRoot ? { CONTENTOS_APP_ROOT: options.appRoot } : {}), ...(options.controlPort ? { CONTENTOS_RUNTIME_CONTROL_PORT: String(options.controlPort) } : {}) }; this.store = new RuntimeStateStore(resolveRuntimePaths(this.env)); }
  async state() { return this.store.read(); }
  private async identity(state: { controlPort: number; instanceId: string }): Promise<RuntimeIdentity> { const value = await probeRuntimeIdentity(state.controlPort); if (!value) throw Object.assign(new Error('Runtime control port is not a ContentOS Runtime'), { code: 'RUNTIME_CONTROL_PORT_CONFLICT', port: state.controlPort }); if (value.instanceId !== state.instanceId) throw Object.assign(new Error('Runtime identity does not match runtime state'), { code: 'RUNTIME_CONTROL_PORT_CONFLICT', port: state.controlPort, expectedInstanceId: state.instanceId, actualInstanceId: value.instanceId }); return value; }
  private async wait(delayMs: number): Promise<void> { await new Promise((resolveWait) => setTimeout(resolveWait, delayMs)); }
  async waitForReady(options: ReadyOptions = {}): Promise<RuntimeStatus> { const deadline = Date.now() + (options.timeoutMs || 60_000); let lastState: Awaited<ReturnType<RuntimeStateStore['read']>> = null; while (Date.now() < deadline) { const state = await this.store.read(); lastState = state; if (state) { if (state.state === 'FAILED') throw Object.assign(new Error('Runtime failed during startup'), { code: 'RUNTIME_START_FAILED', runtimeState: state, services: state.services, logPath: resolveRuntimePaths(this.env).logsRoot }); const identity = await probeRuntimeIdentity(state.controlPort); if (identity) { if (identity.instanceId !== state.instanceId || (options.expectedInstanceId && identity.instanceId !== options.expectedInstanceId)) throw Object.assign(new Error('Runtime identity does not match runtime state'), { code: 'RUNTIME_CONTROL_PORT_CONFLICT', state, identity }); const status = await this.request<RuntimeStatus>('/runtime/status'); if (status.state === 'READY' || status.state === 'READY_WITH_WARNINGS') return status; if (status.state === 'FAILED') throw Object.assign(new Error('Runtime failed during startup'), { code: 'RUNTIME_START_FAILED', status, runtimeState: state, logPath: resolveRuntimePaths(this.env).logsRoot }); } } await this.wait(250); } throw Object.assign(new Error('Runtime startup timed out'), { code: 'RUNTIME_START_TIMEOUT', runtimeState: lastState, services: lastState?.services || [], logPath: resolveRuntimePaths(this.env).logsRoot }); }
  async start(options: StartOptions = {}): Promise<RuntimeStatus> { const existing = await this.store.read(); if (existing) { const identity = await probeRuntimeIdentity(existing.controlPort); if (identity) { if (identity.instanceId !== existing.instanceId) throw Object.assign(new Error('Runtime control port is occupied by another instance'), { code: 'RUNTIME_CONTROL_PORT_CONFLICT', port: existing.controlPort, identity }); return this.waitForReady({ ...(options.timeoutMs === undefined ? {} : { timeoutMs: options.timeoutMs }), expectedInstanceId: existing.instanceId }); } if (await isPortOpen(existing.controlPort)) throw Object.assign(new Error('Runtime control port is occupied by another process'), { code: 'RUNTIME_CONTROL_PORT_CONFLICT', port: existing.controlPort }); if (isProcessAlive(existing.hostPid) && existing.state === 'STARTING') return this.waitForReady({ ...(options.timeoutMs === undefined ? {} : { timeoutMs: options.timeoutMs }), expectedInstanceId: existing.instanceId }); }
    const config = resolveRuntimeConfig(this.env);
    if (!existing) {
      const lock = await this.store.readLock();
      const lockPid = Number(lock?.hostPid);
      if (lock && isProcessAlive(lockPid)) return this.waitForReady(options.timeoutMs === undefined ? {} : { timeoutMs: options.timeoutMs, ...(typeof lock.instanceId === 'string' ? { expectedInstanceId: lock.instanceId } : {}) });
      if (await isPortOpen(config.controlPort)) { const identity = await probeRuntimeIdentity(config.controlPort); throw Object.assign(new Error(identity ? 'Runtime control port belongs to another Runtime' : 'Runtime control port is occupied by another process'), { code: 'RUNTIME_CONTROL_PORT_CONFLICT', port: config.controlPort, ...(identity ? { identity } : {}) }); }
    }
    await RuntimeClient.spawnHost({ ...(options.safeMode === undefined ? {} : { safeMode: options.safeMode }), env: this.env }); return this.waitForReady(options.timeoutMs === undefined ? {} : { timeoutMs: options.timeoutMs }); }
  private async request<T>(path: string, method = 'GET', body?: unknown): Promise<T> { const state = await this.store.read(); if (!state) throw Object.assign(new Error('RUNTIME_NOT_RUNNING'), { code: 'RUNTIME_NOT_RUNNING' }); await this.identity(state); const response = await fetch(`http://127.0.0.1:${state.controlPort}${path}`, { method, headers: { ...(state.controlToken ? { authorization: `Bearer ${state.controlToken}` } : {}), ...(body === undefined ? {} : { 'content-type': 'application/json' }) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw Object.assign(new Error(payload?.error?.message || `Runtime request failed (${response.status})`), { code: payload?.error?.code || 'RUNTIME_REQUEST_FAILED', details: payload }); return payload as T; }
  async getStatus(): Promise<RuntimeStatus> { return this.request<RuntimeStatus>('/runtime/status'); }
  async getServices(): Promise<ServiceStatus[]> { return (await this.request<{ items: ServiceStatus[] }>('/runtime/services')).items; }
  async runDoctor(): Promise<DoctorReport> { return this.request<DoctorReport>('/runtime/doctor', 'POST'); }
  async stop(timeoutMs = 60_000): Promise<RuntimeResult> { const state = await this.store.read(); if (!state) throw Object.assign(new Error('RUNTIME_NOT_RUNNING'), { code: 'RUNTIME_NOT_RUNNING' }); await this.request<RuntimeResult>('/runtime/stop', 'POST'); const deadline = Date.now() + timeoutMs; while (Date.now() < deadline) { const current = await this.store.read(); const ports = current?.services || state.services; if (!current && !isProcessAlive(state.hostPid) && (await Promise.all(ports.filter((item) => item.port).map((item) => isPortOpen(item.port!)))).every((open) => !open)) return { ok: true, message: 'ContentOS stopped' }; await this.wait(250); } throw Object.assign(new Error('Runtime shutdown timed out'), { code: 'RUNTIME_STOP_TIMEOUT', runtimeState: await this.store.read(), logPath: resolveRuntimePaths(this.env).logsRoot }); }
  async restart(options: StartOptions = {}): Promise<RuntimeResult> { const old = await this.store.read(); if (old) await this.stop(options.timeoutMs || 60_000); const status = await this.start(options); return { ok: true, message: 'Runtime restarted', status }; }
  async restartService(serviceId: string): Promise<RuntimeResult> { return this.request<RuntimeResult>(`/runtime/services/${encodeURIComponent(serviceId)}/restart`, 'POST'); }
  async getLogs(query?: { serviceId?: string; limit?: number }): Promise<RuntimeLog[]> { const suffix = new URLSearchParams({ ...(query?.serviceId ? { serviceId: query.serviceId } : {}), ...(query?.limit ? { limit: String(query.limit) } : {}) }); return (await this.request<{ items: RuntimeLog[] }>(`/runtime/logs?${suffix}`)).items; }
  static async spawnHost(options: { safeMode?: boolean; foreground?: boolean; env?: Record<string, string | undefined> } = {}): Promise<void> { const appRoot = resolve(options.env?.CONTENTOS_APP_ROOT || resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..')); const runner = resolve(appRoot, 'node_modules', 'tsx', 'dist', 'cli.mjs'); const entry = resolve(appRoot, 'apps', 'runtime-host', 'src', 'main.ts'); if (options.foreground) { await import(entry); return; } const child = spawn(process.execPath, [runner, entry, ...(options.safeMode ? ['--safe'] : [])], { cwd: appRoot, env: { ...process.env, ...(options.env || {}) }, detached: true, stdio: 'ignore', windowsHide: true }); child.unref(); }
}
