import { useEffect, useState } from 'react';
export type AdjustmentOperation = Record<string, unknown>;
export function buildReorderIndexes(index: number, clipCount: number): number[] {
  const indexes = Array.from({ length: clipCount }, (_, item) => item);
  if (index > 0 && index < clipCount) [indexes[index - 1], indexes[index]] = [indexes[index]!, indexes[index - 1]!];
  return indexes;
}
export function buildReplaceOperation(index: number, assetId: string): AdjustmentOperation { return { type: 'REPLACE', clipIndex: index, assetId }; }
type ReplacementAsset = { id: string; originalName?: string; durationMs?: number; thumbnailUrl?: string; orientation?: string; category?: string; usageCount?: number };
export function ClipInspector({ clip, index, clipCount = 1, replacementAssets = [], mode = 'RANDOM', editable = true, busy = false, onOperation }: { clip?: { assetId: string; sourceInMs: number; durationMs: number; sentenceText?: string; role?: 'INTRO' | 'CONTENT' | 'OUTRO'; voiceStartMs?: number; voiceEndMs?: number }; index: number | null; clipCount?: number; replacementAssets?: ReplacementAsset[]; mode?: 'SCRIPT' | 'RANDOM'; editable?: boolean; busy?: boolean; onOperation: (operation: AdjustmentOperation) => void }) {
  const [sourceInMs, setSourceInMs] = useState(clip?.sourceInMs || 0); const [durationMs, setDurationMs] = useState(clip?.durationMs || 1000);
  const [replacementAssetId, setReplacementAssetId] = useState(''); const [replacementQuery, setReplacementQuery] = useState(''); const [replacementOrientation, setReplacementOrientation] = useState('ALL'); const [replacementUsage, setReplacementUsage] = useState('ALL');
  useEffect(() => { setSourceInMs(clip?.sourceInMs || 0); setDurationMs(clip?.durationMs || 1000); setReplacementAssetId(''); }, [clip?.assetId, clip?.sourceInMs, clip?.durationMs, index]);
  if (!clip || index === null) return <div className="feedback">选择一个镜头查看镜头设置。</div>;
  const reorder = buildReorderIndexes(index, clipCount); const availableReplacements = replacementAssets.filter((asset) => asset.id !== clip.assetId && (!replacementQuery.trim() || (asset.originalName || '').toLowerCase().includes(replacementQuery.trim().toLowerCase())) && (replacementOrientation === 'ALL' || asset.orientation === replacementOrientation) && (replacementUsage === 'ALL' || (replacementUsage === 'UNUSED' ? !asset.usageCount : (asset.usageCount || 0) >= 3))); const voiceLocked = clip.voiceStartMs !== undefined && clip.voiceEndMs !== undefined; const branding = clip.role === 'INTRO' || clip.role === 'OUTRO';
  // Operation protocol values remain TRIM / REMOVE / REORDER / REPLACE / REROLL; labels are Chinese for operators.
  return <div><p className="muted">{branding ? (clip.role === 'INTRO' ? '片头' : '片尾') : `镜头 ${index + 1}`} · 当前素材</p>{voiceLocked && <p className="status">配音同步：时长已锁定（{(durationMs / 1000).toFixed(3)} 秒），可调整素材源起点。</p>}{!editable && <p className="status">当前正在查看历史剪辑版本。历史版本仅供查看，请切回当前版本后再调整。</p>}<label>起始位置（毫秒）<input type="number" value={sourceInMs} onChange={(event) => setSourceInMs(Number(event.target.value))} disabled={!editable || busy} /></label><label>时长（毫秒）<input type="number" value={durationMs} onChange={(event) => setDurationMs(Number(event.target.value))} readOnly={voiceLocked} disabled={!editable || busy || voiceLocked} /></label>{!branding && <><p className="muted">替换素材</p><div className="replacement-filters"><input aria-label="搜索替换素材" placeholder="搜索素材或标签" value={replacementQuery} onChange={(event) => setReplacementQuery(event.target.value)} /><select aria-label="方向筛选" value={replacementOrientation} onChange={(event) => setReplacementOrientation(event.target.value)}><option value="ALL">全部方向</option><option value="VERTICAL">竖屏</option><option value="HORIZONTAL">横屏</option><option value="SQUARE">方形</option></select><select aria-label="使用情况筛选" value={replacementUsage} onChange={(event) => setReplacementUsage(event.target.value)}><option value="ALL">全部使用情况</option><option value="UNUSED">未使用</option><option value="FREQUENT">高频使用</option></select></div><div className="replacement-picker">{availableReplacements.map((asset) => <button type="button" key={asset.id} className={replacementAssetId === asset.id ? 'selected' : ''} onClick={() => setReplacementAssetId(asset.id)} disabled={!editable || busy}>{asset.thumbnailUrl ? <img src={asset.thumbnailUrl} alt="" loading="lazy" /> : <span className="asset-thumb-placeholder">素材</span>}<span>{asset.originalName || '视频素材'}</span><small>{asset.durationMs ? `${(asset.durationMs / 1000).toFixed(1)} 秒` : ''}</small></button>)}</div></>}<div className="inspector-actions"><button type="button" disabled={!editable || busy || voiceLocked} onClick={() => onOperation({ type: 'TRIM', clipIndex: index, sourceInMs, durationMs })}>裁剪</button><button type="button" disabled={!editable || busy} onClick={() => onOperation({ type: 'REMOVE', clipIndex: index })}>移除</button><button type="button" disabled={!editable || busy || clipCount < 2} onClick={() => onOperation({ type: 'REORDER', clipIndexes: reorder })}>调整顺序</button>{!branding && <><button type="button" disabled={!editable || busy || !replacementAssetId} onClick={() => onOperation(buildReplaceOperation(index, replacementAssetId))}>替换素材</button><button type="button" disabled={!editable || busy} onClick={() => onOperation({ type: mode === 'SCRIPT' ? 'REMATCH' : 'REROLL', clipIndex: index })}>{mode === 'SCRIPT' ? '重新匹配' : '随机换一个'}</button></>}</div></div>;
}
