import * as React from 'react';
export type TimelineClip = { assetId: string; sourceInMs: number; durationMs: number; transition?: string; assetName?: string; sentenceText?: string; role?: 'INTRO' | 'CONTENT' | 'OUTRO'; reviewStatus?: 'GOOD' | 'REVIEW' | 'MANUAL'; thumbnailUrl?: string; voiceStartMs?: number; voiceEndMs?: number };
const statusText = { GOOD: '良好', REVIEW: '需复核', MANUAL: '人工修改' } as const;
const clock = (ms: number) => { const total = Math.max(0, ms) / 1000; const minutes = Math.floor(total / 60); const seconds = (total % 60).toFixed(3).padStart(6, '0'); return `${String(minutes).padStart(2, '0')}:${seconds}`; };
export function ManifestTimeline({ clips, selectedIndex, onSelect }: { clips: TimelineClip[]; selectedIndex: number | null; onSelect: (index: number) => void }) {
  const [filter, setFilter] = React.useState<'ALL' | 'REVIEW' | 'MANUAL'>('ALL');
  const counts = { ALL: clips.length, REVIEW: clips.filter((clip) => clip.reviewStatus === 'REVIEW').length, MANUAL: clips.filter((clip) => clip.reviewStatus === 'MANUAL').length };
  const visible = clips.map((clip, index) => ({ clip, index })).filter(({ clip }) => filter === 'ALL' || clip.reviewStatus === filter);
  return <div className="timeline" aria-label="剪辑时间线"><div className="timeline-toolbar"><span>共 {clips.length} 个镜头 · 需复核 {counts.REVIEW} · 人工修改 {counts.MANUAL}</span>{(['ALL', 'REVIEW', 'MANUAL'] as const).map((value) => <button type="button" key={value} className={filter === value ? 'selected' : ''} onClick={() => setFilter(value)}>{value === 'ALL' ? '全部' : value === 'REVIEW' ? '需复核' : '人工修改'} {counts[value]}</button>)}</div>{clips.length === 0 ? <p className="feedback">还没有镜头，请先生成计划。</p> : visible.map(({ clip, index }) => <button type="button" className={`clip-card${selectedIndex === index ? ' selected' : ''}`} key={`${clip.assetId}-${index}`} onClick={() => onSelect(index)}>{clip.thumbnailUrl ? <img className="clip-thumb" src={clip.thumbnailUrl} alt="" loading="lazy" /> : <span className="clip-thumb placeholder">{clip.role === 'INTRO' ? '片头' : clip.role === 'OUTRO' ? '片尾' : '镜头'}</span>}<span className="clip-index">{String(index + 1).padStart(2, '0')}</span><span><strong>{clip.role === 'INTRO' ? '片头' : clip.role === 'OUTRO' ? '片尾' : clip.assetName || `视频素材 ${index + 1}`}</strong><small>{clip.sentenceText || '品牌包装素材'} · {clock(clip.durationMs)} · 起点 {clock(clip.sourceInMs)}{clip.voiceStartMs !== undefined && clip.voiceEndMs !== undefined ? ' · 配音同步' : ''}</small></span><span className={`review-status ${clip.reviewStatus || 'GOOD'}`}>{statusText[clip.reviewStatus || 'GOOD']}</span></button>)}</div>;
}
