import { MediaBrowser } from './media-browser';

export type MediaStepItem = { id: string; originalName: string; durationMs: number; width?: number; height?: number; orientation?: string; tags?: string[]; category?: string; usageCount?: number; lastUsedAt?: string; thumbnailStatus?: string; thumbnailUrl?: string };
export type MediaStepScan = { status: string; progress: { discovered?: number; analyzed?: number; available?: number; unavailable?: number }; files: Array<{ available: boolean }> };

export function MediaStep({ assets, brandingAssets, selectedAssets, sourceRoot, scan, busy, query, orientation, category, usage, sort, mediaPage, indexTotal, mediaHasNext, introAssetId, outroAssetId, preferUnused, detailsAsset, tagDraft, tagInput, categoryDraft, onToggleAsset, onSourceRootChange, onScan, onQueryChange, onOrientationChange, onCategoryChange, onUsageChange, onSortChange, onPreviousPage, onNextPage, onToggleIntro, onToggleOutro, onPreferUnusedChange, onNext, onSelectDetails, onTagDraftChange, onTagInputChange, onCategoryDraftChange, onSaveDetails, onCloseDetails }: { assets: MediaStepItem[]; brandingAssets?: MediaStepItem[]; selectedAssets: string[]; sourceRoot: string; scan: MediaStepScan | null; busy: boolean; query: string; orientation: string; category: string; usage: string; sort: string; mediaPage: number; indexTotal: number; mediaHasNext: boolean; introAssetId: string; outroAssetId: string; preferUnused: boolean; detailsAsset: MediaStepItem | null; tagDraft: string; tagInput: string; categoryDraft: string; onToggleAsset: (id: string) => void; onSourceRootChange: (value: string) => void; onScan: () => void; onQueryChange: (value: string) => void; onOrientationChange: (value: string) => void; onCategoryChange: (value: string) => void; onUsageChange: (value: string) => void; onSortChange: (value: string) => void; onPreviousPage: () => void; onNextPage: () => void; onToggleIntro: (id: string) => void; onToggleOutro: (id: string) => void; onPreferUnusedChange: (value: boolean) => void; onNext: () => void; onSelectDetails: (asset: MediaStepItem) => void; onTagDraftChange: (value: string) => void; onTagInputChange: (value: string) => void; onCategoryDraftChange: (value: string) => void; onSaveDetails: () => void; onCloseDetails: () => void }) {
  const brandingBrowserAssets = [...(brandingAssets || []), ...assets.filter((asset) => !(brandingAssets || []).some((branding) => branding.id === asset.id))];
  return <>
    <section className="workflow-panel"><div className="section-title"><h2>② 选择素材</h2><span>{indexTotal || assets.length} 条可用素材 · 已选择 {selectedAssets.length} 条</span></div><p className="muted">项目素材库和本地素材可以混合选择；取消勾选的素材不会参与本次剪辑。</p>
      <div className="media-source-row"><label>素材文件夹<input aria-label="素材文件夹" value={sourceRoot} onChange={(event) => onSourceRootChange(event.target.value)} placeholder="例如：F:\素材\欧洲零售" /></label><button type="button" onClick={onScan} disabled={busy}>扫描文件夹</button></div>
      {scan && <p className="scan-summary">{scan.status === 'RUNNING' || scan.status === 'QUEUED' ? `正在扫描素材……已处理 ${scan.progress.analyzed || 0} / ${scan.progress.discovered || 0}` : `扫描完成：共 ${scan.progress.discovered || scan.files.length} 条视频，可用 ${scan.progress.available || scan.files.filter((file) => file.available).length} 条，无法读取 ${scan.progress.unavailable || 0} 条`}</p>}
      <div className="media-toolbar"><input aria-label="搜索素材" placeholder="搜索素材" value={query} onChange={(event) => onQueryChange(event.target.value)} /><select aria-label="方向筛选" value={orientation} onChange={(event) => onOrientationChange(event.target.value)}><option value="ALL">全部方向</option><option value="VERTICAL">竖屏</option><option value="HORIZONTAL">横屏</option><option value="SQUARE">方形</option></select><select aria-label="分类筛选" value={category} onChange={(event) => onCategoryChange(event.target.value)}><option value="">全部分类</option><option value="门店">门店</option><option value="商品">商品</option><option value="人物">人物</option><option value="货架">货架</option><option value="数据图表">数据图表</option><option value="其他">其他</option></select><select aria-label="使用情况" value={usage} onChange={(event) => onUsageChange(event.target.value)}><option value="ALL">全部使用情况</option><option value="UNUSED">从未使用</option><option value="RECENT">最近少用</option><option value="FREQUENT">高频使用</option></select><select aria-label="排序" value={sort} onChange={(event) => onSortChange(event.target.value)}><option value="RECOMMENDED">推荐</option><option value="NEWEST">最近新增</option><option value="LEAST_USED">最少使用</option><option value="MOST_RECENT">最近使用</option><option value="DURATION">时长</option></select></div>
      <MediaBrowser assets={assets} selected={selectedAssets} onToggle={onToggleAsset} onEdit={onSelectDetails} />
      <div className="media-pagination" aria-label="素材分页"><button type="button" onClick={onPreviousPage} disabled={mediaPage <= 1}>上一页</button><span>第 {mediaPage} 页 · 共 {indexTotal} 条</span><button type="button" onClick={onNextPage} disabled={!mediaHasNext}>下一页</button></div>
      <details><summary>高级设置：品牌包装</summary><p className="muted">片头和片尾会使用品牌素材选择器，默认来自当前模板。</p><p>片头</p><MediaBrowser assets={brandingBrowserAssets} selected={introAssetId ? [introAssetId] : []} onToggle={onToggleIntro} emptyText="暂无品牌素材，请先上传品牌视频。" /><p>片尾</p><MediaBrowser assets={brandingBrowserAssets} selected={outroAssetId ? [outroAssetId] : []} onToggle={onToggleOutro} emptyText="暂无品牌素材，请先上传品牌视频。" /></details>
      <label className="inline-check"><input type="checkbox" checked={preferUnused} onChange={(event) => onPreferUnusedChange(event.target.checked)} />优先使用近期没出现过的素材</label><p className="muted">系统会尽量避开最近视频中已经使用过的素材。</p><button type="button" className="primary-action" onClick={onNext} disabled={selectedAssets.length === 0}>下一步：自动剪辑</button>
    </section>
    {detailsAsset && <aside className="media-details" aria-label="素材信息"><h3>素材信息</h3><p>{detailsAsset.originalName}</p><label>分类<select value={categoryDraft} onChange={(event) => onCategoryDraftChange(event.target.value)}><option value="">未分类</option><option value="门店">门店</option><option value="商品">商品</option><option value="人物">人物</option><option value="货架">货架</option><option value="数据图表">数据图表</option><option value="其他">其他</option></select></label><label>标签<span className="tag-chip-list">{tagDraft.split(/[、,，\n]/u).map((tag) => tag.trim()).filter(Boolean).map((tag) => <button type="button" className="tag-chip" key={tag} onClick={() => onTagDraftChange(tagDraft.split(/[、,，\n]/u).map((item) => item.trim()).filter((item) => item && item !== tag).join('、'))}>{tag} ×</button>)}</span><input aria-label="添加标签" value={tagInput} onChange={(event) => onTagInputChange(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && tagInput.trim()) { event.preventDefault(); onTagDraftChange([...tagDraft.split(/[、,，\n]/u).map((item) => item.trim()).filter(Boolean), tagInput.trim()].filter((item, index, all) => all.indexOf(item) === index).join('、')); onTagInputChange(''); } }} placeholder="输入标签后按 Enter" /></label><p className="muted">使用次数：{detailsAsset.usageCount || 0} 次</p><button type="button" onClick={onSaveDetails}>保存</button><button type="button" onClick={onCloseDetails}>取消</button></aside>}
  </>;
}
