import { ClipInspector } from './clip-inspector';
import { ClipPreview } from './clip-preview';
import { EditModeSelector, type EditMode } from './edit-mode-selector';

type Clip = { assetId: string; sourceInMs: number; durationMs: number; sentenceText?: string; role?: 'INTRO' | 'CONTENT' | 'OUTRO'; reviewStatus?: 'GOOD' | 'REVIEW' | 'MANUAL'; voiceStartMs?: number; voiceEndMs?: number; matching?: { matchedKeywords: string[]; matchScore: number; fallback: boolean; matchingReason: string }; };
type Manifest = { id: string; status: 'PERSISTED' | 'SUPERSEDED'; revision: number; manifest: { timeline: Clip[]; metadata?: { editMode?: EditMode } } } | null;
type Asset = { id: string; originalName: string; durationMs: number; tags?: string[]; category?: string; usageCount?: number; thumbnailStatus?: string; thumbnailUrl?: string };

export function ReviewStep({ manifest, visibleClipIndexes, reviewCount, manualCount, reviewFilter, setReviewFilter, selectedClips, setSelectedClips, currentClip, selectedClip, setSelectedClip, clipSource, mediaAssets, busy, mode, operations, setOperations, onBulk, onSave, onNext, history, onRegenerate, thumbnailFor, onModeChange }: { manifest: Manifest; visibleClipIndexes: number[]; reviewCount: number; manualCount: number; reviewFilter: 'ALL' | 'REVIEW' | 'MANUAL'; setReviewFilter: (value: 'ALL' | 'REVIEW' | 'MANUAL') => void; selectedClips: number[]; setSelectedClips: (value: number[] | ((current: number[]) => number[])) => void; currentClip?: Clip; selectedClip: number | null; setSelectedClip: (value: number) => void; clipSource?: string; mediaAssets: Asset[]; busy: boolean; mode: EditMode; operations: Array<Record<string, unknown>>; setOperations: (value: Array<Record<string, unknown>> | ((current: Array<Record<string, unknown>>) => Array<Record<string, unknown>>)) => void; onBulk: (type: 'REMATCH' | 'REROLL') => void; onSave: () => void; onNext: () => void; history: Array<{ id: string; revision: number; status: string }>; onRegenerate: () => void; thumbnailFor: (clip: Clip) => string | undefined; onModeChange: (mode: EditMode) => void }) {
  const editMode = manifest?.manifest.metadata?.editMode || mode;
  return <section className="workflow-panel review-panel">
    <div className="section-title"><h2>④ 检查镜头</h2><span>{manifest?.manifest.timeline.length || 0} 个镜头 · {reviewCount} 个建议检查</span></div>
    <div className="review-toolbar"><button type="button" className={reviewFilter === 'ALL' ? 'selected' : ''} onClick={() => setReviewFilter('ALL')}>全部 {manifest?.manifest.timeline.length || 0}</button><button type="button" className={reviewFilter === 'REVIEW' ? 'selected' : ''} onClick={() => setReviewFilter('REVIEW')}>建议检查 {reviewCount}</button><button type="button" className={reviewFilter === 'MANUAL' ? 'selected' : ''} onClick={() => setReviewFilter('MANUAL')}>人工修改 {manualCount}</button><button type="button" onClick={() => setSelectedClips(visibleClipIndexes)}>全选当前结果</button><button type="button" onClick={() => setSelectedClips([])}>取消选择</button>{selectedClips.length > 0 && <><span>已选择 {selectedClips.length} 个镜头</span><button type="button" onClick={() => onBulk(editMode === 'SCRIPT' ? 'REMATCH' : 'REROLL')}>{editMode === 'SCRIPT' ? '批量重新匹配' : '批量随机换素材'}</button></>}</div>
    {manifest && <div className="review-list sentence-list">{manifest.manifest.timeline.map((clip, index) => { if (!visibleClipIndexes.includes(index)) return null; const branding = clip.role === 'INTRO' || clip.role === 'OUTRO'; const thumbnailUrl = thumbnailFor(clip); return <label className={`review-row${selectedClips.includes(index) ? ' selected' : ''}`} key={`${clip.assetId}-${index}`}><input type="checkbox" disabled={branding} checked={selectedClips.includes(index)} onChange={() => setSelectedClips((current) => current.includes(index) ? current.filter((item) => item !== index) : [...current, index])} /><span className="review-index">{String(index + 1).padStart(2, '0')}</span><span className="review-thumb">{thumbnailUrl ? <img src={thumbnailUrl} alt="" loading="lazy" /> : branding ? (clip.role === 'INTRO' ? '品牌片头' : '品牌片尾') : '暂无预览'}</span><span><strong>{clip.role === 'INTRO' ? '片头' : clip.role === 'OUTRO' ? '片尾' : clip.sentenceText || '正文镜头'}</strong><small>{clip.reviewStatus === 'MANUAL' ? '人工修改' : clip.reviewStatus === 'REVIEW' || clip.matching?.fallback ? '建议检查' : '良好'} · {(clip.durationMs / 1000).toFixed(1)} 秒</small></span><button type="button" className="review-row-button" onClick={() => setSelectedClip(index)}>选择镜头</button></label>; })}</div>}
    {currentClip ? <div className="current-clip"><h3>当前镜头预览</h3><ClipPreview src={clipSource} sourceInMs={currentClip.sourceInMs} durationMs={currentClip.durationMs} label={currentClip.assetId} /><p className="muted">文案：{currentClip.sentenceText || '品牌包装'} · 素材：{mediaAssets.find((asset) => asset.id === currentClip.assetId)?.originalName || '当前素材'}</p><ClipInspector clip={currentClip} index={selectedClip} clipCount={manifest?.manifest.timeline.length || 0} replacementAssets={mediaAssets} mode={editMode} editable={manifest.status !== 'SUPERSEDED'} busy={busy} onOperation={(operation) => setOperations((current) => [...current, operation])} /></div> : <p className="muted">选择镜头查看预览。</p>}
    {operations.length > 0 && <p className="status">待提交调整：{operations.length} 项</p>}
    <div className="review-actions"><button type="button" onClick={onSave} disabled={busy || operations.length === 0}>保存镜头调整</button><button type="button" className="primary-action" onClick={onNext} disabled={!manifest || operations.length > 0}>下一步：生成成片</button></div>
    <details><summary>查看历史版本</summary><p className="muted">已保存 {history.length} 个剪辑版本。</p>{history.filter((item) => item.id !== manifest?.id).map((item) => <p key={item.id}>剪辑版本 {item.revision} · {item.status === 'PERSISTED' ? '当前可用' : '历史记录'}</p>)}</details>
    <details><summary>重新生成剪辑</summary><EditModeSelector mode={editMode} onSelect={onModeChange} /><button type="button" onClick={onRegenerate} disabled={busy}>生成剪辑方案</button></details>
  </section>;
}
