import { randomUUID } from 'node:crypto';
import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { DirectorJobService } from '../../../packages/modules/director/src/director-job-service.js';
import { DirectorV1Service } from '../../../packages/modules/director/src/director-v1-service.js';
import { JobService } from '../../../packages/modules/job/src/index.js';

const briefInput = z.object({ topic: z.string().trim().min(1).max(20_000), targetPlatform: z.string().trim().min(1).max(100), channelPositioning: z.string().trim().min(1).max(20_000), targetDurationSeconds: z.number().int().min(1).max(600), contentType: z.string().trim().min(1).max(100), audience: z.string().trim().min(1).max(20_000), coreThesis: z.string().trim().min(1).max(20_000), tone: z.string().trim().min(1).max(20_000), ctaGoal: z.string().trim().max(20_000).optional(), referenceMaterial: z.string().trim().min(1).max(20_000), mustInclude: z.array(z.string().trim().min(1).max(2_000)).max(32), mustAvoid: z.array(z.string().trim().min(1).max(2_000)).max(32), requirements: z.record(z.string(), z.unknown()), createdBy: z.string().trim().min(1).max(200) }).strict();
const generateInput = z.object({ briefId: z.string().trim().min(1).max(200), scriptAggregateId: z.string().trim().min(1).max(200).optional(), modelProfileId: z.string().trim().min(1).max(200).optional(), correlationId: z.string().trim().min(1).max(200).optional() }).strict();
const scriptInput = z.object({ origin: z.enum(['MANUAL', 'IMPORTED']), title: z.string().trim().min(1).max(500), titleCandidates: z.array(z.string().trim().min(1).max(2_000)).min(1).max(8), coverText: z.string().trim().min(1).max(500), topicKeywords: z.array(z.string().trim().min(1).max(2_000)).min(1).max(32), hook: z.string().trim().min(1).max(20_000), body: z.string().trim().min(1).max(20_000), cta: z.string().trim().max(20_000).optional(), createdBy: z.string().trim().min(1).max(200) }).strict();
const storyboardGenerateInput = z.object({ storyboardAggregateId: z.string().trim().min(1).max(200).optional(), modelProfileId: z.string().trim().min(1).max(200).optional(), correlationId: z.string().trim().min(1).max(200).optional() }).strict();

export interface DirectorRouteDependencies { director: DirectorV1Service; directorJobs: DirectorJobService; jobs: JobService; }
function validation(reply: { code: (status: number) => { send: (body: unknown) => unknown } }, message: string, details: unknown): unknown { return reply.code(422).send({ error: { code: 'DIRECTOR_VALIDATION_ERROR', message, details } }); }
function failure(reply: { code: (status: number) => { send: (body: unknown) => unknown } }, status: number, code: string, message: string): unknown { return reply.code(status).send({ error: { code, message, details: [] } }); }

export function registerDirectorV1Routes(app: FastifyInstance, deps: DirectorRouteDependencies): void {
  app.post('/api/v1/projects/:projectId/director/brief', async (request, reply) => {
    const parsed = briefInput.safeParse(request.body); if (!parsed.success) return validation(reply, 'Invalid ContentBrief input', parsed.error.issues);
    const { ctaGoal, ...briefFields } = parsed.data;
    const input = ctaGoal === undefined ? briefFields : { ...briefFields, ctaGoal };
    try { return reply.code(201).send(await deps.director.createBrief((request.params as { projectId: string }).projectId, input)); } catch (error) { return failure(reply, 404, 'DIRECTOR_PROJECT_NOT_FOUND', error instanceof Error ? error.message : 'Project not found'); }
  });
  app.post('/api/v1/projects/:projectId/scripts/generate', async (request, reply) => {
    const projectId = (request.params as { projectId: string }).projectId; const parsed = generateInput.safeParse(request.body); if (!parsed.success) return validation(reply, 'Invalid Script generation input', parsed.error.issues);
    try {
      const brief = await deps.director.getBrief(parsed.data.briefId, projectId); if (!brief) return failure(reply, 404, 'DIRECTOR_BRIEF_NOT_FOUND', 'Brief not found');
      const script = parsed.data.scriptAggregateId ? { id: parsed.data.scriptAggregateId } : await deps.director.createScript(projectId, brief.id);
      const job = await deps.directorJobs.createScriptGeneration({ projectId, briefId: brief.id, scriptAggregateId: script.id, ...(parsed.data.modelProfileId ? { modelProfileId: parsed.data.modelProfileId } : {}), correlationId: parsed.data.correlationId ?? `api-${randomUUID()}` });
      return reply.code(202).send({ jobId: job.id, state: job.state, scriptAggregateId: script.id, projectId });
    } catch (error) { return failure(reply, 409, 'DIRECTOR_JOB_CONFLICT', error instanceof Error ? error.message : 'Director Job conflict'); }
  });
  app.get('/api/v1/projects/:projectId/scripts', async (request) => ({ items: await deps.director.listScriptRevisions((request.params as { projectId: string }).projectId) }));
  app.get('/api/v1/projects/:projectId/scripts/:scriptId', async (request, reply) => { const params = request.params as { projectId: string; scriptId: string }; const result = await deps.director.getScriptRevision(params.scriptId, params.projectId); return result ? result : failure(reply, 404, 'DIRECTOR_SCRIPT_NOT_FOUND', 'Script revision not found'); });
  app.post('/api/v1/projects/:projectId/scripts/:scriptId/revisions', async (request, reply) => { const params = request.params as { projectId: string; scriptId: string }; const parsed = scriptInput.safeParse(request.body); if (!parsed.success) return validation(reply, 'Invalid Script revision input', parsed.error.issues); const { cta, ...scriptFields } = parsed.data; const input = cta === undefined ? scriptFields : { ...scriptFields, cta }; try { const parent = await deps.director.getScriptRevision(params.scriptId, params.projectId); const result = parent ? await deps.director.createManualScriptRevision(params.projectId, params.scriptId, input, parsed.data.createdBy) : await deps.director.createScriptRevision(params.projectId, params.scriptId, input); return reply.code(201).send(result); } catch (error) { return failure(reply, 409, 'DIRECTOR_SCRIPT_REVISION_CONFLICT', error instanceof Error ? error.message : 'Script revision conflict'); } });
  app.post('/api/v1/projects/:projectId/scripts/:scriptId/accept', async (request, reply) => { const params = request.params as { projectId: string; scriptId: string }; try { return deps.director.acceptScript(params.projectId, params.scriptId); } catch (error) { return failure(reply, 409, 'DIRECTOR_SCRIPT_TRANSITION_CONFLICT', error instanceof Error ? error.message : 'Script transition conflict'); } });
  app.post('/api/v1/projects/:projectId/scripts/:scriptId/storyboards/generate', async (request, reply) => { const params = request.params as { projectId: string; scriptId: string }; const parsed = storyboardGenerateInput.safeParse(request.body || {}); if (!parsed.success) return validation(reply, 'Invalid Storyboard generation input', parsed.error.issues); try { const script = await deps.director.getScriptRevision(params.scriptId, params.projectId); if (!script) return failure(reply, 404, 'DIRECTOR_SCRIPT_NOT_FOUND', 'Script revision not found'); if (script.status !== 'ACCEPTED') return failure(reply, 409, 'DIRECTOR_SCRIPT_NOT_ACCEPTED', 'Storyboard generation requires an accepted Script'); const board = parsed.data.storyboardAggregateId ? { id: parsed.data.storyboardAggregateId } : await deps.director.createStoryboard(params.projectId); const job = await deps.directorJobs.createStoryboardGeneration({ projectId: params.projectId, scriptRevisionId: script.id, storyboardAggregateId: board.id, ...(parsed.data.modelProfileId ? { modelProfileId: parsed.data.modelProfileId } : {}), correlationId: parsed.data.correlationId ?? `api-${randomUUID()}` }); return reply.code(202).send({ jobId: job.id, state: job.state, storyboardAggregateId: board.id, projectId: params.projectId }); } catch (error) { return failure(reply, 409, 'DIRECTOR_JOB_CONFLICT', error instanceof Error ? error.message : 'Director Job conflict'); } });
  app.get('/api/v1/projects/:projectId/storyboards', async (request) => ({ items: await deps.director.listStoryboardRevisions((request.params as { projectId: string }).projectId) }));
  app.get('/api/v1/projects/:projectId/storyboards/:storyboardId', async (request, reply) => { const params = request.params as { projectId: string; storyboardId: string }; const result = await deps.director.getStoryboardRevision(params.storyboardId, params.projectId); return result ? result : failure(reply, 404, 'DIRECTOR_STORYBOARD_NOT_FOUND', 'Storyboard revision not found'); });
  app.post('/api/v1/projects/:projectId/storyboards/:storyboardId/approve', async (request, reply) => { const params = request.params as { projectId: string; storyboardId: string }; try { return deps.director.approveStoryboard(params.projectId, params.storyboardId); } catch (error) { return failure(reply, 409, 'DIRECTOR_STORYBOARD_TRANSITION_CONFLICT', error instanceof Error ? error.message : 'Storyboard transition conflict'); } });
  app.get('/api/v1/jobs/:jobId', async (request, reply) => { const job = await deps.jobs.get((request.params as { jobId: string }).jobId); if (!job) return failure(reply, 404, 'JOB_NOT_FOUND', 'Job not found'); return { id: job.id, projectId: job.projectId, type: job.type, state: job.state, result: job.result, error: job.error, attemptCount: job.attemptCount, maxAttempts: job.maxAttempts }; });
}
