import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { IntelligentDecisionService } from '../../../packages/modules/intelligence/src/index.js';
import { ProjectService } from '../../../packages/modules/project/src/index.js';

const presetInput = z.object({ name: z.string().trim().min(1).max(100), config: z.object({ schemaVersion: z.literal('INTELLIGENT_PLANNER_CONFIG_V1'), version: z.string().min(1), targetDurationMs: z.number().int().positive(), minClipDurationMs: z.number().int().positive(), maxClipDurationMs: z.number().int().positive(), maxAssetReuse: z.number().int().positive(), diversityWeight: z.number().min(0).max(1) }), enabled: z.boolean().optional() }).strict();
const recommendationInput = z.object({ presetId: z.string().trim().min(1).nullable().optional(), profile: z.string().trim().min(1).max(100), confidence: z.number().min(0).max(1), alternatives: z.array(z.string().trim().min(1)).optional(), limitations: z.array(z.string().trim().min(1)).optional(), evidence: z.record(z.string(), z.unknown()).optional() }).strict();
const decisionEventInput = z.object({ sentenceId: z.string().trim().min(1).nullable().optional(), eventType: z.enum(['SHOT_ACCEPTED', 'SHOT_REPLACED', 'SHOT_EXCLUDED', 'ASSET_EXCLUDED', 'DURATION_CHANGED']), previousCandidateId: z.string().trim().min(1).nullable().optional(), nextCandidateId: z.string().trim().min(1).nullable().optional(), previousShotId: z.string().trim().min(1).nullable().optional(), nextShotId: z.string().trim().min(1).nullable().optional(), evidence: z.record(z.string(), z.unknown()).optional() }).strict();

export function registerIntelligentDecisionRoutes(app: FastifyInstance, dependencies: { projects: ProjectService; decisions: IntelligentDecisionService }): void {
  app.get('/api/v1/projects/:projectId/intelligence/presets', async (request, reply) => { const projectId = String((request.params as { projectId: string }).projectId); if (!(await dependencies.projects.get(projectId))) return reply.code(404).send({ error: { code: 'PROJECT_NOT_FOUND', message: 'Project not found', details: [] } }); return { items: await dependencies.decisions.listPresets(projectId) }; });
  app.post('/api/v1/projects/:projectId/intelligence/presets', async (request, reply) => { const projectId = String((request.params as { projectId: string }).projectId); if (!(await dependencies.projects.get(projectId))) return reply.code(404).send({ error: { code: 'PROJECT_NOT_FOUND', message: 'Project not found', details: [] } }); const parsed = presetInput.safeParse(request.body || {}); if (!parsed.success) return reply.code(422).send({ error: { code: 'VALIDATION_ERROR', message: 'Invalid intelligent preset input', details: parsed.error.issues } }); try { return reply.code(201).send(await dependencies.decisions.createPreset({ projectId, name: parsed.data.name, config: parsed.data.config, ...(parsed.data.enabled === undefined ? {} : { enabled: parsed.data.enabled }) })); } catch (error) { const message = error instanceof Error ? error.message : 'Preset rejected'; return reply.code(409).send({ error: { code: message, message, details: [] } }); } });
  app.post('/api/v1/projects/:projectId/intelligence/plans/:planId/decisions', async (request, reply) => { const params = request.params as { projectId: string; planId: string }; const parsed = decisionEventInput.safeParse(request.body || {}); if (!parsed.success) return reply.code(422).send({ error: { code: 'VALIDATION_ERROR', message: 'Invalid intelligent decision event', details: parsed.error.issues } }); try { return reply.code(201).send(await dependencies.decisions.createDecisionEvent({ projectId: params.projectId, planId: params.planId, eventType: parsed.data.eventType, ...(parsed.data.sentenceId === undefined ? {} : { sentenceId: parsed.data.sentenceId }), ...(parsed.data.previousCandidateId === undefined ? {} : { previousCandidateId: parsed.data.previousCandidateId }), ...(parsed.data.nextCandidateId === undefined ? {} : { nextCandidateId: parsed.data.nextCandidateId }), ...(parsed.data.previousShotId === undefined ? {} : { previousShotId: parsed.data.previousShotId }), ...(parsed.data.nextShotId === undefined ? {} : { nextShotId: parsed.data.nextShotId }), ...(parsed.data.evidence === undefined ? {} : { evidence: parsed.data.evidence }) })); } catch (error) { const message = error instanceof Error ? error.message : 'Decision event rejected'; return reply.code(message.includes('NOT_FOUND') ? 404 : 422).send({ error: { code: message, message, details: [] } }); } });
  app.get('/api/v1/projects/:projectId/intelligence/plans/:planId/decisions', async (request) => { const params = request.params as { projectId: string; planId: string }; return { items: await dependencies.decisions.listDecisionEvents(params.projectId, params.planId) }; });
  app.post('/api/v1/projects/:projectId/intelligence/plans/:planId/recommendations/build', async (request, reply) => { const params = request.params as { projectId: string; planId: string }; const body = request.body && typeof request.body === 'object' ? request.body as { presetId?: unknown } : {}; try { return reply.code(201).send(await dependencies.decisions.buildRecommendation(params.projectId, params.planId, typeof body.presetId === 'string' ? body.presetId : null)); } catch (error) { const message = error instanceof Error ? error.message : 'Recommendation build failed'; return reply.code(message.includes('NOT_FOUND') ? 404 : 422).send({ error: { code: message, message, details: [] } }); } });
  app.post('/api/v1/projects/:projectId/intelligence/plans/:planId/recommendations', async (request, reply) => { const params = request.params as { projectId: string; planId: string }; const parsed = recommendationInput.safeParse(request.body || {}); if (!parsed.success) return reply.code(422).send({ error: { code: 'VALIDATION_ERROR', message: 'Invalid intelligent recommendation input', details: parsed.error.issues } }); try { return reply.code(201).send(await dependencies.decisions.createRecommendation({ projectId: params.projectId, planId: params.planId, profile: parsed.data.profile, confidence: parsed.data.confidence, ...(parsed.data.presetId === undefined ? {} : { presetId: parsed.data.presetId }), ...(parsed.data.alternatives === undefined ? {} : { alternatives: parsed.data.alternatives }), ...(parsed.data.limitations === undefined ? {} : { limitations: parsed.data.limitations }), ...(parsed.data.evidence === undefined ? {} : { evidence: parsed.data.evidence }) })); } catch (error) { const message = error instanceof Error ? error.message : 'Recommendation rejected'; return reply.code(message.includes('NOT_FOUND') ? 404 : 422).send({ error: { code: message, message, details: [] } }); } });
  app.get('/api/v1/projects/:projectId/intelligence/plans/:planId/recommendations', async (request) => { const params = request.params as { projectId: string; planId: string }; return { items: await dependencies.decisions.listRecommendations(params.projectId, params.planId) }; });
}
