import { createHash, randomUUID } from 'node:crypto';
import { access, stat } from 'node:fs/promises';
import { createReadStream } from 'node:fs';
import { extname } from 'node:path';
import type { FastifyInstance } from 'fastify';
import type { Pool } from 'pg';
import { z } from 'zod';
import { createExternalVideoProvider, ensureStandaloneWorkspace, HybridMediaService, JianyingRuntimeLocator, ScriptEditingV3EvaluationService, ScriptEditingV3Service, type VideoService } from '../../../packages/modules/video/src/index.js';
import type { JobService } from '../../../packages/modules/job/src/index.js';
import { AssetCatalogService, type AssetService, type LocalMediaSourceService } from '../../../packages/modules/asset/src/index.js';
import type { LocalPathAccessService } from '../../../packages/modules/local-path/src/index.js';
import type { LocalStorageProvider } from '../../../packages/infrastructure/storage/src/index.js';
import { prepareVoiceTiming } from '../../../packages/modules/video/src/index.js';

const scanInput = z.object({ workspaceId: z.string().trim().min(1), sourceRoot: z.string().trim().min(1), recursive: z.boolean().default(true) });
const snapshotInput = z.object({ workspaceId: z.string().trim().min(1), sourceRootIds: z.array(z.string().trim().min(1)).default([]), sourceFiles: z.array(z.string().trim().min(1)).max(100).default([]), sourceKind: z.enum(['MANUAL', 'JIANYING_DRAFT', 'MIXED']).default('MANUAL') });
const sessionInput = z.object({
  workspaceId: z.string().trim().min(1),
  snapshotId: z.string().trim().min(1),
  script: z.string().trim().min(1),
  voicePath: z.string().trim().min(1).optional(),
  presentationSettings: z.record(z.string(), z.unknown()).optional(),
  template: z.enum(['COMMERCIAL_OPINION', 'NEWS', 'STORE_PROMOTION', 'PRODUCT_INTRO']).optional(),
  pace: z.enum(['SLOW', 'NORMAL', 'FAST']).optional(),
  shotDensity: z.enum(['LOW', 'MEDIUM', 'HIGH']).optional(),
  subtitleStyle: z.enum(['simple', 'commercial', 'emphasis', 'news']).optional(),
  audioPlan: z.record(z.string(), z.unknown()).optional(),
  brandingPlan: z.record(z.string(), z.unknown()).optional(),
  usePexels: z.boolean().optional(),
  sentences: z.array(z.object({ text: z.string().trim().min(1), startMs: z.number().nonnegative().optional(), endMs: z.number().positive().optional(), voiceStartMs: z.number().nonnegative().optional(), voiceEndMs: z.number().positive().optional(), durationMs: z.number().positive().optional() })).optional(),
});
const operationInput = z.discriminatedUnion('type', [
  z.object({ type: z.literal('REPLACE_CLIP'), sentenceId: z.string().min(1), assetId: z.string().min(1), sourceInMs: z.number().int().nonnegative().optional(), sourceSegmentId: z.string().min(1).optional() }),
  z.object({ type: z.literal('TRIM_SOURCE'), sentenceId: z.string().min(1), sourceInMs: z.number().int().nonnegative(), sourceOutMs: z.number().int().positive() }),
  z.object({ type: z.literal('LOCK_CLIP'), sentenceId: z.string().min(1) }),
  z.object({ type: z.literal('UNLOCK_CLIP'), sentenceId: z.string().min(1) }),
  z.object({ type: z.literal('MANUAL_SELECT_CLIP'), sentenceId: z.string().min(1), assetId: z.string().min(1), sourceInMs: z.number().int().nonnegative().optional(), sourceSegmentId: z.string().min(1).optional() }),
]);
const jianyingInput = z.object({ workspaceId: z.string().trim().min(1), draftPath: z.string().trim().min(1).optional(), draftPaths: z.array(z.string().trim().min(1)).min(1).optional() }).refine((value) => Boolean(value.draftPath || value.draftPaths?.length), { message: 'draftPath or draftPaths is required' });
const goldInput = z.object({ gold: z.boolean() });
const manualTagsInput = z.object({ tags: z.array(z.string().trim().min(1)).default([]) });
const evaluationImportInput = z.object({ workspaceId: z.string().trim().min(1), name: z.string().trim().min(1).max(200), snapshotId: z.string().trim().min(1).optional(), idempotencyKey: z.string().trim().min(1).max(200).optional(), items: z.array(z.object({ assetId: z.string().trim().min(1), sourceFingerprint: z.string().optional(), fileName: z.string().trim().min(1), durationMs: z.number().int().nonnegative().optional(), tags: z.array(z.string()).optional(), visualProfile: z.unknown().optional() })).min(100).max(300), queries: z.array(z.object({ id: z.string().trim().min(1), visualNeed: z.string().trim().min(1), usableAssetIds: z.array(z.string()), forbiddenAssetIds: z.array(z.string()).optional(), metadata: z.record(z.string(), z.unknown()).optional() })).min(10).max(20), judgments: z.array(z.object({ queryId: z.string(), assetId: z.string(), label: z.enum(['BEST', 'USABLE', 'UNUSABLE', 'FORBIDDEN']), reason: z.string().optional(), annotator: z.string().default('operator') })).optional() });
const evaluationJudgmentInput = z.object({ queryId: z.string().trim().min(1), assetId: z.string().trim().min(1), label: z.enum(['BEST', 'USABLE', 'UNUSABLE', 'FORBIDDEN']), reason: z.string().trim().max(100).optional(), annotator: z.string().trim().min(1).max(100).default('operator') });
function csvCell(value: unknown): string { return `"${String(value ?? '').replace(/"/gu, '""')}"`; }
function parseCsvLine(line: string): string[] { const cells: string[] = []; const pattern = /("(?:""|[^"])*"|[^,]*)(?:,|$)/gu; let match: RegExpExecArray | null; while ((match = pattern.exec(line))) { const value = match[1] || ''; cells.push(value.startsWith('"') && value.endsWith('"') ? value.slice(1, -1).replace(/""/gu, '"') : value); if (pattern.lastIndex >= line.length) break; } return cells; }

function errorCode(error: unknown): string { return error instanceof Error ? error.message : 'SCRIPT_EDITING_V3_FAILED'; }
function sourceRootId(root: string): string { return `local-${Buffer.from(root.toLowerCase()).toString('base64url').slice(0, 18)}`; }
function publicSnapshot(snapshot: Awaited<ReturnType<ScriptEditingV3Service['getSnapshot']>>) { return { ...snapshot, items: snapshot.items.map(({ sourcePath: _sourcePath, ...item }) => item) }; }
function publicSession(session: Awaited<ReturnType<ScriptEditingV3Service['getSession']>>) { return { ...session, cards: session.cards.map((card) => ({ ...card, ...(card.asset ? { asset: (({ sourcePath: _sourcePath, ...item }) => item)(card.asset) } : {}) })) }; }
function visualAnalysisConfig(): string { return `${process.env.QWEN_VL_MODEL || process.env.QWEN_MODEL || 'qwen-vl-max'}:${process.env.QWEN_MODEL_VERSION || 'unknown'}:qwen-visual-v2:asset-profile-v2`; }
function qwenConfigured(): boolean { return Boolean(process.env.QWEN_API_KEY?.trim() && (process.env.QWEN_BASE_URL?.trim() || process.env.QWEN_API_URL?.trim())); }

async function enqueueVisualAnalysisJobs(
  snapshot: Awaited<ReturnType<ScriptEditingV3Service['getSnapshot']>>,
  jobs: JobService,
): Promise<{ configured: boolean; queued: number; eligible: number }> {
  const eligible = snapshot.items.filter((item) => item.availability === 'VALID' && !item.disabled);
  if (!qwenConfigured()) return { configured: false, queued: 0, eligible: eligible.length };
  const analysisConfig = visualAnalysisConfig();
  await Promise.all(eligible.map((item) => jobs.createIdempotent({
    id: `job-${randomUUID()}`,
    projectId: null,
    workspaceId: snapshot.workspaceId,
    type: 'ANALYZE_ASSET_VISUAL',
    payload: { schemaVersion: 'ASSET_VISUAL_ANALYSIS_V1', snapshotId: snapshot.id, assetId: item.assetId, analysisConfig },
    idempotencyKey: `analyze-asset-visual:${snapshot.id}:${item.assetId}:${analysisConfig}`,
    maxAttempts: 3,
  })));
  return { configured: true, queued: eligible.length, eligible: eligible.length };
}

async function enqueueRepresentativeFrameJobs(
  snapshot: Awaited<ReturnType<ScriptEditingV3Service['getSnapshot']>>,
  jobs: JobService,
): Promise<number> {
  const eligible = snapshot.items.filter((item) => item.availability === 'VALID' && !item.disabled);
  if (qwenConfigured()) return 0;
  await Promise.all(eligible.map((item) => jobs.createIdempotent({
    id: `job-${randomUUID()}`,
    projectId: null,
    workspaceId: snapshot.workspaceId,
    type: 'GENERATE_REPRESENTATIVE_FRAMES',
    payload: { schemaVersion: 'REPRESENTATIVE_FRAMES_V1', snapshotId: snapshot.id, assetId: item.assetId },
    idempotencyKey: `generate-representative-frames:${snapshot.id}:${item.assetId}`,
    maxAttempts: 3,
  })));
  return eligible.length;
}

export function registerScriptEditingV3Routes(app: FastifyInstance, dependencies: { db: Pool; jobs: JobService; video: VideoService; assets: AssetService; localMedia: LocalMediaSourceService; localPathAccess?: LocalPathAccessService; storage?: LocalStorageProvider; jianyingRuntime?: JianyingRuntimeLocator }): void {
  const service = new ScriptEditingV3Service(dependencies.db, dependencies.storage ? { storage: dependencies.storage, hybridMedia: new HybridMediaService(dependencies.assets, dependencies.storage, createExternalVideoProvider(), dependencies.db) } : {});
  const evaluations = new ScriptEditingV3EvaluationService(dependencies.db);
  const jianyingRuntime = dependencies.jianyingRuntime || new JianyingRuntimeLocator();
  app.get('/api/v1/edit/v3/jianying/runtime', async (_request, reply) => {
    const status = await jianyingRuntime.getRuntimeStatus();
    return reply.send({
      platform: status.platform,
      helperConfigured: status.helper.configured,
      helperAvailable: status.helper.status === 'AVAILABLE',
      helperName: status.helper.path ? status.helper.path.split(/[\\/]/u).pop() : undefined,
      dllConfigured: status.dll.configured,
      dllAvailable: status.dll.status === 'AVAILABLE',
      dllName: status.dll.path ? status.dll.path.split(/[\\/]/u).pop() : undefined,
      encryptedDraftSupport: status.encryptedDraftSupport,
    });
  });
  app.post('/api/v1/edit/v3/scans', async (request, reply) => {
    const parsed = scanInput.safeParse(request.body || {}); if (!parsed.success) return reply.code(422).send({ error: { code: 'VALIDATION_ERROR', details: parsed.error.issues } });
    const input = parsed.data; const canonical = dependencies.localPathAccess ? await dependencies.localPathAccess.authorize(input.sourceRoot, 'MEDIA_ROOT') : input.sourceRoot; const rootId = sourceRootId(canonical); const key = `v3-material-scan:${input.workspaceId}:${rootId}:${input.recursive}`; const existing = await dependencies.jobs.getByIdempotencyKey(key); if (existing) return reply.code(202).send({ scanId: (existing.payload as { scanId?: string }).scanId, jobId: existing.id, state: existing.state, sourceRootId: rootId });
    await dependencies.db.query("insert into video_workspaces (id,type,project_id) values ($1,'STANDALONE',null) on conflict (id) do nothing", [input.workspaceId]);
    const scanId = `scan-${randomUUID()}`; await dependencies.localMedia.createScan({ id: scanId, workspaceId: input.workspaceId, sourceRoot: canonical, sourceRootId: rootId, recursive: input.recursive });
    const job = await dependencies.jobs.createIdempotent({ id: `job-${randomUUID()}`, projectId: null, workspaceId: input.workspaceId, type: 'LOCAL_MEDIA_SCAN', payload: { schemaVersion: 'LOCAL_MEDIA_SCAN_V1', workspaceId: input.workspaceId, scanId, sourceRoot: canonical, sourceRootId: rootId, recursive: input.recursive }, idempotencyKey: key, maxAttempts: 3 });
    return reply.code(202).send({ scanId, jobId: job.id, state: job.state, sourceRootId: rootId });
  });
  app.get('/api/v1/edit/v3/scans/:id', async (request, reply) => { const workspaceId = String((request.query as { workspaceId?: string } | undefined)?.workspaceId || ''); if (!workspaceId) return reply.code(422).send({ error: { code: 'WORKSPACE_REQUIRED' } }); const scan = await dependencies.localMedia.getScan(String((request.params as { id: string }).id), undefined, workspaceId); if (!scan) return reply.code(404).send({ error: { code: 'LOCAL_MEDIA_SCAN_NOT_FOUND' } }); return { id: scan.id, status: scan.status, progress: scan.progress, sourceRootId: scan.sourceRootId, files: scan.files.map(({ sourcePath: _sourcePath, ...file }) => file) }; });

  app.post('/api/v1/edit/v3/pool/snapshots', async (request, reply) => { const parsed = snapshotInput.safeParse(request.body || {}); if (!parsed.success) return reply.code(422).send({ error: { code: 'VALIDATION_ERROR', details: parsed.error.issues } }); try { await ensureStandaloneWorkspace(dependencies.db, parsed.data.workspaceId); const sourceFiles = await Promise.all(parsed.data.sourceFiles.map(async (sourceFile) => dependencies.localPathAccess ? dependencies.localPathAccess.authorize(sourceFile, 'PRIORITY_ASSET') : sourceFile)); for (const sourceFile of sourceFiles) if (!await access(sourceFile).then(() => true).catch(() => false)) throw new Error('LOCAL_MEDIA_FILE_NOT_FOUND'); const snapshot = await service.createMaterialPoolSnapshot({ ...parsed.data, sourceFiles }); const analysis = await enqueueVisualAnalysisJobs(snapshot, dependencies.jobs); const representativeFramesQueued = await enqueueRepresentativeFrameJobs(snapshot, dependencies.jobs); return reply.code(201).send({ ...publicSnapshot(snapshot), analysis, representativeFramesQueued }); } catch (error) { return reply.code(422).send({ error: { code: errorCode(error) } }); } });
  app.get('/api/v1/edit/v3/pool/snapshots/:id', async (request, reply) => { try { return publicSnapshot(await service.getSnapshot(String((request.params as { id: string }).id))); } catch (error) { return reply.code(404).send({ error: { code: errorCode(error) } }); } });
  app.get('/api/v1/edit/v3/pool/snapshots/:id/health', async (request, reply) => { try { return await service.getMaterialPoolHealth(String((request.params as { id: string }).id)); } catch (error) { return reply.code(404).send({ error: { code: errorCode(error) } }); } });
  app.post('/api/v1/edit/v3/pool/snapshots/:id/items/:assetId/shots', async (request, reply) => {
    const parsed = z.object({ threshold: z.number().min(0.05).max(0.95).default(0.35) }).safeParse(request.body || {});
    if (!parsed.success) return reply.code(422).send({ error: { code: 'VALIDATION_ERROR', details: parsed.error.issues } });
    const snapshotId = String((request.params as { id: string }).id); const assetId = String((request.params as { assetId: string }).assetId);
    try {
      const snapshot = await service.getSnapshot(snapshotId); const item = snapshot.items.find((candidate) => candidate.assetId === assetId);
      if (!item || !item.sourceFingerprint || !item.sourcePath || item.availability !== 'VALID') return reply.code(422).send({ error: { code: 'MATERIAL_NOT_AVAILABLE_FOR_SHOT_DETECTION' } });
      const detectorVersion = 'shot-detection-v1'; const existing = (await dependencies.db.query('select * from script_editing_v3_shot_detection_runs where snapshot_id=$1 and asset_id=$2 and source_fingerprint=$3 and detector_version=$4', [snapshotId, assetId, item.sourceFingerprint, detectorVersion])).rows[0] as Record<string, unknown> | undefined;
      if (existing?.status === 'SUCCEEDED') return { runId: String(existing.id), status: String(existing.status), cached: true };
      const runId = existing ? String(existing.id) : `shot-run-${randomUUID()}`;
      if (!existing) await dependencies.db.query('insert into script_editing_v3_shot_detection_runs (id,snapshot_id,asset_id,source_fingerprint,threshold,detector_version) values ($1,$2,$3,$4,$5,$6)', [runId, snapshotId, assetId, item.sourceFingerprint, parsed.data.threshold, detectorVersion]);
      const key = `shot-detection:${snapshotId}:${assetId}:${item.sourceFingerprint}:${parsed.data.threshold}`;
      const job = await dependencies.jobs.createIdempotent({ id: `job-${randomUUID()}`, projectId: null, workspaceId: snapshot.workspaceId, type: 'SHOT_DETECTION_V1', payload: { schemaVersion: 'SHOT_DETECTION_V1', runId, snapshotId, assetId, sourcePath: item.sourcePath, durationMs: item.durationMs, sourceFingerprint: item.sourceFingerprint, threshold: parsed.data.threshold }, idempotencyKey: key, maxAttempts: 2 });
      return reply.code(202).send({ runId, jobId: job.id, state: job.state, cached: false });
    } catch (error) { return reply.code(422).send({ error: { code: errorCode(error) } }); }
  });
  app.get('/api/v1/edit/v3/pool/snapshots/:id/items/:assetId/shots', async (request, reply) => { const snapshotId = String((request.params as { id: string }).id); const assetId = String((request.params as { assetId: string }).assetId); const result = await dependencies.db.query('select r.id,r.status,r.threshold,r.detector_version,r.error,s.shot_index,s.source_in_ms,s.source_out_ms,s.confidence,s.evidence from script_editing_v3_shot_detection_runs r left join script_editing_v3_shots s on s.run_id=r.id where r.snapshot_id=$1 and r.asset_id=$2 order by r.created_at desc,s.shot_index', [snapshotId, assetId]); const first = result.rows[0] as Record<string, unknown> | undefined; if (!first) return reply.code(404).send({ error: { code: 'SHOT_DETECTION_NOT_FOUND' } }); return { runId: String(first.id), status: String(first.status), threshold: Number(first.threshold), detectorVersion: String(first.detector_version), error: first.error || null, shots: result.rows.filter((row) => row.shot_index !== null).map((row) => ({ index: Number(row.shot_index), sourceInMs: Number(row.source_in_ms), sourceOutMs: Number(row.source_out_ms), confidence: Number(row.confidence), evidence: row.evidence || {} })) }; });
  app.post('/api/v1/edit/v3/pool/snapshots/:id/items/:assetId/relink', async (request, reply) => { const parsed = z.object({ sourcePath: z.string().trim().min(1), actor: z.string().trim().min(1).max(100).optional(), force: z.boolean().default(false) }).safeParse(request.body || {}); if (!parsed.success) return reply.code(422).send({ error: { code: 'VALIDATION_ERROR', details: parsed.error.issues } }); try { const path = dependencies.localPathAccess ? await dependencies.localPathAccess.authorize(parsed.data.sourcePath, 'PRIORITY_ASSET') : parsed.data.sourcePath; return await service.relinkMaterial(String((request.params as { id: string }).id), String((request.params as { assetId: string }).assetId), path, parsed.data.actor || 'operator', parsed.data.force); } catch (error) { return reply.code(422).send({ error: { code: errorCode(error) } }); } });
  app.get('/api/v1/edit/v3/pool/snapshots/:id/items/:assetId/relinks', async (request) => service.listRelinks(String((request.params as { id: string; assetId: string }).id), String((request.params as { id: string; assetId: string }).assetId)).then((items) => ({ items })));
  app.post('/api/v1/edit/v3/pool/snapshots/:id/items/:assetId/gold', async (request, reply) => { const parsed = goldInput.safeParse(request.body || {}); if (!parsed.success) return reply.code(422).send({ error: { code: 'VALIDATION_ERROR', details: parsed.error.issues } }); try { await service.setGold(String((request.params as { id: string; assetId: string }).id), String((request.params as { id: string; assetId: string }).assetId), parsed.data.gold); return { status: 'UPDATED', gold: parsed.data.gold }; } catch (error) { return reply.code(404).send({ error: { code: errorCode(error) } }); } });
  app.post('/api/v1/edit/v3/pool/snapshots/:id/items/:assetId/disabled', async (request, reply) => { const parsed = z.object({ disabled: z.boolean() }).safeParse(request.body || {}); if (!parsed.success) return reply.code(422).send({ error: { code: 'VALIDATION_ERROR', details: parsed.error.issues } }); try { await service.setDisabled(String((request.params as { id: string; assetId: string }).id), String((request.params as { id: string; assetId: string }).assetId), parsed.data.disabled); return { status: 'UPDATED', disabled: parsed.data.disabled }; } catch (error) { return reply.code(404).send({ error: { code: errorCode(error) } }); } });
  app.post('/api/v1/edit/v3/pool/snapshots/:id/items/:assetId/tags', async (request, reply) => { const parsed = manualTagsInput.safeParse(request.body || {}); if (!parsed.success) return reply.code(422).send({ error: { code: 'VALIDATION_ERROR', details: parsed.error.issues } }); try { const tags = await service.setManualTags(String((request.params as { id: string; assetId: string }).id), String((request.params as { id: string; assetId: string }).assetId), parsed.data.tags); return { status: 'UPDATED', tags }; } catch (error) { return reply.code(404).send({ error: { code: errorCode(error) } }); } });
   app.post('/api/v1/edit/v3/pool/snapshots/:id/analyze', async (request, reply) => { const snapshotId = String((request.params as { id: string }).id); const body = z.object({ assetId: z.string().trim().min(1) }).safeParse(request.body || {}); if (!body.success) return reply.code(422).send({ error: { code: 'VALIDATION_ERROR', details: body.error.issues } }); const snapshot = await service.getSnapshot(snapshotId).catch(() => null); if (!snapshot) return reply.code(404).send({ error: { code: 'MATERIAL_POOL_SNAPSHOT_NOT_FOUND' } }); const item = snapshot.items.find((candidate) => candidate.assetId === body.data.assetId); if (!item) return reply.code(404).send({ error: { code: 'MATERIAL_NOT_FOUND' } }); if (item.availability !== 'VALID' || item.disabled) return reply.code(422).send({ error: { code: 'MATERIAL_NOT_ELIGIBLE_FOR_ANALYSIS' } }); if (!qwenConfigured()) return reply.code(503).send({ error: { code: 'QWEN_PROVIDER_NOT_CONFIGURED' } }); const analysisConfig = visualAnalysisConfig(); const key = `analyze-asset-visual:${snapshotId}:${body.data.assetId}:${analysisConfig}`; const job = await dependencies.jobs.createIdempotent({ id: `job-${randomUUID()}`, projectId: null, workspaceId: snapshot.workspaceId, type: 'ANALYZE_ASSET_VISUAL', payload: { schemaVersion: 'ASSET_VISUAL_ANALYSIS_V1', snapshotId, assetId: body.data.assetId, analysisConfig }, idempotencyKey: key, maxAttempts: 3 }); return reply.code(202).send({ jobId: job.id, state: job.state }); });
  app.post('/api/v1/edit/v3/pool/snapshots/:id/analyze-all', async (request, reply) => { const snapshot = await service.getSnapshot(String((request.params as { id: string }).id)).catch(() => null); if (!snapshot) return reply.code(404).send({ error: { code: 'MATERIAL_POOL_SNAPSHOT_NOT_FOUND' } }); return reply.code(202).send({ snapshotId: snapshot.id, analysis: await enqueueVisualAnalysisJobs(snapshot, dependencies.jobs) }); });
  app.get('/api/v1/edit/v3/media/:assetId', async (request, reply) => { const query = request.query as { snapshotId?: string }; if (!query.snapshotId) return reply.code(422).send({ error: { code: 'SNAPSHOT_REQUIRED' } }); try { const snapshot = await service.getSnapshot(query.snapshotId); const assetId = String((request.params as { assetId: string }).assetId); const item = snapshot.items.find((candidate) => candidate.assetId === assetId); let sourcePath = item?.sourcePath; let fileName = item?.fileName || assetId; if (!sourcePath && dependencies.storage) { const row = (await dependencies.db.query('select a.storage_key,a.metadata from assets a join video_workspace_assets wa on wa.asset_id=a.id and wa.workspace_id=$1 and wa.role=\'SOURCE\' where a.id=$2 and a.lifecycle=\'READY\'', [snapshot.workspaceId, assetId])).rows[0] as { storage_key?: string; metadata?: Record<string, unknown> } | undefined; if (row?.storage_key) { sourcePath = dependencies.storage.objectPath(String(row.storage_key)); const metadata = row.metadata && typeof row.metadata === 'object' ? row.metadata : {}; fileName = typeof metadata.originalName === 'string' ? metadata.originalName : fileName; } } if (!sourcePath) return reply.code(404).send({ error: { code: 'MATERIAL_NOT_FOUND' } }); const details = await stat(sourcePath).catch(() => null); if (!details?.isFile()) return reply.code(404).send({ error: { code: 'MATERIAL_FILE_NOT_FOUND' } }); const mime = ({ mp4: 'video/mp4', mov: 'video/quicktime', m4v: 'video/mp4', webm: 'video/webm', mkv: 'video/x-matroska', avi: 'video/x-msvideo' } as Record<string, string>)[extname(fileName).slice(1).toLowerCase()] || 'video/mp4'; reply.header('accept-ranges', 'bytes').header('content-type', mime); const range = request.headers.range; if (!range) return reply.header('content-length', details.size).send(createReadStream(sourcePath)); const match = /^bytes=(\d*)-(\d*)$/u.exec(range); if (!match) return reply.code(416).send(); const start = match[1] ? Number(match[1]) : Math.max(0, details.size - Number(match[2] || 0)); const end = match[2] ? Number(match[2]) : details.size - 1; if (!Number.isInteger(start) || !Number.isInteger(end) || start < 0 || end < start || end >= details.size) return reply.code(416).header('content-range', `bytes */${details.size}`).send(); return reply.code(206).header('content-length', end - start + 1).header('content-range', `bytes ${start}-${end}/${details.size}`).send(createReadStream(sourcePath, { start, end })); } catch (error) { return reply.code(404).send({ error: { code: errorCode(error) } }); } });

  app.post('/api/v1/edit/v3/sessions', async (request, reply) => { const parsed = sessionInput.safeParse(request.body || {}); if (!parsed.success) return reply.code(422).send({ error: { code: 'VALIDATION_ERROR', details: parsed.error.issues } }); try { const input = parsed.data; await ensureStandaloneWorkspace(dependencies.db, input.workspaceId); const timingScript = input.sentences?.length ? input.sentences.map((sentence) => sentence.text).join('。') : input.script; const timing = input.voicePath ? await prepareVoiceTiming({ assetService: dependencies.assets, assets: new AssetCatalogService(dependencies.db) }, { workspaceId: input.workspaceId, script: timingScript, voicePath: input.voicePath }) : undefined; let cursor = 0; const sentences = timing?.sentences.map((sentence, index) => { const durationMs = Number(sentence.durationMs || 3_000); const startMs = sentence.voiceStartMs ?? cursor; const endMs = sentence.voiceEndMs ?? startMs + durationMs; cursor = Math.max(cursor, endMs); return { text: input.sentences?.[index]?.text || sentence.text, startMs, endMs, durationMs: endMs - startMs }; }) || input.sentences; const { presentationSettings, template, pace, shotDensity, subtitleStyle, audioPlan, brandingPlan, usePexels, ...session } = input; const settings = { ...(presentationSettings ? { presentationSettings } : {}), ...(template ? { template } : {}), ...(pace ? { pace } : {}), ...(shotDensity ? { shotDensity } : {}), ...(subtitleStyle ? { subtitleStyle } : {}), ...(audioPlan ? { audioPlan } : {}), ...(brandingPlan ? { brandingPlan } : {}), ...(usePexels !== undefined ? { usePexels } : {}) }; return reply.code(201).send(await service.createSession({ ...session, ...(Object.keys(settings).length ? { settings } : {}), ...(sentences ? { sentences } : {}) })); } catch (error) { return reply.code(422).send({ error: { code: errorCode(error) } }); } });
  app.get('/api/v1/edit/v3/sessions/:id', async (request, reply) => { try { return publicSession(await service.getSession(String((request.params as { id: string }).id))); } catch (error) { return reply.code(404).send({ error: { code: errorCode(error) } }); } });
  app.post('/api/v1/edit/v3/sessions/:id/generate', async (request, reply) => { try { return reply.code(201).send(await service.generate(String((request.params as { id: string }).id))); } catch (error) { return reply.code(422).send({ error: { code: errorCode(error) } }); } });
  app.post('/api/v1/edit/v3/sessions/:id/operations', async (request, reply) => { const parsed = operationInput.safeParse(request.body || {}); if (!parsed.success) return reply.code(422).send({ error: { code: 'VALIDATION_ERROR', details: parsed.error.issues } }); try { return reply.code(201).send(await service.applyOperation(String((request.params as { id: string }).id), parsed.data)); } catch (error) { const code = errorCode(error); return reply.code(code.includes('LOCKED') ? 409 : 422).send({ error: { code } }); } });
  app.get('/api/v1/edit/v3/sessions/:id/revisions', async (request, reply) => { try { return { items: await service.listRevisionHistory(String((request.params as { id: string }).id)) }; } catch (error) { return reply.code(404).send({ error: { code: errorCode(error) } }); } });
  app.post('/api/v1/edit/v3/sessions/:id/revisions/:action', async (request, reply) => { const parsed = z.object({ targetManifestId: z.string().trim().min(1).optional(), reason: z.string().trim().max(500).optional() }).safeParse(request.body || {}); if (!parsed.success) return reply.code(422).send({ error: { code: 'VALIDATION_ERROR', details: parsed.error.issues } }); const action = String((request.params as { action: string }).action).toUpperCase(); if (!['UNDO', 'REDO', 'RESTORE'].includes(action)) return reply.code(404).send({ error: { code: 'REVISION_ACTION_NOT_FOUND' } }); try { return await service.changeRevision(String((request.params as { id: string }).id), action as 'UNDO' | 'REDO' | 'RESTORE', parsed.data.targetManifestId, parsed.data.reason); } catch (error) { return reply.code(409).send({ error: { code: errorCode(error) } }); } });
  app.post('/api/v1/edit/v3/sessions/:id/render', async (request, reply) => { const id = String((request.params as { id: string }).id); const row = (await dependencies.db.query('select workspace_id,current_manifest_id,revision from script_editing_v3_sessions where id=$1', [id])).rows[0] as { workspace_id?: string; current_manifest_id?: string; revision?: number } | undefined; if (!row?.workspace_id || !row.current_manifest_id) return reply.code(409).send({ error: { code: 'SCRIPT_EDITING_V3_MANIFEST_NOT_READY' } }); const job = await dependencies.video.createManifestRenderJobForWorkspace(row.workspace_id, row.current_manifest_id, `script-editing-v3:${id}:revision:${Number(row.revision || 1)}`); await dependencies.db.query("update script_editing_v3_sessions set status='RENDERING',updated_at=now() where id=$1", [id]); return reply.code(202).send({ jobId: job.id, manifestId: row.current_manifest_id, status: 'RENDERING' }); });
  app.post('/api/v1/edit/v3/sessions/:id/preview', async (request, reply) => {
    const mode = String((request.body as { mode?: string } | undefined)?.mode || 'DRAFT').toUpperCase();
    if (!['DRAFT', 'FAST'].includes(mode)) return reply.code(422).send({ error: { code: 'PREVIEW_MODE_INVALID' } });
    const id = String((request.params as { id: string }).id);
    const session = (await dependencies.db.query('select workspace_id,current_manifest_id,material_pool_snapshot_id from script_editing_v3_sessions where id=$1', [id])).rows[0] as { workspace_id?: string; current_manifest_id?: string; material_pool_snapshot_id?: string } | undefined;
    if (!session?.workspace_id || !session.current_manifest_id || !session.material_pool_snapshot_id) return reply.code(409).send({ error: { code: 'SCRIPT_EDITING_V3_MANIFEST_NOT_READY' } });
    const manifest = (await dependencies.db.query<{ manifest: { timeline?: Array<{ assetId: string; sourceInMs: number; sourceOutMs?: number; durationMs: number; sentenceId?: string; role?: string }> } }>('select manifest from edit_manifests where id=$1 and workspace_id=$2', [session.current_manifest_id, session.workspace_id])).rows[0]?.manifest;
    if (!manifest) return reply.code(404).send({ error: { code: 'SCRIPT_EDITING_V3_MANIFEST_NOT_FOUND' } });
    const snapshot = await service.getSnapshot(session.material_pool_snapshot_id);
    const fragments = [];
    for (const [index, clip] of (manifest.timeline || []).filter((candidate) => candidate.role !== 'INTRO' && candidate.role !== 'OUTRO').entries()) {
      const item = snapshot.items.find((candidate) => candidate.assetId === clip.assetId); if (!item?.sourceFingerprint) continue;
      const key = `${mode.toLowerCase()}-${index}-${clip.sentenceId || clip.assetId}`;
      await dependencies.db.query('insert into script_editing_v3_preview_fragments (id,workspace_id,manifest_id,fragment_key,source_fingerprint,source_in_ms,source_out_ms,output_path,status,metadata) values ($1,$2,$3,$4,$5,$6,$7,null,\'READY\',$8) on conflict (manifest_id,fragment_key,source_fingerprint,source_in_ms,source_out_ms) do update set updated_at=now()', [`preview-fragment-${randomUUID()}`, session.workspace_id, session.current_manifest_id, key, item.sourceFingerprint, clip.sourceInMs, clip.sourceOutMs || clip.sourceInMs + clip.durationMs, JSON.stringify({ mode, sentenceId: clip.sentenceId || null })]);
      fragments.push({ key, assetId: clip.assetId, sourceInMs: clip.sourceInMs, sourceOutMs: clip.sourceOutMs || clip.sourceInMs + clip.durationMs, durationMs: clip.durationMs, sentenceId: clip.sentenceId || null, url: `/api/v1/edit/v3/media/${encodeURIComponent(clip.assetId)}?snapshotId=${encodeURIComponent(session.material_pool_snapshot_id)}` });
    }
    return { mode, manifestId: session.current_manifest_id, cached: true, fragments };
  });
  app.get('/api/v1/edit/v3/sessions/:id/rendered', async (request, reply) => { if (!dependencies.storage) return reply.code(503).send({ error: { code: 'STORAGE_UNAVAILABLE' } }); const id = String((request.params as { id: string }).id); const row = (await dependencies.db.query('select a.storage_key from script_editing_v3_sessions s join renders r on r.manifest_id=s.current_manifest_id and r.status=\'SUCCEEDED\' join assets a on a.id=r.output_asset_id where s.id=$1 order by r.finished_at desc nulls last limit 1', [id])).rows[0] as { storage_key?: string } | undefined; if (!row?.storage_key) return reply.code(404).send({ error: { code: 'V3_RENDER_NOT_READY' } }); const path = dependencies.storage.objectPath(row.storage_key); const details = await stat(path).catch(() => null); if (!details?.isFile()) return reply.code(404).send({ error: { code: 'V3_RENDER_FILE_NOT_FOUND' } }); return reply.header('content-type', 'video/mp4').header('content-length', details.size).send(createReadStream(path)); });

  app.get('/api/v1/edit/v3/evaluation-sets', async (request) => { const workspaceId = String((request.query as { workspaceId?: string }).workspaceId || ''); if (!workspaceId) return { items: [] }; return { items: await evaluations.list(workspaceId) }; });
  app.get('/api/v1/edit/v3/evaluation-sets/:id', async (request, reply) => { const value = await evaluations.get(String((request.params as { id: string }).id)); return value ? value : reply.code(404).send({ error: { code: 'EVALUATION_SET_NOT_FOUND' } }); });
  app.get('/api/v1/edit/v3/evaluation-sets/:id/export', async (request, reply) => { const value = await evaluations.get(String((request.params as { id: string }).id)); if (!value) return reply.code(404).send({ error: { code: 'EVALUATION_SET_NOT_FOUND' } }); const format = String((request.query as { format?: string }).format || 'json').toLowerCase(); if (format !== 'csv') return reply.header('content-type', 'application/json; charset=utf-8').send(value); const rows = [['type', 'id', 'visualNeed', 'usableAssetIds', 'forbiddenAssetIds', 'assetId', 'fileName', 'label', 'reason', 'annotator'], ...value.items.map((item) => ['ITEM', '', '', '', '', String((item as { assetId: string }).assetId), String((item as { fileName: string }).fileName), '', '', '']), ...value.queries.map((query) => ['QUERY', String((query as { id: string }).id), String((query as { visualNeed: string }).visualNeed), JSON.stringify((query as { usableAssetIds: string[] }).usableAssetIds), JSON.stringify((query as { forbiddenAssetIds: string[] }).forbiddenAssetIds || []), '', '', '', '', '']), ...value.judgments.map((judgment) => ['JUDGMENT', String((judgment as { queryId: string }).queryId), '', '', '', String((judgment as { assetId: string }).assetId), '', String((judgment as { label: string }).label), String((judgment as { reason?: string | null }).reason || ''), String((judgment as { annotator: string }).annotator)])]; return reply.header('content-type', 'text/csv; charset=utf-8').send(rows.map((row) => row.map(csvCell).join(',')).join('\n')); });
  app.post('/api/v1/edit/v3/evaluation-sets/import-csv', async (request, reply) => { const workspaceId = String((request.query as { workspaceId?: string }).workspaceId || ''); const name = String((request.query as { name?: string }).name || 'Imported CSV'); const text = typeof request.body === 'string' ? request.body : String((request.body as { csv?: string } | undefined)?.csv || ''); if (!workspaceId || !text.trim()) return reply.code(422).send({ error: { code: 'CSV_IMPORT_INPUT_REQUIRED' } }); const lines = text.split(/\r?\n/u).filter(Boolean).slice(1).map(parseCsvLine); const items = new Map<string, { assetId: string; fileName: string }>(); const queries = new Map<string, { id: string; visualNeed: string; usableAssetIds: string[]; forbiddenAssetIds: string[] }>(); for (const row of lines) { const type = row[0]; if (type === 'ITEM' && row[5]) items.set(row[5], { assetId: row[5], fileName: row[6] || row[5] }); if (type === 'QUERY' && row[1]) queries.set(row[1], { id: row[1], visualNeed: row[2] || row[1], usableAssetIds: JSON.parse(row[3] || '[]') as string[], forbiddenAssetIds: JSON.parse(row[4] || '[]') as string[] }); } try { return reply.code(201).send(await evaluations.importSet({ workspaceId, name, items: [...items.values()], queries: [...queries.values()] })); } catch (error) { return reply.code(422).send({ error: { code: errorCode(error) } }); } });
  app.post('/api/v1/edit/v3/evaluation-sets/:id/judgments', async (request, reply) => { const parsed = evaluationJudgmentInput.safeParse(request.body || {}); if (!parsed.success) return reply.code(422).send({ error: { code: 'VALIDATION_ERROR', details: parsed.error.issues } }); try { return await evaluations.judge({ setId: String((request.params as { id: string }).id), ...parsed.data }); } catch (error) { return reply.code(422).send({ error: { code: errorCode(error) } }); } });
  app.post('/api/v1/edit/v3/evaluation-sets/import', async (request, reply) => { const parsed = evaluationImportInput.safeParse(request.body || {}); if (!parsed.success) return reply.code(422).send({ error: { code: 'VALIDATION_ERROR', details: parsed.error.issues } }); try { const input = parsed.data; return reply.code(201).send(await evaluations.importSet({ workspaceId: input.workspaceId, name: input.name, ...(input.snapshotId ? { snapshotId: input.snapshotId } : {}), ...(input.idempotencyKey ? { idempotencyKey: input.idempotencyKey } : {}), items: input.items, queries: input.queries, ...(input.judgments ? { judgments: input.judgments } : {}) })); } catch (error) { return reply.code(422).send({ error: { code: errorCode(error) } }); } });

  app.post('/api/v1/edit/v3/jianying/import', async (request, reply) => { const parsed = jianyingInput.safeParse(request.body || {}); if (!parsed.success) return reply.code(422).send({ error: { code: 'VALIDATION_ERROR', details: parsed.error.issues } }); try { await ensureStandaloneWorkspace(dependencies.db, parsed.data.workspaceId); const paths = [...new Set([...(parsed.data.draftPath ? [parsed.data.draftPath] : []), ...(parsed.data.draftPaths || [])])]; const authorizedPaths = []; for (const draftPath of paths) { const path = dependencies.localPathAccess ? await dependencies.localPathAccess.authorize(draftPath, 'JIANYING_DRAFT') : draftPath; if (!await access(path).then(() => true).catch(() => false)) throw new Error('JIANYING_DRAFT_NOT_FOUND'); authorizedPaths.push(path); } const digest = createHash('sha256').update(`${parsed.data.workspaceId}:${authorizedPaths.join('\0')}`).digest('hex'); const key = `jianying-import:${parsed.data.workspaceId}:${digest}`; const existing = await dependencies.jobs.getByIdempotencyKey(key); if (existing) return reply.code(202).send({ jobId: existing.id, state: existing.state }); const job = await dependencies.jobs.createIdempotent({ id: `job-${randomUUID()}`, projectId: null, workspaceId: parsed.data.workspaceId, type: 'IMPORT_JIANYING_DRAFT', payload: { schemaVersion: 'JIANYING_DRAFT_IMPORT_V1', workspaceId: parsed.data.workspaceId, draftPaths: authorizedPaths }, idempotencyKey: key, maxAttempts: 3 }); return reply.code(202).send({ jobId: job.id, state: job.state }); } catch (error) { return reply.code(422).send({ error: { code: errorCode(error) } }); } });
}
