'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';

type Candidate = { assetId: string; recommendedSourceInMs: number; finalScore: number };
type Item = { assetId: string; fileName: string; durationMs: number; tags: string[] };
type Card = { sentenceId: string; index: number; text: string; startMs: number; endMs: number; clip: { assetId: string; sourceInMs: number; sourceOutMs: number; durationMs: number; locked: boolean } | null; asset?: Item; candidates: Candidate[] };
type Session = { id: string; snapshotId: string; revision: number; status: string; manifestId?: string; cards: Card[] };
const seconds = (ms: number) => `${(ms / 1000).toFixed(2)}s`;

export default function ScriptEditingV3Page() {
  const [workspaceId] = useState(() => typeof window === 'undefined' ? 'workspace-v3' : window.localStorage.getItem('contentos-v3-workspace') || 'workspace-v3');
  const [script, setScript] = useState('越来越多消费者开始走进这些低价门店。顾客在货架区域挑选商品。');
  const [sourceRoot, setSourceRoot] = useState('');
  const [scan, setScan] = useState<{ id: string; state: string; sourceRootId?: string } | null>(null);
  const [snapshotId, setSnapshotId] = useState('');
  const [pool, setPool] = useState<Item[]>([]);
  const [session, setSession] = useState<Session | null>(null);
  const [message, setMessage] = useState('');
  const [busy, setBusy] = useState(false);
  const [renderUrl, setRenderUrl] = useState('');
  const refreshSession = async (id = session?.id) => { if (!id) return; const response = await fetch(`/api/v1/edit/v3/sessions/${encodeURIComponent(id)}`); if (response.ok) setSession(await response.json() as Session); };
  useEffect(() => { if (!scan || scan.state === 'SUCCEEDED' || scan.state === 'FAILED') return; const timer = window.setInterval(async () => { const response = await fetch(`/api/v1/edit/v3/scans/${encodeURIComponent(scan.id)}?workspaceId=${encodeURIComponent(workspaceId)}`); if (!response.ok) return; const next = await response.json() as { id: string; status: string; sourceRootId: string }; setScan({ id: next.id, state: next.status, sourceRootId: next.sourceRootId }); }, 1200); return () => window.clearInterval(timer); }, [scan, workspaceId]);
  const startScan = async () => { setBusy(true); try { const response = await fetch('/api/v1/edit/v3/scans', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ workspaceId, sourceRoot }) }); const data = await response.json() as { scanId?: string; state?: string; sourceRootId?: string; error?: { code?: string } }; if (!response.ok || !data.scanId) throw new Error(data.error?.code || '素材扫描失败'); setScan({ id: data.scanId, state: data.state || 'QUEUED', sourceRootId: data.sourceRootId }); setMessage('素材已进入后台扫描；完成后点击“固定素材池快照”。'); } catch (error) { setMessage(error instanceof Error ? error.message : '素材扫描失败'); } finally { setBusy(false); } };
  const createSnapshot = async () => { if (!scan?.sourceRootId || scan.state !== 'SUCCEEDED') { setMessage('请等待素材扫描完成。'); return; } setBusy(true); try { const response = await fetch('/api/v1/edit/v3/pool/snapshots', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ workspaceId, sourceRootIds: [scan.sourceRootId] }) }); const data = await response.json() as { id?: string; items?: Item[]; error?: { code?: string } }; if (!response.ok || !data.id) throw new Error(data.error?.code || '素材池快照创建失败'); setSnapshotId(data.id); setPool(data.items || []); setMessage(`已固定素材池快照，共 ${data.items?.length || 0} 个素材。`); } catch (error) { setMessage(error instanceof Error ? error.message : '素材池快照创建失败'); } finally { setBusy(false); } };
  const createSession = async () => { if (!snapshotId || !script.trim()) return; setBusy(true); try { const response = await fetch('/api/v1/edit/v3/sessions', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ workspaceId, snapshotId, script }) }); const data = await response.json() as { id?: string; error?: { code?: string } }; if (!response.ok || !data.id) throw new Error(data.error?.code || 'Workbench 创建失败'); setSession({ id: data.id, snapshotId, revision: 1, status: 'DRAFT', cards: [] }); setMessage('文案已生成视觉查询，点击“生成首版方案”。'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Workbench 创建失败'); } finally { setBusy(false); } };
  const generate = async () => { if (!session) return; setBusy(true); const response = await fetch(`/api/v1/edit/v3/sessions/${session.id}/generate`, { method: 'POST' }); if (!response.ok) setMessage('当前素材池没有满足句子时长的候选素材。'); else { await refreshSession(session.id); setMessage('首版方案已生成，下面可以逐句换镜头、Trim 或锁定。'); } setBusy(false); };
  const operation = async (body: Record<string, unknown>, success: string) => { if (!session) return; const response = await fetch(`/api/v1/edit/v3/sessions/${session.id}/operations`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const data = await response.json() as { error?: { code?: string } }; if (!response.ok) { setMessage(data.error?.code || '编辑操作失败'); return; } await refreshSession(session.id); setMessage(success); };
  const render = async () => { if (!session?.manifestId) return; const response = await fetch(`/api/v1/edit/v3/sessions/${session.id}/render`, { method: 'POST' }); const data = await response.json() as { jobId?: string; error?: { code?: string } }; if (!response.ok || !data.jobId) { setMessage(data.error?.code || '渲染任务创建失败'); return; } setMessage('整片渲染已进入 durable Job；正在等待成片…'); for (let attempt = 0; attempt < 90; attempt += 1) { await new Promise((resolve) => window.setTimeout(resolve, 1000)); const jobResponse = await fetch(`/api/v1/jobs/${data.jobId}`); const job = jobResponse.ok ? await jobResponse.json() as { state: string } : null; if (job?.state === 'SUCCEEDED') { setRenderUrl(`/api/v1/edit/v3/sessions/${session.id}/rendered`); setMessage('整片已完成，可以在下方播放。'); break; } if (job?.state === 'FAILED' || job?.state === 'BLOCKED') { setMessage('渲染失败，请查看任务状态。'); break; } } };
  return <main className="shell"><header className="page-header"><p className="eyebrow">剪辑 / Script Editing V3 Unified</p><div className="page-header-row"><div><h1>Sentence Editing Workbench</h1><p className="muted">每个文案段落对应一个真实视频 Clip。素材池在生成方案时固定，人工操作只影响当前句子。</p></div><Link className="module-nav-link" href="/edit">返回剪辑首页</Link></div></header>
    <section className="card"><h2>1. 固定本次素材池</h2><div className="inline-field"><input value={sourceRoot} onChange={(event) => setSourceRoot(event.target.value)} placeholder="输入已授权的素材文件夹路径" /><button type="button" onClick={() => void startScan()} disabled={busy || !sourceRoot.trim()}>扫描素材</button></div>{scan && <p className="muted">扫描状态：{scan.state} {scan.sourceRootId ? `· ${scan.sourceRootId}` : ''}</p>}<button type="button" onClick={() => void createSnapshot()} disabled={busy || scan?.state !== 'SUCCEEDED'}>固定素材池快照</button>{snapshotId && <p className="muted">Snapshot：{snapshotId} · {pool.length} 个素材</p>}</section>
    <section className="card"><h2>2. 文案确认</h2><textarea value={script} onChange={(event) => setScript(event.target.value)} rows={5} /><div className="entry-actions"><button type="button" onClick={() => void createSession()} disabled={busy || !snapshotId || !script.trim()}>创建 Workbench</button><button type="button" onClick={() => void generate()} disabled={busy || !session}>生成首版方案</button></div>{message && <p className="status">{message}</p>}</section>
    {session && <section className="card"><div className="section-title"><h2>3. Sentence Editing Cards</h2><span>revision {session.revision}</span></div>{session.cards.length === 0 ? <p className="muted">尚未生成方案。</p> : session.cards.map((card) => <article className="card" key={card.sentenceId}><div className="page-header-row"><div><strong>{String(card.index + 1).padStart(2, '0')} · {card.text}</strong><p className="muted">{seconds(card.startMs)} → {seconds(card.endMs)} · 句子时长 {seconds(card.endMs - card.startMs)}</p></div><button type="button" onClick={() => void operation({ type: card.clip?.locked ? 'UNLOCK_CLIP' : 'LOCK_CLIP', sentenceId: card.sentenceId }, card.clip?.locked ? '已解锁当前 Clip' : '已锁定当前 Clip')}>{card.clip?.locked ? '解锁' : '锁定'}</button></div>{card.clip && <><video controls preload="metadata" className="history-preview" src={`/api/v1/edit/v3/media/${encodeURIComponent(card.clip.assetId)}?snapshotId=${encodeURIComponent(session.snapshotId)}`} /><p className="muted">{card.asset?.fileName || card.clip.assetId} · Source {seconds(card.clip.sourceInMs)} → {seconds(card.clip.sourceOutMs)} · {card.clip.locked ? '已锁定' : '未锁定'}</p><div className="entry-actions">{card.candidates.map((candidate) => <button type="button" key={candidate.assetId} onClick={() => void operation({ type: 'REPLACE_CLIP', sentenceId: card.sentenceId, assetId: candidate.assetId, sourceInMs: candidate.recommendedSourceInMs }, `已将当前句子替换为候选 ${candidate.assetId}`)}>候选 {candidate.assetId.slice(-8)} · {candidate.finalScore}</button>)}<button type="button" onClick={() => void operation({ type: 'TRIM_SOURCE', sentenceId: card.sentenceId, sourceInMs: card.clip!.sourceInMs, sourceOutMs: card.clip!.sourceInMs + card.clip!.durationMs }, '已保存当前 Source 区间')}>保存当前 Trim</button></div></>}</article>)}</section>}
    {session?.manifestId && <section className="card"><div className="page-header-row"><div><h2>4. Full Video Preview</h2><p className="muted">渲染执行现有 immutable EditManifest；Renderer 不会重新选素材。</p></div><button type="button" onClick={() => void render()}>渲染整片</button></div>{renderUrl && <video controls className="history-preview" src={renderUrl} />}</section>}
  </main>;
}
