import { randomUUID } from 'node:crypto';
import { appendFile, mkdir } from 'node:fs/promises';
import { createServer, type IncomingMessage, type ServerResponse } from 'node:http';
import { resolve } from 'node:path';
import { createServiceDefinitions } from './service-definitions.js';
import { assertPortAvailable, isPortOpen, ProcessManager, RestartBudget, resolveRuntimePaths, RuntimeStateStore, ServiceRegistry, type DoctorReport, type HealthResult, type RuntimeLog, type RuntimeResult, type RuntimeStateFile, type RuntimeStatus, type ServiceDefinition, type ServiceState, type ServiceStatus } from '../../../packages/runtime-core/src/index.js';
import { runDoctor } from '../../../packages/runtime-core/src/index.js';

export interface RuntimeHostOptions { safeMode?: boolean; env?: Record<string, string | undefined>; }
const now = () => new Date().toISOString();
const errorValue = (error: unknown) => ({ code: typeof (error as { code?: unknown }).code === 'string' ? String((error as { code: string }).code) : 'RUNTIME_ERROR', message: error instanceof Error ? error.message : String(error) });

export class RuntimeHost {
  readonly paths: ReturnType<typeof resolveRuntimePaths>; readonly store: RuntimeStateStore; readonly instanceId = randomUUID(); readonly controlPort: number; readonly registry = new ServiceRegistry();
  private readonly processes: ProcessManager; private readonly statuses = new Map<string, ServiceStatus>(); private readonly budgets = new Map<string, RestartBudget>(); private readonly env: Record<string, string | undefined>; private server: ReturnType<typeof createServer> | undefined; private state: RuntimeStateFile; private stopping = false; private monitor: NodeJS.Timeout | undefined; private readonly logs: RuntimeLog[] = [];
  constructor(options: RuntimeHostOptions = {}) {
    const baseEnv = { ...process.env, ...(options.env || {}) };
    const appRoot = baseEnv.CONTENTOS_APP_ROOT || resolveRuntimePaths(baseEnv).appRoot;
    this.env = { ...baseEnv, CONTENTOS_APP_ROOT: appRoot, DATABASE_URL: baseEnv.DATABASE_URL || 'postgresql://contentos_dev:change-me@127.0.0.1:55433/contentos_operator_dev', STORAGE_ROOT: baseEnv.STORAGE_ROOT || resolve(appRoot, 'storage', 'local') };
    this.paths = resolveRuntimePaths(this.env); this.store = new RuntimeStateStore(this.paths); this.controlPort = Number(this.env.CONTENTOS_RUNTIME_CONTROL_PORT || 3099); this.processes = new ProcessManager(this.paths);
    const definitions = createServiceDefinitions({ appRoot: this.paths.appRoot, env: this.env, safeMode: options.safeMode === true }); for (const item of definitions) { this.registry.register(item); this.budgets.set(item.id, new RestartBudget(item.restartPolicy)); this.statuses.set(item.id, { id: item.id, label: item.label, required: item.required, kind: item.kind, state: 'STOPPED', ...(item.port ? { port: item.port } : {}), dependsOn: item.dependsOn, restartCount: 0, updatedAt: now() }); }
    this.state = { instanceId: this.instanceId, hostPid: process.pid, startedAt: now(), controlPort: this.controlPort, controlToken: randomUUID(), state: 'STOPPED', services: this.snapshotServices(), warnings: [] };
  }
  private log(serviceId: string, level: RuntimeLog['level'], event: string, message: string): void { const item = { timestamp: now(), serviceId, level, event, message }; this.logs.push(item); if (this.logs.length > 500) this.logs.shift(); void mkdir(this.paths.logsRoot, { recursive: true }).then(() => appendFile(resolve(this.paths.logsRoot, 'runtime-host.log'), JSON.stringify(item) + '\n', 'utf8')); }
  private snapshotServices(): ServiceStatus[] { return [...this.statuses.values()].map((item) => ({ ...item, dependsOn: [...item.dependsOn], ...(item.capability ? { capability: { ...item.capability } } : {}) })); }
  private async persist(state: RuntimeStateFile['state'] = this.state.state, warnings = this.state.warnings): Promise<void> { this.state = { ...this.state, state, services: this.snapshotServices(), warnings: [...warnings] }; await this.store.write(this.state); }
  private async acquire(): Promise<void> { const existing = await this.store.read(); if (existing) { if (await isPortOpen(existing.controlPort)) throw Object.assign(new Error('ContentOS already running'), { code: 'RUNTIME_ALREADY_RUNNING' }); await this.store.remove(); } await this.store.acquire({ instanceId: this.instanceId, hostPid: process.pid, controlPort: this.controlPort }); }
  private setState(id: string, state: ServiceState, extra: Partial<ServiceStatus> = {}): void { const current = this.statuses.get(id); if (!current) return; this.statuses.set(id, { ...current, state, ...extra, updatedAt: now() }); }
  private async runHealth(definition: ServiceDefinition): Promise<HealthResult> { if (definition.healthCheck) return definition.healthCheck(); if (definition.kind === 'PROCESS') return this.processes.get(definition.id) ? { state: 'READY', message: 'Process alive' } : { state: 'FAILED', message: 'Process is not running' }; return { state: 'READY' }; }
  private async waitReady(definition: ServiceDefinition): Promise<void> { const deadline = Date.now() + definition.startupTimeoutMs; let last: unknown; while (Date.now() < deadline) { try { const health = await this.runHealth(definition); if (health.state === 'READY' || health.state === 'DEGRADED') { this.setState(definition.id, health.state, health.capability ? { capability: health.capability } : {}); return; } last = health.message; if (health.state === 'FAILED' && definition.kind === 'PROCESS' && !this.processes.get(definition.id)) throw Object.assign(new Error(`${definition.id} process exited before readiness`), { code: 'SERVICE_PROCESS_EXITED' }); } catch (error) { if ((error as { code?: string }).code === 'SERVICE_PROCESS_EXITED') throw error; last = error; } await new Promise((resolveWait) => setTimeout(resolveWait, 250)); } throw Object.assign(new Error(`${definition.id} readiness timeout: ${last instanceof Error ? last.message : String(last || 'not ready')}`), { code: 'SERVICE_READINESS_TIMEOUT' }); }
  private async startDefinition(definition: ServiceDefinition): Promise<void> { this.setState(definition.id, 'STARTING'); await this.persist('STARTING'); try { if (definition.port) await assertPortAvailable(definition.port, definition.id); if (definition.start) await definition.start(); if (definition.command) { const child = await this.processes.start(definition.id, definition.command, definition.args || [], { ...this.env, ...(definition.env || {}), CONTENTOS_SKIP_MIGRATIONS: '1', STORAGE_ROOT: this.env.STORAGE_ROOT || this.paths.storageRoot }); this.setState(definition.id, 'STARTING', { ...(child.pid ? { pid: child.pid } : {}), startedAt: child.startedAt }); child.child.once('exit', (code, signal) => { if (!this.stopping && code !== 0) { this.log(definition.id, 'ERROR', 'PROCESS_EXIT', `exit=${code ?? 'null'} signal=${signal ?? 'null'}`); this.setState(definition.id, 'FAILED', { lastError: { code: 'PROCESS_EXIT', message: `exit=${code ?? 'null'}`, at: now() } }); void this.handleCrash(definition); } }); } await this.waitReady(definition); this.log(definition.id, 'INFO', 'READY', `${definition.label} ready`); await this.persist(this.state.state); } catch (error) { const value = errorValue(error); this.setState(definition.id, 'FAILED', { lastError: { ...value, at: now() } }); this.log(definition.id, 'ERROR', 'FAILED', value.message); await this.persist(this.state.state, [...this.state.warnings, `${definition.label}: ${value.message}`]); throw error; } }
  private async handleCrash(definition: ServiceDefinition): Promise<void> { if (!definition.command || !definition.restartClass || definition.restartClass === 'PERMANENT') return; const budget = this.budgets.get(definition.id); if (!budget || !budget.canRestart()) { this.setState(definition.id, 'FAILED', { lastError: { code: 'RESTART_BUDGET_EXHAUSTED', message: 'restart budget exhausted', at: now() } }); await this.persist(this.state.state, [...this.state.warnings, `${definition.label}: restart budget exhausted`]); return; } const delay = budget.consume(); this.setState(definition.id, 'STARTING', { restartCount: budget.count() }); await this.persist(this.state.state); setTimeout(() => { if (!this.stopping) void this.startDefinition(definition).catch(() => undefined); }, delay).unref(); }
  async start(): Promise<RuntimeStatus> { this.stopping = false; await mkdir(this.paths.runtimeRoot, { recursive: true }); await mkdir(this.paths.stateRoot, { recursive: true }); await mkdir(this.paths.logsRoot, { recursive: true }); await mkdir(this.paths.startupReportsRoot, { recursive: true }); await this.acquire(); this.state = { ...this.state, state: 'STARTING' }; await this.persist('STARTING'); const doctor = await runDoctor(this.paths, this.env); if (doctor.coreStartup !== 'READY') { this.state.warnings = doctor.checks.filter((item) => item.scope === 'CORE' && item.status === 'FAIL').map((item) => item.message); await this.persist('FAILED'); throw Object.assign(new Error('CORE_STARTUP_FAILED'), { code: 'CORE_STARTUP_FAILED', doctor }); } await this.listen(); const started = Date.now(); try { const startupWarnings: string[] = []; for (const definition of this.registry.topological(true)) { try { await this.startDefinition(definition); } catch (error) { if (definition.required) throw error; const message = `${definition.label}: ${error instanceof Error ? error.message : String(error)}`; startupWarnings.push(message); this.setState(definition.id, 'DEGRADED', { lastError: { code: 'OPTIONAL_START_FAILED', message, at: now() } }); this.log(definition.id, 'WARN', 'OPTIONAL_START_FAILED', message); } } const warnings = [...this.state.warnings, ...startupWarnings, ...doctor.checks.filter((item) => item.status !== 'PASS').map((item) => `${item.id}: ${item.message}`)]; await this.persist(warnings.length ? 'READY_WITH_WARNINGS' : 'READY', warnings); await this.writeStartupReport(Date.now() - started, doctor); this.monitor = setInterval(() => void this.refreshHealth(), 1_000); this.monitor.unref(); return this.status(); } catch (error) { await this.persist('FAILED', [...this.state.warnings, error instanceof Error ? error.message : String(error)]); await this.stop('startup-failed'); throw error; } }
  private async refreshHealth(): Promise<void> { for (const definition of this.registry.list(true)) { const current = this.statuses.get(definition.id); if (!current || current.state === 'STOPPED' || current.state === 'STOPPING') continue; try { const health = await this.runHealth(definition); this.setState(definition.id, health.state, health.capability ? { capability: health.capability } : {}); } catch (error) { this.setState(definition.id, 'DEGRADED', { lastError: { ...errorValue(error), at: now() } }); } } await this.persist(this.state.state); }
  private async listen(): Promise<void> { this.server = createServer((request, response) => void this.handleRequest(request, response)); await new Promise<void>((resolveListen, reject) => { this.server!.once('error', reject); this.server!.listen(this.controlPort, '127.0.0.1', () => resolveListen()); }); }
  private json(response: ServerResponse, status: number, payload: unknown): void { response.statusCode = status; response.setHeader('content-type', 'application/json'); response.end(JSON.stringify(payload)); }
  private authorized(request: IncomingMessage): boolean { return request.headers.authorization === `Bearer ${this.state.controlToken}`; }
  private async handleRequest(request: IncomingMessage, response: ServerResponse): Promise<void> { const url = new URL(request.url || '/', `http://127.0.0.1:${this.controlPort}`); try { if (url.pathname === '/runtime/status' && request.method === 'GET') return this.json(response, 200, this.status()); if (url.pathname === '/runtime/services' && request.method === 'GET') return this.json(response, 200, { items: this.snapshotServices() }); if (url.pathname === '/runtime/logs' && request.method === 'GET') { const serviceId = url.searchParams.get('serviceId'); const limit = Math.min(500, Number(url.searchParams.get('limit') || 100)); return this.json(response, 200, { items: this.logs.filter((item) => !serviceId || item.serviceId === serviceId).slice(-limit) }); } if (!this.authorized(request)) return this.json(response, 401, { error: { code: 'INVALID_CONTROL_TOKEN', message: 'Invalid runtime control token' } }); if (url.pathname === '/runtime/doctor' && request.method === 'POST') return this.json(response, 200, await runDoctor(this.paths, this.env)); if (url.pathname === '/runtime/stop' && request.method === 'POST') { this.json(response, 202, { ok: true, message: 'Runtime stopping' }); void this.stop('CONTROL'); return; } if (url.pathname === '/runtime/restart' && request.method === 'POST') { this.json(response, 202, { ok: true, message: 'Runtime restart scheduled' }); void this.stop('RESTART').then(() => this.start()).catch((error) => this.log('runtime-host', 'ERROR', 'RESTART_FAILED', error instanceof Error ? error.message : String(error))); return; } const match = /^\/runtime\/services\/([^/]+)\/restart$/.exec(url.pathname); if (match && request.method === 'POST') return this.json(response, 200, await this.restartService(decodeURIComponent(match[1]!))); return this.json(response, 404, { error: { code: 'RUNTIME_ROUTE_NOT_FOUND', message: 'Runtime route not found' } }); } catch (error) { const value = errorValue(error); return this.json(response, 500, { error: value }); } }
  async stop(reason = 'CLI'): Promise<RuntimeResult> { if (this.stopping) return { ok: true, message: 'Runtime stopping' }; this.stopping = true; await this.persist('STOPPING'); if (this.monitor) clearInterval(this.monitor); for (const definition of this.registry.reverse(true)) { this.setState(definition.id, 'STOPPING'); await this.persist('STOPPING'); if (definition.stop) await definition.stop().catch(() => undefined); await this.processes.stop(definition.id, definition.shutdownTimeoutMs).catch(() => undefined); this.setState(definition.id, 'STOPPED'); } if (this.server) await new Promise<void>((resolveClose) => this.server!.close(() => resolveClose())); await this.store.remove(); this.state = { ...this.state, state: 'STOPPED', warnings: [...this.state.warnings, `stopped:${reason}`] }; return { ok: true, message: 'ContentOS stopped' }; }
  async restartService(id: string): Promise<RuntimeResult> { const definition = this.registry.get(id); if (!definition) return { ok: false, message: `Unknown service: ${id}`, error: { code: 'SERVICE_NOT_FOUND', message: id } }; await this.processes.stop(id, definition.shutdownTimeoutMs); await this.startDefinition(definition); return { ok: true, message: `${id} restarted`, status: this.status() }; }
  status(): RuntimeStatus { return { instanceId: this.state.instanceId, hostPid: this.state.hostPid, state: this.state.state, startedAt: this.state.startedAt, uptimeMs: Math.max(0, Date.now() - Date.parse(this.state.startedAt)), controlPort: this.state.controlPort, services: this.snapshotServices(), warnings: [...this.state.warnings] }; }
  private async writeStartupReport(totalStartupMs: number, doctor: DoctorReport): Promise<void> { await mkdir(this.paths.startupReportsRoot, { recursive: true }); await import('node:fs/promises').then((fs) => fs.writeFile(resolve(this.paths.startupReportsRoot, `${this.instanceId}.json`), JSON.stringify({ timestamp: now(), instanceId: this.instanceId, appRoot: this.paths.appRoot, totalStartupMs, serviceStartupTimes: this.snapshotServices().map((item) => ({ id: item.id, startedAt: item.startedAt })), warnings: this.state.warnings, migration: this.statuses.get('migration')?.state, doctor }, null, 2), 'utf8')); }
}
