'use client';

import { useEffect, useMemo, useState } from 'react';
import { defaultPresentationSettings, PresentationSettingsPanel, type PresentationSettingsValue } from '../../_components/presentation-settings';

type Clip = { id: string; durationMs: number; selectedAssetId?: string; selectedSource?: string; asset?: { id: string; path: string; source: string; originalName?: string; author?: string; thumbnailUrl?: string }; locked?: boolean };
type Scene = { id: string; sceneIndex: number; text: string; role: string; startMs: number; endMs: number; clipSlots: Clip[] };
type Plan = { id: string; status: string; revision: number; outputRoot?: string; outputPath?: string; editorialPlan?: { scenes: Scene[]; sentences?: Array<{ text: string; durationMs?: number; voiceStartMs?: number; voiceEndMs?: number }>; totalDurationMs?: number }; resolvedPlan?: { scenes: Scene[]; sentences?: Array<{ text: string; durationMs?: number; voiceStartMs?: number; voiceEndMs?: number }>; totalDurationMs?: number; warnings?: string[] } };
const roleLabels: Record<string, string> = { HOOK: '开头', BODY: '正文', EXPLANATION: '解释', TURN: '转折', AUTHENTIC_ENTITY: '真实主体', EVIDENCE: '证据', CTA: '行动号召', ENDING: '结尾' };
const sourceLabels: Record<string, string> = { LOCAL: '本地', PEXELS: 'Pexels', FAKE_PEXELS: '网络模拟' };
function seconds(value: number): string { return `${(value / 1000).toFixed(1)}s`; }
function warningLabel(value: string): string { return value === 'EDIT_BGM_UNAVAILABLE' ? '未找到匹配的本地背景音乐，成片将不带音乐' : '部分可选素材暂不可用'; }
type ScriptSegment = { index: number; text: string; normalizedText: string };
function cleanAndSegmentScriptV1(input: string, segmentation: PresentationSettingsValue['segmentation']): { cleanedScript: string; segments: ScriptSegment[] } {
  const cleanedScript = input.normalize('NFKC').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g, '').replace(/[ \t]+/g, ' ').trim();
  const delimiters = segmentation.mode === 'SENTENCE_ONLY' ? ['。', '！', '!', '？', '?', '；', ';'] : segmentation.mode === 'CUSTOM' ? segmentation.delimiters || ['。'] : ['，', ',', '。', '！', '!', '？', '?', '；', ';'];
  const parts: string[] = []; let start = 0; let quote = false;
  for (let i = 0; i < cleanedScript.length; i += 1) { const char = cleanedScript[i]!; if (char === '"' || char === '“' || char === '”') quote = !quote; if (quote || !delimiters.includes(char)) continue; if ((char === '.' || char === ',') && /\d/.test(cleanedScript[i - 1] || '') && /\d/.test(cleanedScript[i + 1] || '')) continue; if (char === '.' && (cleanedScript.slice(start, i).includes('http://') || cleanedScript.slice(start, i).includes('https://'))) continue; const text = cleanedScript.slice(start, i + 1).trim(); if (text) parts.push(text); start = i + 1; }
  const tail = cleanedScript.slice(start).trim(); if (tail) parts.push(tail);
  return { cleanedScript, segments: parts.map((text, index) => ({ index, text, normalizedText: text.normalize('NFKC').toLowerCase() })) };
}
function mergeScriptSegmentsV1(items: ScriptSegment[], index: number): ScriptSegment[] { if (index < 0 || index >= items.length - 1) return items; const merged = `${items[index]!.text}${items[index + 1]!.text}`; return items.filter((_, itemIndex) => itemIndex !== index + 1).map((item, itemIndex) => itemIndex === index ? { ...item, text: merged, normalizedText: merged.normalize('NFKC').toLowerCase() } : { ...item, index: itemIndex }); }
function splitScriptSegmentV1(items: ScriptSegment[], index: number, at: number): ScriptSegment[] { const item = items[index]; if (!item || at <= 0 || at >= item.text.length) return items; const left = item.text.slice(0, at).trim(); const right = item.text.slice(at).trim(); if (!left || !right) return items; return [...items.slice(0, index), { index, text: left, normalizedText: left.normalize('NFKC').toLowerCase() }, { index: index + 1, text: right, normalizedText: right.normalize('NFKC').toLowerCase() }, ...items.slice(index + 1).map((entry, offset) => ({ ...entry, index: index + offset + 2 }))]; }

export default function ScriptEditingV2Page() {
  const [script, setScript] = useState(''); const [voicePath, setVoicePath] = useState(''); const [sourceRoots, setSourceRoots] = useState<string[]>([]); const [manualSourceRoot, setManualSourceRoot] = useState(''); const [sourceCounts, setSourceCounts] = useState<Record<string, number>>({}); const [usePexels, setUsePexels] = useState(false); const [priorityAssets, setPriorityAssets] = useState<Array<{ assetId: string; path: string; mode: 'PREFER' | 'MUST_USE' }>>([]); const [priorityPath, setPriorityPath] = useState(''); const [template, setTemplate] = useState('COMMERCIAL_OPINION'); const [pace, setPace] = useState('NORMAL'); const [density, setDensity] = useState('MEDIUM'); const [subtitleStyle, setSubtitleStyle] = useState('commercial'); const [heroText, setHeroText] = useState(true); const [musicMode, setMusicMode] = useState('NONE'); const [musicPath, setMusicPath] = useState(''); const [ducking, setDucking] = useState(true); const [intro, setIntro] = useState(false); const [outro, setOutro] = useState(false); const [outputRoot, setOutputRoot] = useState(''); const [segments, setSegments] = useState<Array<{ index: number; text: string; normalizedText: string }>>([]); const [cleanedScript, setCleanedScript] = useState(''); const [presentationSettings, setPresentationSettings] = useState<PresentationSettingsValue>(defaultPresentationSettings); const [plan, setPlan] = useState<Plan | null>(null); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false);
  const workspaceId = useMemo(() => 'workspace-local', []);

  useEffect(() => { const saved = window.localStorage.getItem('contentos-script-v2-plan'); if (saved) { try { setPlan(JSON.parse(saved) as Plan); } catch { /* ignore stale local state */ } } }, []);
  async function pickFolder(): Promise<void> { const response = await fetch('/api/v1/local-paths/pick-folder', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ purpose: 'MEDIA_ROOT' }) }); const data = await response.json() as { cancelled?: boolean; path?: string; error?: { message?: string } }; if (data.cancelled) return; if (!response.ok || !data.path) { setStatus(data.error?.message || '无法选择素材文件夹。'); return; } const path = data.path; setSourceRoots((current) => [...current.filter(Boolean), path]); const scan = await fetch('/api/v1/edit/sources/scan', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ sourceRoots: [path] }) }); const scanned = await scan.json() as { items?: Array<{ total?: number; available?: number }> }; const item = scanned.items?.[0]; setSourceCounts((current) => ({ ...current, [path]: Number(item?.available ?? item?.total ?? 0) })); }
  async function pickFile(purpose: 'VOICE_FILE' | 'MUSIC_FILE' | 'PRIORITY_ASSET'): Promise<string | undefined> { const response = await fetch('/api/v1/local-paths/pick-file', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ purpose }) }); const data = await response.json() as { cancelled?: boolean; path?: string; error?: { message?: string } }; if (data.cancelled) return undefined; if (!response.ok || !data.path) { setStatus(data.error?.message || '无法选择文件。'); return undefined; } return data.path; }
  async function pickVoice(): Promise<void> { const path = await pickFile('VOICE_FILE'); if (path) setVoicePath(path); }
  async function pickMusic(): Promise<void> { const path = await pickFile('MUSIC_FILE'); if (path) setMusicPath(path); }
  async function pickPriority(mode: 'PREFER' | 'MUST_USE'): Promise<void> { const path = await pickFile('PRIORITY_ASSET'); if (path) setPriorityAssets((items) => [...items, { assetId: path, path, mode }]); }
  async function createPlan(): Promise<void> {
    setBusy(true); setStatus('正在分析剪辑结构…');
    const music = musicMode === 'SPECIFIED' && musicPath.trim() ? { path: musicPath.trim(), volume: 0.12, loop: true, ducking: { enabled: ducking, musicVolume: 0.12 } } : undefined;
    const selectedRoots = [...sourceRoots.filter(Boolean), ...(manualSourceRoot.trim() ? [manualSourceRoot.trim()] : [])];
    const response = await fetch('/api/v1/edit/script-plans', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ workspaceId, script: cleanedScript || script, rawScript: script, cleanedScript, confirmedSegments: segments.map((segment) => segment.text), presentationSettings: { ...presentationSettings, output: { ...presentationSettings.output, outputRoot: outputRoot.trim() || undefined } }, voicePath: voicePath.trim() || undefined, sourceRoots: selectedRoots, usePexels, priorityAssets: priorityAssets.map((item) => item), template, pace, shotDensity: density, subtitleStyle, heroText, backgroundMusicMode: musicMode, backgroundMusic: music, introEnabled: intro, outroEnabled: outro, outputRoot: outputRoot.trim() || undefined }) });
    const data = await response.json() as Plan & { error?: { code?: string; message?: string } }; if (response.ok) { setPlan(data); window.localStorage.setItem('contentos-script-v2-plan', JSON.stringify(data)); setStatus(data.status === 'READY' ? '剪辑方案已生成' : '正在匹配素材…'); } else setStatus(`生成失败：${data.error?.message || '请检查设置'}`); setBusy(false);
  }
  async function refreshPlan(id = plan?.id): Promise<void> { if (!id) return; const response = await fetch(`/api/v1/edit/script-plans/${id}`); if (!response.ok) return; const next = await response.json() as Plan; setPlan(next); window.localStorage.setItem('contentos-script-v2-plan', JSON.stringify(next)); if (next.status === 'QUEUED' || next.status === 'PLANNING' || next.status === 'RENDERING') window.setTimeout(() => void refreshPlan(next.id), 1200); }
  async function updateClip(clipId: string, body: { locked?: boolean }): Promise<void> { if (!plan) return; const response = await fetch(`/api/v1/edit/script-plans/${plan.id}/clips/${clipId}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); if (response.ok) await refreshPlan(plan.id); }
  async function reroll(clipId?: string, localOnly = false): Promise<void> { if (!plan) return; setStatus('正在换片…'); const response = await fetch(`/api/v1/edit/script-plans/${plan.id}/reroll`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(clipId ? { clipId, localOnly } : {}) }); if (response.ok) await refreshPlan(plan.id); else setStatus(localOnly ? '当前没有合适的本地素材' : '当前镜头没有可替换素材'); }
  async function render(): Promise<void> { if (!plan || plan.status !== 'READY') return; setStatus('正在开始剪辑…'); const response = await fetch(`/api/v1/edit/script-plans/${plan.id}/render`, { method: 'POST' }); setStatus(response.ok ? '已进入渲染队列' : '方案尚未准备好'); await refreshPlan(plan.id); }
  useEffect(() => { if (!plan || (plan.status !== 'QUEUED' && plan.status !== 'PLANNING' && plan.status !== 'RENDERING')) return; const timer = window.setTimeout(() => void refreshPlan(plan.id), 0); return () => window.clearTimeout(timer); }, [plan?.id, plan?.status]);
  const scenes = plan?.resolvedPlan?.scenes ?? plan?.editorialPlan?.scenes ?? [];
  const splitAtCursor = (index: number): void => {
    const active = document.activeElement;
    const fallback = Math.max(1, Math.floor((segments[index]?.text.length || 2) / 2));
    const at = active instanceof HTMLInputElement && active.dataset.segmentIndex === String(index) ? active.selectionStart || fallback : fallback;
    setSegments((items) => splitScriptSegmentV1(items, index, at));
  };

  return <main className="shell"><header className="page-header"><p className="eyebrow">剪辑 / 规则方案 V2</p><h1>脚本剪辑</h1><p className="muted">先生成方案，确认镜头后再开始剪辑。</p></header>
    <section className="panel"><h2>1. 文案与配音</h2><label htmlFor="v2-script">文案</label><textarea id="v2-script" value={script} onChange={(event) => { setScript(event.target.value); setSegments([]); }} placeholder="输入文案，支持逗号级分段" rows={6} /><div className="inline-field"><button type="button" onClick={() => { const result = cleanAndSegmentScriptV1(script, presentationSettings.segmentation); setCleanedScript(result.cleanedScript); setSegments(result.segments); setStatus(`已整理 ${result.segments.length} 段，请确认后生成方案。`); }}>整理文案</button><span className="muted">保留原意，不改写文字</span></div>{segments.length ? <div><p className="muted">文案分段预览（确认后用于剪辑）</p>{segments.map((segment, index) => <div className="inline-field" key={`${segment.index}-${index}`}><strong>{String(index + 1).padStart(2, '0')}</strong><input data-segment-index={index} value={segment.text} onChange={(e) => setSegments((items) => items.map((item, i) => i === index ? { ...item, text: e.target.value, normalizedText: e.target.value.normalize('NFKC').toLowerCase() } : item))} /><button type="button" onClick={() => setSegments((items) => mergeScriptSegmentsV1(items, index - 1))} disabled={index === 0}>并入上一段</button><button type="button" onClick={() => setSegments((items) => mergeScriptSegmentsV1(items, index))} disabled={index === segments.length - 1}>并入下一段</button><button type="button" onClick={() => splitAtCursor(index)}>在光标处拆分</button><button type="button" onClick={() => setSegments((items) => items.filter((_, i) => i !== index).map((item, i) => ({ ...item, index: i })))}>删除空段</button></div>)}</div> : null}<label htmlFor="v2-voice">配音文件（可选）</label><div className="inline-field"><input id="v2-voice" value={voicePath} onChange={(event) => setVoicePath(event.target.value)} placeholder="可手动填写高级路径" /><button type="button" onClick={() => void pickVoice()}>选择配音</button></div>{plan ? <p className="muted">已分段 {plan.resolvedPlan?.sentences?.length || plan.editorialPlan?.sentences?.length || 0} 段 · 配音/方案时长 {((plan.resolvedPlan?.totalDurationMs || plan.editorialPlan?.totalDurationMs || 0) / 1000).toFixed(1)} 秒</p> : <p className="muted">先点击“整理文案”确认分段。</p>}</section>
    <section className="panel"><h2>2. 剪辑方式</h2><div className="grid"><label>模板<select value={template} onChange={(event) => setTemplate(event.target.value)}><option value="COMMERCIAL_OPINION">商业观点</option><option value="NEWS">新闻解读</option><option value="STORE_PROMOTION">门店宣传</option><option value="PRODUCT_INTRO">产品介绍</option></select></label><label>节奏<select value={pace} onChange={(event) => setPace(event.target.value)}><option value="SLOW">舒缓</option><option value="NORMAL">正常</option><option value="FAST">紧凑</option></select></label><label>画面变化<select value={density} onChange={(event) => setDensity(event.target.value)}><option value="LOW">少</option><option value="MEDIUM">适中</option><option value="HIGH">多</option></select></label></div></section>
    <section className="panel"><h2>3. 素材来源</h2>{sourceRoots.filter(Boolean).map((root) => <div className="inline-field" key={root}><span>{root}</span><small className="muted">✓ {sourceCounts[root] ?? '已选择'} 个视频</small><button type="button" onClick={() => setSourceRoots((current) => current.filter((item) => item !== root))}>删除</button></div>)}<div className="inline-field"><button type="button" onClick={() => void pickFolder()}>+ 选择素材文件夹</button><input value={manualSourceRoot} onChange={(event) => setManualSourceRoot(event.target.value)} placeholder="高级模式：手动填写路径" /></div><label className="checkbox"><input type="checkbox" checked={usePexels} onChange={(event) => setUsePexels(event.target.checked)} />使用 Pexels 补充素材</label></section>
    <section className="panel"><h2>4. 重点素材</h2><div className="inline-field"><input value={priorityPath} onChange={(event) => setPriorityPath(event.target.value)} placeholder="高级模式：手动填写路径" /><button type="button" onClick={() => void pickPriority('PREFER')}>选择重点素材</button><select onChange={(event) => { if (priorityPath.trim()) setPriorityAssets((items) => [...items, { assetId: priorityPath.trim(), path: priorityPath.trim(), mode: event.target.value as 'PREFER' | 'MUST_USE' }]); setPriorityPath(''); }} defaultValue="PREFER"><option value="PREFER">优先使用</option><option value="MUST_USE">必须出现</option></select></div>{priorityAssets.map((item) => <p className="muted" key={item.assetId}>{item.assetId} · {item.mode === 'MUST_USE' ? '必须出现' : '优先使用'}</p>)}</section>
    <section className="panel"><h2>5. 字幕与文字</h2><label>字幕样式<select value={subtitleStyle} onChange={(event) => setSubtitleStyle(event.target.value)}><option value="simple">简洁白字</option><option value="commercial">商业蓝白</option><option value="emphasis">大字强调</option></select></label><label className="checkbox"><input type="checkbox" checked={heroText} onChange={(event) => setHeroText(event.target.checked)} />重点文字</label></section>
    <section className="panel"><h2>6. 音乐与品牌</h2><label>背景音乐<select value={musicMode} onChange={(event) => setMusicMode(event.target.value)}><option value="NONE">无</option><option value="AUTO">自动按模板</option><option value="SPECIFIED">指定本地音乐</option></select></label>{musicMode === 'SPECIFIED' ? <div className="inline-field"><input value={musicPath} onChange={(event) => setMusicPath(event.target.value)} placeholder="高级模式：手动填写路径" /><button type="button" onClick={() => void pickMusic()}>选择音乐</button></div> : null}<label className="checkbox"><input type="checkbox" checked={ducking} onChange={(event) => setDucking(event.target.checked)} />配音时降低背景音乐</label><label className="checkbox"><input type="checkbox" checked={intro} onChange={(event) => setIntro(event.target.checked)} />片头</label><label className="checkbox"><input type="checkbox" checked={outro} onChange={(event) => setOutro(event.target.checked)} />片尾</label></section>
    <PresentationSettingsPanel value={presentationSettings} onChange={setPresentationSettings} previewText={segments[0]?.text || '字幕预览'} />
    <section className="panel"><h2>7. 输出</h2><label htmlFor="v2-output-root">输出文件夹（可选）</label><div className="inline-field"><input id="v2-output-root" value={outputRoot} onChange={(event) => setOutputRoot(event.target.value)} placeholder="高级模式：手动填写路径" /><button type="button" onClick={async () => { const response = await fetch('/api/v1/local-paths/pick-folder', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ purpose: 'OUTPUT_ROOT' }) }); const data = await response.json() as { cancelled?: boolean; path?: string; error?: { message?: string } }; if (data.path) setOutputRoot(data.path); else if (!data.cancelled) setStatus(data.error?.message || '无法选择输出文件夹。'); }}>选择输出文件夹</button></div><p className="muted">画布设置会随脚本和 MIX 共用并写入历史记录。</p><button type="button" onClick={() => void createPlan()} disabled={busy || !script.trim()}>生成剪辑方案</button>{status ? <p className="muted">{status}</p> : null}</section>
    {plan ? <section className="panel"><div className="page-header-row"><div><h2>剪辑方案</h2><p className="muted">{scenes.length} 个场景 · 第 {plan.revision} 版</p>{plan.outputPath ? <p className="muted">成片路径：{plan.outputPath}</p> : null}</div><button type="button" onClick={() => void render()} disabled={plan.status !== 'READY'}>开始剪辑</button></div>{plan.resolvedPlan?.warnings?.length ? <p className="status">提示：{plan.resolvedPlan.warnings.map(warningLabel).join('；')}</p> : null}{scenes.map((scene) => <article className="card" key={scene.id}><div className="page-header-row"><div><h3>场景 {String(scene.sceneIndex + 1).padStart(2, '0')} · {roleLabels[scene.role] || scene.role} · {seconds(scene.endMs - scene.startMs)}</h3><p>{scene.text}</p></div><button type="button" onClick={() => void reroll()} disabled={scene.clipSlots.every((clip) => clip.locked)}>换未锁定镜头</button></div>{scene.clipSlots.map((clip) => <div className="inline-field" key={clip.id}>{clip.asset?.thumbnailUrl ? <img src={clip.asset.thumbnailUrl} alt={clip.asset.originalName || '素材缩略图'} width={96} height={54} style={{ objectFit: 'cover', borderRadius: 6 }} /> : <span aria-label="素材缩略图占位" style={{ display: 'inline-flex', width: 96, height: 54, alignItems: 'center', justifyContent: 'center', borderRadius: 6, background: '#eef2f7', color: '#64748b' }}>素材</span>}<span>{clip.asset?.originalName || clip.asset?.path || clip.selectedAssetId || '等待素材'}{clip.asset?.author ? ` · ${clip.asset.author}` : ''} · {sourceLabels[clip.asset?.source || clip.selectedSource || ''] || '待匹配'} · {seconds(clip.durationMs)}</span><button type="button" onClick={() => void reroll(clip.id)} disabled={clip.locked}>换一个</button><button type="button" onClick={() => void reroll(clip.id, true)} disabled={clip.locked}>仅用本地</button><button type="button" onClick={() => void updateClip(clip.id, { locked: !clip.locked })}>{clip.locked ? '已锁定' : '锁定'}</button></div>)}</article>)}</section> : null}
  </main>;
}
