'use client';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
type Brief = { id: string; topic: string; coreThesis: string; targetPlatform: string; targetDurationSeconds: number };
type Script = { id: string; revision: number; status: string; origin: string; title: string; titleCandidates: string[]; coverText: string; topicKeywords: string[]; hook: string; body: string; cta?: string; parentRevisionId?: string };
type Storyboard = { id: string; revision: number; status: string; scriptRevisionId: string; scenes: Array<{ sceneIndex: number; voiceoverText: string }> };
type Job = { jobId: string; state: string };
const briefDefaults = { topic: '', targetPlatform: 'douyin', channelPositioning: '', targetDurationSeconds: 45, contentType: 'knowledge', audience: '', coreThesis: '', tone: '清晰、克制', ctaGoal: '', referenceMaterial: '未提供事实依据', mustInclude: [], mustAvoid: [], requirements: {}, createdBy: 'operator' };

export default function DirectorPage({ params }: { params: { id: string } }) {
  const projectId = params.id; const [brief, setBrief] = useState<Brief | null>(null); const [scripts, setScripts] = useState<Script[]>([]); const [storyboards, setStoryboards] = useState<Storyboard[]>([]); const [job, setJob] = useState<Job | null>(null); const [form, setForm] = useState(briefDefaults); const [message, setMessage] = useState('');
  const refresh = useCallback(async () => { const [briefResponse, scriptsResponse, storyboardResponse] = await Promise.all([fetch(`/api/v1/projects/${projectId}/director/brief/current`), fetch(`/api/v1/projects/${projectId}/scripts`), fetch(`/api/v1/projects/${projectId}/storyboards`)]); if (briefResponse.ok) setBrief(await briefResponse.json() as Brief); if (scriptsResponse.ok) setScripts((await scriptsResponse.json() as { items: Script[] }).items); if (storyboardResponse.ok) setStoryboards((await storyboardResponse.json() as { items: Storyboard[] }).items); }, [projectId]);
  useEffect(() => { void refresh(); }, [refresh]);
  const createBrief = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const response = await fetch(`/api/v1/projects/${projectId}/director/brief`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); if (!response.ok) { setMessage('Brief 校验失败，请检查必填字段。'); return; } const created = await response.json() as Brief; setBrief(created); setMessage(`Brief ${created.id} 已创建。`); };
  const generateScript = async () => { if (!brief) return; const response = await fetch(`/api/v1/projects/${projectId}/scripts/generate`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ briefId: brief.id }) }); const data = await response.json() as Job & { error?: { message?: string } }; setJob(data); setMessage(response.ok ? `Script Job ${data.jobId} 已入队。` : data.error?.message || 'Job 创建失败。'); };
  const acceptScript = async (scriptId: string) => { await fetch(`/api/v1/projects/${projectId}/scripts/${scriptId}/accept`, { method: 'POST' }); await refresh(); };
  const reviseScript = async (script: Script, body: string) => { await fetch(`/api/v1/projects/${projectId}/scripts/${script.id}/revisions`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ origin: 'MANUAL', title: script.title, titleCandidates: script.titleCandidates, coverText: script.coverText, topicKeywords: script.topicKeywords, hook: script.hook, body, ...(script.cta ? { cta: script.cta } : {}), createdBy: 'operator' }) }); await refresh(); };
  const generateStoryboard = async (scriptId: string) => { const response = await fetch(`/api/v1/projects/${projectId}/scripts/${scriptId}/storyboards/generate`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: '{}' }); const data = await response.json() as Job; setJob(data); };
  const approveStoryboard = async (storyboardId: string) => { await fetch(`/api/v1/projects/${projectId}/storyboards/${storyboardId}/approve`, { method: 'POST' }); await refresh(); };
  return <main className="shell"><header><p className="eyebrow">Project / {projectId}</p><h1>Director 工作台</h1><p className="muted">Brief 是输入事实，Script 和 Storyboard 以追加版本保存；生成工作通过 Durable Job 执行。</p></header><section className="grid"><form className="card" onSubmit={createBrief}><div className="section-title"><h2>ContentBrief</h2><span>{brief ? `当前 ${brief.id}` : '未创建'}</span></div><label>选题<input value={form.topic} onChange={(event) => setForm({ ...form, topic: event.target.value })} required /></label><label>栏目定位<input value={form.channelPositioning} onChange={(event) => setForm({ ...form, channelPositioning: event.target.value })} required /></label><label>目标受众<input value={form.audience} onChange={(event) => setForm({ ...form, audience: event.target.value })} required /></label><label>核心观点<textarea value={form.coreThesis} onChange={(event) => setForm({ ...form, coreThesis: event.target.value })} required /></label><label>事实依据<textarea value={form.referenceMaterial} onChange={(event) => setForm({ ...form, referenceMaterial: event.target.value })} required /></label><button type="submit">保存 Brief 版本</button></form><section className="card"><div className="section-title"><h2>生成 Job</h2><span>{job?.state || '—'}</span></div><p className="muted">API 只入队，不在浏览器或请求处理器中执行 AI。</p><button type="button" onClick={() => void generateScript()} disabled={!brief}>生成 Script</button>{job && <p className="status">{job.jobId} · {job.state}</p>}{message && <p className="status">{message}</p>}</section></section><section className="card"><div className="section-title"><h2>Script revisions</h2><span>{scripts.length} 个版本</span></div><ul className="revision-list">{scripts.map((script) => <li key={script.id}><strong>V{script.revision} · {script.title}</strong><span>{script.status} / {script.origin}</span><small>{script.hook}</small>{script.status === 'DRAFT' && <><button type="button" onClick={() => void acceptScript(script.id)}>接受 Script</button><button type="button" onClick={() => void reviseScript(script, `${script.body}\n\n补充说明：请用一个真实例子解释。`)}>生成手工 V{script.revision + 1}</button></>}{script.status === 'ACCEPTED' && <button type="button" onClick={() => void generateStoryboard(script.id)}>生成 Storyboard Job</button>}</li>)}</ul></section><section className="card"><div className="section-title"><h2>Storyboard revisions</h2><span>{storyboards.length} 个版本</span></div><ul className="revision-list">{storyboards.map((storyboard) => <li key={storyboard.id}><strong>V{storyboard.revision} · {storyboard.status}</strong><span>绑定 Script {storyboard.scriptRevisionId}</span><small>{storyboard.scenes.map((scene) => `${scene.sceneIndex}. ${scene.voiceoverText}`).join(' / ')}</small>{storyboard.status === 'DRAFT' && <button type="button" onClick={() => void approveStoryboard(storyboard.id)}>批准 Storyboard</button>}</li>)}</ul></section></main>;
}
