'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';

type Preset = { id: string; name: string; description: string; editModeDefault: 'SCRIPT' | 'RANDOM'; minClipDurationMs: number; maxClipDurationMs: number; preferUnusedMedia: boolean; introAssetId: string | null; outroAssetId: string | null; canvas?: { width: number; height: number; aspectRatio: string }; fps?: number; isDefault: boolean };

export default function VideoPresetsPage() {
  const [items, setItems] = useState<Preset[]>([]);
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [message, setMessage] = useState('');
  const load = async () => { const response = await fetch('/api/v1/video/presets'); if (response.ok) setItems((await response.json() as { items: Preset[] }).items); };
  useEffect(() => { void load(); }, []);
  const create = async () => { if (!name.trim()) return; const response = await fetch('/api/v1/video/presets', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name, description, editModeDefault: 'SCRIPT', minClipDurationMs: 2000, maxClipDurationMs: 5000, preferUnusedMedia: true }) }); setMessage(response.ok ? '模板已创建。' : '模板创建失败。'); if (response.ok) { setName(''); setDescription(''); await load(); } };
  const duplicate = async (preset: Preset) => { const response = await fetch('/api/v1/video/presets', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: `${preset.name}（副本）`, description: preset.description, editModeDefault: preset.editModeDefault, minClipDurationMs: preset.minClipDurationMs, maxClipDurationMs: preset.maxClipDurationMs, preferUnusedMedia: preset.preferUnusedMedia, introAssetId: preset.introAssetId, outroAssetId: preset.outroAssetId }) }); setMessage(response.ok ? '模板已复制。' : '模板复制失败。'); await load(); };
  const setDefault = async (id: string) => { const response = await fetch(`/api/v1/video/presets/${id}/default`, { method: 'POST' }); setMessage(response.ok ? '默认模板已更新。' : '默认模板更新失败。'); await load(); };
  const remove = async (id: string) => { const response = await fetch(`/api/v1/video/presets/${id}`, { method: 'DELETE' }); setMessage(response.ok ? '模板已删除。' : '默认模板不能删除。'); await load(); };
  const update = async (preset: Preset) => { const response = await fetch(`/api/v1/video/presets/${preset.id}`, { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: preset.name, description: preset.description, editModeDefault: preset.editModeDefault, minClipDurationMs: preset.minClipDurationMs, maxClipDurationMs: preset.maxClipDurationMs, preferUnusedMedia: preset.preferUnusedMedia, introAssetId: preset.introAssetId || null, outroAssetId: preset.outroAssetId || null }) }); setMessage(response.ok ? '模板已保存。' : '模板保存失败。'); await load(); };
  const change = <K extends keyof Preset>(id: string, key: K, value: Preset[K]) => setItems((current) => current.map((item) => item.id === id ? { ...item, [key]: value } : item));
  return <main className="shell"><header><p className="eyebrow"><Link href="/settings">系统设置</Link> / 视频剪辑</p><h1>剪辑模板</h1><p className="muted">管理默认短视频、MIZAN 门店口播、商业分析和产品推荐模板。</p></header><section className="card preset-create"><h2>新建模板</h2><input aria-label="模板名称" value={name} onChange={(event) => setName(event.target.value)} placeholder="模板名称" /><input aria-label="模板说明" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="模板说明" /><button type="button" onClick={() => void create()}>新建模板</button></section><section className="preset-list">{items.map((preset) => <article className="card" key={preset.id}><div className="section-title"><input aria-label={`模板名称 ${preset.id}`} value={preset.name} onChange={(event) => change(preset.id, 'name', event.target.value)} /><span>{preset.isDefault ? '默认模板' : ''}</span></div><textarea aria-label={`模板说明 ${preset.id}`} value={preset.description} onChange={(event) => change(preset.id, 'description', event.target.value)} /><label>适用剪辑方式<select value={preset.editModeDefault} onChange={(event) => change(preset.id, 'editModeDefault', event.target.value as Preset['editModeDefault'])}><option value="SCRIPT">按脚本剪辑</option><option value="RANDOM">随机混剪</option></select></label><div className="preset-duration"><label>最短镜头（秒）<input type="number" min="0.1" step="0.1" value={(preset.minClipDurationMs / 1000).toFixed(1)} onChange={(event) => change(preset.id, 'minClipDurationMs', Math.round(Number(event.target.value) * 1000))} /></label><label>最长镜头（秒）<input type="number" min="0.1" step="0.1" value={(preset.maxClipDurationMs / 1000).toFixed(1)} onChange={(event) => change(preset.id, 'maxClipDurationMs', Math.round(Number(event.target.value) * 1000))} /></label></div><label className="inline-check"><input type="checkbox" checked={preset.preferUnusedMedia} onChange={(event) => change(preset.id, 'preferUnusedMedia', event.target.checked)} />优先使用近期没出现过的素材</label><label>固定片头<input value={preset.introAssetId || ''} onChange={(event) => change(preset.id, 'introAssetId', event.target.value || null)} placeholder="可留空，使用项目素材选择器" /></label><label>固定片尾<input value={preset.outroAssetId || ''} onChange={(event) => change(preset.id, 'outroAssetId', event.target.value || null)} placeholder="可留空，使用项目素材选择器" /></label><p className="muted">输出格式：竖屏 1080×1920 · 30帧/秒</p><div className="review-actions"><button type="button" onClick={() => void update(preset)}>保存</button><button type="button" onClick={() => void duplicate(preset)}>复制</button>{!preset.isDefault && <><button type="button" onClick={() => void setDefault(preset.id)}>设为默认</button><button type="button" onClick={() => void remove(preset.id)}>删除</button></>}</div></article>)}</section>{message && <p className="status">{message}</p>}</main>;
}
