"use client";

import Link from "next/link";
import { useEffect, useState, type ChangeEvent } from "react";
import { PresetAssetPicker, type PresetAsset } from "../../../components/video/preset-asset-picker";

type Preset = { id: string; name: string; description: string; editModeDefault: "SCRIPT" | "RANDOM"; minClipDurationMs: number; maxClipDurationMs: number; preferUnusedMedia: boolean; introAssetId: string | null; outroAssetId: string | null; canvas?: { width: number; height: number; aspectRatio: string }; fps?: number; isDefault: boolean };

export default function VideoPresetsPage() {
  const [items, setItems] = useState<Preset[]>([]);
  const [brandingAssets, setBrandingAssets] = useState<PresetAsset[]>([]);
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [message, setMessage] = useState("");
  const [uploading, setUploading] = useState(false);
  const load = async () => {
    const [presetsResponse, assetsResponse] = await Promise.all([fetch("/api/v1/video/presets"), fetch("/api/v1/video/preset-assets")]);
    if (presetsResponse.ok) setItems((await presetsResponse.json() as { items: Preset[] }).items);
    if (assetsResponse.ok) setBrandingAssets((await assetsResponse.json() as { items: PresetAsset[] }).items);
  };
  useEffect(() => { void load(); }, []);
  const create = async () => { if (!name.trim()) return; const response = await fetch("/api/v1/video/presets", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, description, editModeDefault: "SCRIPT", minClipDurationMs: 2000, maxClipDurationMs: 5000, preferUnusedMedia: true }) }); setMessage(response.ok ? "模板已创建。" : "模板创建失败。"); if (response.ok) { setName(""); setDescription(""); await load(); } };
  const duplicate = async (preset: Preset) => { const response = await fetch("/api/v1/video/presets", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: `${preset.name}（副本）`, description: preset.description, editModeDefault: preset.editModeDefault, minClipDurationMs: preset.minClipDurationMs, maxClipDurationMs: preset.maxClipDurationMs, preferUnusedMedia: preset.preferUnusedMedia, introAssetId: preset.introAssetId, outroAssetId: preset.outroAssetId }) }); setMessage(response.ok ? "模板已复制。" : "模板复制失败。"); await load(); };
  const setDefault = async (id: string) => { const response = await fetch(`/api/v1/video/presets/${id}/default`, { method: "POST" }); setMessage(response.ok ? "默认模板已更新。" : "默认模板更新失败。"); await load(); };
  const remove = async (id: string) => { const response = await fetch(`/api/v1/video/presets/${id}`, { method: "DELETE" }); setMessage(response.ok ? "模板已删除。" : "默认模板不能删除。此模板可能仍被项目使用。"); await load(); };
  const uploadBranding = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); const body = new FormData(); body.append("file", file); const response = await fetch("/api/v1/video/preset-assets", { method: "POST", body }); const data = response.ok ? null : await response.json() as { error?: { message?: string } }; setUploading(false); setMessage(response.ok ? "品牌视频已上传。" : data?.error?.message || "品牌视频上传失败，请检查文件后重试。"); event.target.value = ""; await load(); };
  const removeBranding = async (asset: PresetAsset) => { const response = await fetch(`/api/v1/video/preset-assets/${encodeURIComponent(asset.id)}`, { method: "DELETE" }); const data = response.ok ? null : await response.json() as { error?: { message?: string } }; setMessage(response.ok ? "品牌视频已移除。" : data?.error?.message || "品牌视频删除失败。通常需要先从剪辑模板中移除。"); await load(); };
  const update = async (preset: Preset) => { const response = await fetch(`/api/v1/video/presets/${preset.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: preset.name, description: preset.description, editModeDefault: preset.editModeDefault, minClipDurationMs: preset.minClipDurationMs, maxClipDurationMs: preset.maxClipDurationMs, preferUnusedMedia: preset.preferUnusedMedia, introAssetId: preset.introAssetId || null, outroAssetId: preset.outroAssetId || null }) }); setMessage(response.ok ? "模板已保存。" : "模板保存失败。"); await load(); };
  const change = <K extends keyof Preset>(id: string, key: K, value: Preset[K]) => setItems((current) => current.map((item) => item.id === id ? { ...item, [key]: value } : item));
  return <main className="shell">
    <header><p className="eyebrow"><Link href="/settings">系统设置</Link> / 视频剪辑</p><h1>剪辑模板</h1><p className="muted">管理默认短视频、MIZAN 门店口播、商业分析和产品推荐模板。</p></header>
    <section className="card preset-create"><h2>品牌素材</h2><p className="muted">用于剪辑模板的固定片头和片尾。</p><label className="upload-control">上传品牌视频<input aria-label="品牌视频文件" type="file" accept="video/*" onChange={(event) => void uploadBranding(event)} disabled={uploading} /></label>{brandingAssets.length > 0 ? <div className="branding-asset-list">{brandingAssets.map((asset) => <div className="branding-asset-row" key={asset.id}><span><strong>{asset.originalName}</strong><small>{(asset.durationMs / 1000).toFixed(1)} 秒</small></span><button type="button" onClick={() => void removeBranding(asset)}>删除</button></div>)}</div> : <p className="muted">暂无品牌素材，请先上传品牌视频。</p>}</section>
    <section className="card preset-create"><h2>新建模板</h2><input aria-label="模板名称" value={name} onChange={(event) => setName(event.target.value)} placeholder="模板名称" /><input aria-label="模板说明" value={description} onChange={(event) => setDescription(event.target.value)} placeholder="模板说明" /><button type="button" onClick={() => void create()}>新建模板</button></section>
    <section className="preset-list">{items.map((preset) => <article className="card" key={preset.id}><div className="section-title"><input aria-label={`模板名称 ${preset.id}`} value={preset.name} onChange={(event) => change(preset.id, "name", event.target.value)} /><span>{preset.isDefault ? "默认模板" : ""}</span></div><textarea aria-label={`模板说明 ${preset.id}`} value={preset.description} onChange={(event) => change(preset.id, "description", event.target.value)} /><label>适用剪辑方式<select value={preset.editModeDefault} onChange={(event) => change(preset.id, "editModeDefault", event.target.value as Preset["editModeDefault"])}><option value="SCRIPT">按脚本剪辑</option><option value="RANDOM">随机混剪</option></select></label><div className="preset-duration"><label>最短镜头（秒）<input type="number" min="0.1" step="0.1" value={(preset.minClipDurationMs / 1000).toFixed(1)} onChange={(event) => change(preset.id, "minClipDurationMs", Math.round(Number(event.target.value) * 1000))} /></label><label>最长镜头（秒）<input type="number" min="0.1" step="0.1" value={(preset.maxClipDurationMs / 1000).toFixed(1)} onChange={(event) => change(preset.id, "maxClipDurationMs", Math.round(Number(event.target.value) * 1000))} /></label></div><label className="inline-check"><input type="checkbox" checked={preset.preferUnusedMedia} onChange={(event) => change(preset.id, "preferUnusedMedia", event.target.checked)} />优先使用近期没出现过的素材</label><PresetAssetPicker label="片头" value={preset.introAssetId} assets={brandingAssets} onChange={(value) => change(preset.id, "introAssetId", value)} /><PresetAssetPicker label="片尾" value={preset.outroAssetId} assets={brandingAssets} onChange={(value) => change(preset.id, "outroAssetId", value)} /><p className="muted">输出格式：竖屏 1080×1920 · 30帧/秒</p><div className="review-actions"><button type="button" onClick={() => void update(preset)}>保存</button><button type="button" onClick={() => void duplicate(preset)}>复制</button>{!preset.isDefault && <><button type="button" onClick={() => void setDefault(preset.id)}>设为默认</button><button type="button" onClick={() => void remove(preset.id)}>删除</button></>}</div></article>)}</section>{message && <p className="status">{message}</p>}
  </main>;
}
