import { createHash, randomUUID } from 'node:crypto';
import type { Pool } from 'pg';
import type { AvatarClipV1, AvatarGenerationV1, AvatarProfileV1, GenerationStatus, ProfileStatus, SpeechGenerationV1, VoiceProfileV1 } from '../../../contracts/src/index.js';
import { AssetCatalogService } from '../../asset/src/index.js';
import { JobService, type JobRecord } from '../../job/src/index.js';

export interface CreateVoiceProfileInput { projectId: string; name: string; provider: string; referenceAssetId?: string | undefined; providerVoiceId?: string | undefined; language?: string | undefined; defaultSpeed?: number | undefined; defaultEmotion?: string | undefined; status?: ProfileStatus | undefined; }
export interface UpdateVoiceProfileInput { name?: string | undefined; referenceAssetId?: string | null | undefined; providerVoiceId?: string | null | undefined; language?: string | undefined; defaultSpeed?: number | undefined; defaultEmotion?: string | undefined; status?: ProfileStatus | undefined; }
export interface CreateAvatarProfileInput { projectId: string; name: string; ownerName?: string | undefined; status?: ProfileStatus | undefined; }
export interface UpdateAvatarProfileInput { name?: string | undefined; ownerName?: string | undefined; status?: ProfileStatus | undefined; }
export interface CreateAvatarClipInput { projectId: string; avatarProfileId: string; assetId: string; name: string; durationMs?: number | undefined; width?: number | undefined; height?: number | undefined; fps?: number | undefined; sceneType?: string | undefined; gestureLevel?: string | undefined; tags?: string[] | undefined; }
export interface UpdateAvatarClipInput { name?: string | undefined; assetId?: string | undefined; durationMs?: number | null | undefined; width?: number | null | undefined; height?: number | null | undefined; fps?: number | null | undefined; sceneType?: string | null | undefined; gestureLevel?: string | null | undefined; tags?: string[] | undefined; status?: ProfileStatus | undefined; }
export interface CreateSpeechGenerationInput { projectId: string; voiceProfileId: string; text: string; provider?: string | undefined; model?: string | undefined; language?: string | undefined; speed?: number | undefined; emotion?: string | undefined; correlationId: string; }
export interface CreateAvatarGenerationInput { projectId: string; avatarProfileId: string; avatarClipId: string; speechAssetId: string; sourceInMs?: number | undefined; provider?: string | undefined; model?: string | undefined; parameters?: Record<string, unknown> | undefined; correlationId: string; }
export interface DigitalHumanAssetReader { getProjectAsset(projectId: string, assetId: string): Promise<{ id: string; projectId: string; kind: string; lifecycle: string; storageKey: string; checksum: string; metadata: Record<string, unknown> } | null>; getReadySourceAsset(projectId: string, assetId: string, kind: 'VIDEO' | 'AUDIO'): Promise<{ id: string; projectId: string; kind: 'VIDEO' | 'AUDIO'; storageKey: string; metadata: Record<string, unknown> } | null>; }

const record = (value: unknown): Record<string, unknown> => value && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {};
const text = (value: unknown): string => value === null || value === undefined ? '' : String(value);
const optionalText = (value: unknown): string | null => value === null || value === undefined ? null : String(value);
const iso = (value: unknown): string => new Date(text(value)).toISOString();
const hash = (value: unknown): string => createHash('sha256').update(typeof value === 'string' ? value : JSON.stringify(value)).digest('hex');
const stableId = (prefix: string, projectId: string, requestHash: string): string => `${prefix}-${hash({ projectId, requestHash })}`;
const positiveDuration = (metadata: Record<string, unknown>): boolean => Number.isFinite(Number(metadata.durationMs)) && Number(metadata.durationMs) > 0;
const validSpeed = (value: number, field: string): number => { if (!Number.isFinite(value) || value < .5 || value > 2) throw new Error(`${field} must be between 0.5 and 2`); return value; };

export interface AvatarTiming { sourceVideoAssetId: string; sourceInMs: number; sourceOutMs: number; targetDurationMs: number; sourceDurationMs: number; audioDurationMs: number; }
export class DigitalHumanDurationError extends Error { constructor(public readonly code: 'SOURCE_VIDEO_TOO_SHORT' | 'SPEECH_ASSET_DURATION_INVALID' | 'AVATAR_CLIP_DURATION_INVALID', public readonly details: Record<string, number>) { super(code); this.name = 'DigitalHumanDurationError'; } }
export function normalizeAvatarTiming(sourceVideo: { id: string; metadata: Record<string, unknown> }, audio: { metadata: Record<string, unknown> }, sourceInMs = 0): AvatarTiming {
  const sourceDurationMs = Number(sourceVideo.metadata.durationMs); const audioDurationMs = Number(audio.metadata.durationMs);
  if (!Number.isFinite(sourceDurationMs) || sourceDurationMs <= 0) throw new DigitalHumanDurationError('AVATAR_CLIP_DURATION_INVALID', { sourceDurationMs, audioDurationMs, requiredDurationMs: audioDurationMs });
  if (!Number.isFinite(audioDurationMs) || audioDurationMs <= 0) throw new DigitalHumanDurationError('SPEECH_ASSET_DURATION_INVALID', { sourceDurationMs, audioDurationMs, requiredDurationMs: audioDurationMs });
  if (!Number.isInteger(sourceInMs) || sourceInMs < 0) throw new DigitalHumanDurationError('SOURCE_VIDEO_TOO_SHORT', { sourceDurationMs, audioDurationMs, requiredDurationMs: audioDurationMs, sourceInMs });
  const sourceOutMs = sourceInMs + audioDurationMs;
  if (sourceOutMs > sourceDurationMs) throw new DigitalHumanDurationError('SOURCE_VIDEO_TOO_SHORT', { sourceDurationMs, audioDurationMs, requiredDurationMs: audioDurationMs, sourceInMs, sourceOutMs });
  return { sourceVideoAssetId: sourceVideo.id, sourceInMs, sourceOutMs, targetDurationMs: audioDurationMs, sourceDurationMs, audioDurationMs };
}

function mapVoice(row: Record<string, unknown>): VoiceProfileV1 { return { id: text(row.id), projectId: text(row.project_id), name: text(row.name), provider: text(row.provider), referenceAssetId: optionalText(row.reference_asset_id), providerVoiceId: optionalText(row.provider_voice_id), language: text(row.language), defaultSpeed: Number(row.default_speed), defaultEmotion: text(row.default_emotion), status: row.status as ProfileStatus, createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) }; }
function mapAvatar(row: Record<string, unknown>): AvatarProfileV1 { return { id: text(row.id), projectId: text(row.project_id), name: text(row.name), ownerName: text(row.owner_name), status: row.status as ProfileStatus, createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) }; }
function mapClip(row: Record<string, unknown>): AvatarClipV1 { return { id: text(row.id), projectId: text(row.project_id), avatarProfileId: text(row.avatar_profile_id), assetId: text(row.asset_id), name: text(row.name), durationMs: row.duration_ms === null || row.duration_ms === undefined ? null : Number(row.duration_ms), width: row.width === null || row.width === undefined ? null : Number(row.width), height: row.height === null || row.height === undefined ? null : Number(row.height), fps: row.fps === null || row.fps === undefined ? null : Number(row.fps), sceneType: optionalText(row.scene_type), gestureLevel: optionalText(row.gesture_level), tags: Array.isArray(row.tags) ? row.tags.filter((tag): tag is string => typeof tag === 'string') : [], status: row.status as ProfileStatus, usageCount: Number(row.usage_count), lastUsedAt: row.last_used_at ? iso(row.last_used_at) : null, createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) }; }
function mapSpeech(row: Record<string, unknown>): SpeechGenerationV1 { const error = record(row.error); return { id: text(row.id), projectId: text(row.project_id), voiceProfileId: text(row.voice_profile_id), provider: text(row.provider), model: text(row.model), modelVersion: optionalText(row.model_version), text: text(row.text), textHash: text(row.text_hash), parameters: record(row.parameters), status: row.status as GenerationStatus, jobId: text(row.job_id), outputAssetId: optionalText(row.output_asset_id), durationMs: row.duration_ms === null || row.duration_ms === undefined ? null : Number(row.duration_ms), latencyMs: row.latency_ms === null || row.latency_ms === undefined ? null : Number(row.latency_ms), provenance: record(row.provenance), error: Object.keys(error).length ? { code: text(error.code), message: text(error.message) } : null, createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) }; }
function mapAvatarGeneration(row: Record<string, unknown>): AvatarGenerationV1 { const error = record(row.error); return { id: text(row.id), projectId: text(row.project_id), avatarProfileId: text(row.avatar_profile_id), avatarClipId: text(row.avatar_clip_id), speechAssetId: text(row.speech_asset_id), sourceVideoAssetId: optionalText(row.source_video_asset_id), sourceInMs: Number(row.source_in_ms || 0), sourceOutMs: row.source_out_ms === null || row.source_out_ms === undefined ? null : Number(row.source_out_ms), targetDurationMs: row.target_duration_ms === null || row.target_duration_ms === undefined ? null : Number(row.target_duration_ms), provider: text(row.provider), model: optionalText(row.model), modelVersion: optionalText(row.model_version), externalTaskId: optionalText(row.external_task_id), status: row.status as GenerationStatus, jobId: text(row.job_id), outputAssetId: optionalText(row.output_asset_id), durationMs: row.duration_ms === null || row.duration_ms === undefined ? null : Number(row.duration_ms), costAmount: row.cost_amount === null || row.cost_amount === undefined ? null : Number(row.cost_amount), costCurrency: optionalText(row.cost_currency), billingQuantity: row.billing_quantity === null || row.billing_quantity === undefined ? null : Number(row.billing_quantity), billingUnit: optionalText(row.billing_unit), requestHash: text(row.request_hash), provenance: record(row.provenance), error: Object.keys(error).length ? { code: text(error.code), message: text(error.message) } : null, createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) }; }

export class DigitalHumanService {
  constructor(private readonly db: Pool, private readonly jobs: JobService, private readonly assets: DigitalHumanAssetReader = new AssetCatalogService(db)) {}

  async createVoiceProfile(input: CreateVoiceProfileInput): Promise<VoiceProfileV1> {
    if (input.referenceAssetId) { const asset = await this.assets.getProjectAsset(input.projectId, input.referenceAssetId); if (!asset || asset.kind !== 'AUDIO' || asset.lifecycle !== 'READY' || !positiveDuration(asset.metadata)) throw new Error('VOICE_REFERENCE_ASSET_NOT_READY'); }
    const defaultSpeed = validSpeed(input.defaultSpeed ?? 1, 'defaultSpeed');
    const result = await this.db.query('insert into voice_profiles (id, project_id, name, provider, reference_asset_id, provider_voice_id, language, default_speed, default_emotion, status) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *', [`voice-profile-${randomUUID()}`, input.projectId, input.name.trim(), input.provider.trim(), input.referenceAssetId || null, input.providerVoiceId || null, input.language || 'zh', defaultSpeed, input.defaultEmotion || 'natural', input.status || 'DRAFT']);
    return mapVoice(result.rows[0] as Record<string, unknown>);
  }
  async listVoiceProfiles(projectId: string): Promise<VoiceProfileV1[]> { const result = await this.db.query('select * from voice_profiles where project_id = $1 order by updated_at desc, id desc', [projectId]); return result.rows.map((row) => mapVoice(row as Record<string, unknown>)); }
  async getVoiceProfile(projectId: string, id: string): Promise<VoiceProfileV1 | null> { const result = await this.db.query('select * from voice_profiles where project_id = $1 and id = $2', [projectId, id]); return result.rows[0] ? mapVoice(result.rows[0] as Record<string, unknown>) : null; }
  async updateVoiceProfile(projectId: string, id: string, input: UpdateVoiceProfileInput): Promise<VoiceProfileV1 | null> {
    const current = await this.getVoiceProfile(projectId, id); if (!current) return null;
    const referenceAssetId = input.referenceAssetId === undefined ? current.referenceAssetId : input.referenceAssetId;
    if (referenceAssetId) { const asset = await this.assets.getProjectAsset(projectId, referenceAssetId); if (!asset || asset.kind !== 'AUDIO' || asset.lifecycle !== 'READY' || !positiveDuration(asset.metadata)) throw new Error('VOICE_REFERENCE_ASSET_NOT_READY'); }
    const defaultSpeed = validSpeed(input.defaultSpeed ?? current.defaultSpeed, 'defaultSpeed');
    const result = await this.db.query('update voice_profiles set name=$3, reference_asset_id=$4, provider_voice_id=$5, language=$6, default_speed=$7, default_emotion=$8, status=$9, updated_at=now() where project_id=$1 and id=$2 returning *', [projectId, id, input.name?.trim() || current.name, referenceAssetId, input.providerVoiceId === undefined ? current.providerVoiceId : input.providerVoiceId, input.language?.trim() || current.language, defaultSpeed, input.defaultEmotion?.trim() || current.defaultEmotion, input.status || current.status]);
    return result.rows[0] ? mapVoice(result.rows[0] as Record<string, unknown>) : null;
  }
  async disableVoiceProfile(projectId: string, id: string): Promise<VoiceProfileV1 | null> { return this.updateVoiceProfile(projectId, id, { status: 'DISABLED' }); }

  async createAvatarProfile(input: CreateAvatarProfileInput): Promise<AvatarProfileV1> { const result = await this.db.query('insert into avatar_profiles (id, project_id, name, owner_name, status) values ($1,$2,$3,$4,$5) returning *', [`avatar-profile-${randomUUID()}`, input.projectId, input.name.trim(), input.ownerName?.trim() || '', input.status || 'DRAFT']); return mapAvatar(result.rows[0] as Record<string, unknown>); }
  async listAvatarProfiles(projectId: string): Promise<AvatarProfileV1[]> { const result = await this.db.query('select * from avatar_profiles where project_id = $1 order by updated_at desc, id desc', [projectId]); return result.rows.map((row) => mapAvatar(row as Record<string, unknown>)); }
  async getAvatarProfile(projectId: string, id: string): Promise<AvatarProfileV1 | null> { const result = await this.db.query('select * from avatar_profiles where project_id = $1 and id = $2', [projectId, id]); return result.rows[0] ? mapAvatar(result.rows[0] as Record<string, unknown>) : null; }
  async updateAvatarProfile(projectId: string, id: string, input: UpdateAvatarProfileInput): Promise<AvatarProfileV1 | null> { const current = await this.getAvatarProfile(projectId, id); if (!current) return null; const result = await this.db.query('update avatar_profiles set name=$3, owner_name=$4, status=$5, updated_at=now() where project_id=$1 and id=$2 returning *', [projectId, id, input.name?.trim() || current.name, input.ownerName === undefined ? current.ownerName : input.ownerName.trim(), input.status || current.status]); return result.rows[0] ? mapAvatar(result.rows[0] as Record<string, unknown>) : null; }
  async disableAvatarProfile(projectId: string, id: string): Promise<AvatarProfileV1 | null> { return this.updateAvatarProfile(projectId, id, { status: 'DISABLED' }); }
  async createAvatarClip(input: CreateAvatarClipInput): Promise<AvatarClipV1> {
    const profile = await this.getAvatarProfile(input.projectId, input.avatarProfileId); if (!profile) throw new Error('AVATAR_PROFILE_NOT_FOUND');
    const asset = await this.assets.getProjectAsset(input.projectId, input.assetId); if (!asset || asset.kind !== 'VIDEO' || asset.lifecycle !== 'READY') throw new Error('AVATAR_CLIP_ASSET_NOT_READY');
    const result = await this.db.query('insert into avatar_clips (id, project_id, avatar_profile_id, asset_id, name, duration_ms, width, height, fps, scene_type, gesture_level, tags) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) returning *', [`avatar-clip-${randomUUID()}`, input.projectId, input.avatarProfileId, input.assetId, input.name.trim(), input.durationMs || null, input.width || null, input.height || null, input.fps || null, input.sceneType || null, input.gestureLevel || null, JSON.stringify(input.tags || [])]);
    return mapClip(result.rows[0] as Record<string, unknown>);
  }
  async listAvatarClips(projectId: string, avatarProfileId: string): Promise<AvatarClipV1[]> { const result = await this.db.query('select * from avatar_clips where project_id = $1 and avatar_profile_id = $2 order by usage_count, created_at', [projectId, avatarProfileId]); return result.rows.map((row) => mapClip(row as Record<string, unknown>)); }
  async getAvatarClip(projectId: string, id: string): Promise<AvatarClipV1 | null> { const result = await this.db.query('select * from avatar_clips where project_id = $1 and id = $2', [projectId, id]); return result.rows[0] ? mapClip(result.rows[0] as Record<string, unknown>) : null; }
  async updateAvatarClip(projectId: string, id: string, input: UpdateAvatarClipInput): Promise<AvatarClipV1 | null> {
    const current = await this.getAvatarClip(projectId, id); if (!current) return null;
    const assetId = input.assetId === undefined ? current.assetId : input.assetId;
    if (input.assetId !== undefined) { const asset = await this.assets.getProjectAsset(projectId, assetId); if (!asset || asset.kind !== 'VIDEO' || asset.lifecycle !== 'READY') throw new Error('AVATAR_CLIP_ASSET_NOT_READY'); }
    const result = await this.db.query('update avatar_clips set asset_id=$3, name=$4, duration_ms=$5, width=$6, height=$7, fps=$8, scene_type=$9, gesture_level=$10, tags=$11, status=$12, updated_at=now() where project_id=$1 and id=$2 returning *', [projectId, id, assetId, input.name?.trim() || current.name, input.durationMs === undefined ? current.durationMs : input.durationMs, input.width === undefined ? current.width : input.width, input.height === undefined ? current.height : input.height, input.fps === undefined ? current.fps : input.fps, input.sceneType === undefined ? current.sceneType : input.sceneType, input.gestureLevel === undefined ? current.gestureLevel : input.gestureLevel, JSON.stringify(input.tags === undefined ? current.tags : input.tags), input.status || current.status]);
    return result.rows[0] ? mapClip(result.rows[0] as Record<string, unknown>) : null;
  }
  async disableAvatarClip(projectId: string, id: string): Promise<AvatarClipV1 | null> { return this.updateAvatarClip(projectId, id, { status: 'DISABLED' }); }

  async createSpeechGeneration(input: CreateSpeechGenerationInput): Promise<{ generation: SpeechGenerationV1; job: JobRecord; created: boolean }> {
    const profile = await this.getVoiceProfile(input.projectId, input.voiceProfileId); if (!profile || profile.status === 'DISABLED') throw new Error('VOICE_PROFILE_NOT_FOUND');
    const reference = profile.referenceAssetId ? await this.assets.getProjectAsset(input.projectId, profile.referenceAssetId) : null;
    if (profile.referenceAssetId && (!reference || reference.kind !== 'AUDIO' || reference.lifecycle !== 'READY')) throw new Error('VOICE_REFERENCE_ASSET_NOT_READY');
    const provider = input.provider || profile.provider; const model = input.model || 'indextts-2.5'; const speed = validSpeed(input.speed ?? profile.defaultSpeed, 'speed'); const parameters = { language: input.language || profile.language, speed, emotion: input.emotion || profile.defaultEmotion };
    const textHash = hash({ provider, model, voiceProfileId: profile.id, referenceChecksum: reference?.checksum || null, text: input.text, parameters });
    const existing = await this.db.query('select * from speech_generations where project_id = $1 and text_hash = $2 and voice_profile_id = $3 and provider = $4 and model = $5', [input.projectId, textHash, profile.id, provider, model]);
    if (existing.rows[0]) {
      let generation = mapSpeech(existing.rows[0] as Record<string, unknown>); let job = await this.jobs.get(generation.jobId); if (!job) throw new Error('SPEECH_GENERATION_JOB_NOT_FOUND');
      if (['FAILED', 'CANCELLED'].includes(generation.status) && ['FAILED', 'CANCELLED'].includes(job.state)) {
        job = await this.jobs.requeueTerminal(job.id);
        if (job.state === 'QUEUED') {
          await this.db.query("update speech_generations set status = 'PENDING', error = null, updated_at = now() where id = $1 and status in ('FAILED','CANCELLED')", [generation.id]);
          generation = (await this.getSpeechGeneration(input.projectId, generation.id)) || generation;
        }
      }
      return { generation, job, created: false };
    }
    const generationId = stableId('speech-generation', input.projectId, textHash);
    const job = await this.jobs.createIdempotent({ id: stableId('job-speech', input.projectId, textHash), projectId: input.projectId, type: 'SPEECH_GENERATE', idempotencyKey: `digital-human:speech:${input.projectId}:${textHash}`, payload: { schemaVersion: 'DIGITAL_HUMAN_JOB_PAYLOAD_V1', kind: 'SPEECH', generationId, projectId: input.projectId, correlationId: input.correlationId }, maxAttempts: 3 });
    const result = await this.db.query('insert into speech_generations (id, project_id, voice_profile_id, provider, model, text, text_hash, parameters, job_id) values ($1,$2,$3,$4,$5,$6,$7,$8,$9) on conflict (project_id, text_hash, voice_profile_id, provider, model) do nothing returning *', [generationId, input.projectId, profile.id, provider, model, input.text, textHash, JSON.stringify(parameters), job.id]);
    const row = result.rows[0] || (await this.db.query('select * from speech_generations where project_id = $1 and text_hash = $2 and voice_profile_id = $3 and provider = $4 and model = $5', [input.projectId, textHash, profile.id, provider, model])).rows[0];
    if (!row) throw new Error('SPEECH_GENERATION_INSERT_FAILED');
    const generation = mapSpeech(row as Record<string, unknown>); return { generation, job, created: result.rowCount === 1 };
  }
  async getSpeechGeneration(projectId: string, id: string): Promise<SpeechGenerationV1 | null> { const result = await this.db.query('select * from speech_generations where project_id = $1 and id = $2', [projectId, id]); return result.rows[0] ? mapSpeech(result.rows[0] as Record<string, unknown>) : null; }
  async listSpeechGenerations(projectId: string): Promise<SpeechGenerationV1[]> { const result = await this.db.query('select * from speech_generations where project_id = $1 order by created_at desc', [projectId]); return result.rows.map((row) => mapSpeech(row as Record<string, unknown>)); }
  async markSpeechRunning(id: string): Promise<void> { await this.db.query("update speech_generations set status = 'RUNNING', updated_at = now() where id = $1 and status in ('PENDING','RUNNING','WAITING_EXTERNAL','FAILED')", [id]); }
  async completeSpeech(id: string, input: { outputAssetId: string; durationMs: number; latencyMs: number; modelVersion: string; provenance: Record<string, unknown> }): Promise<boolean> { const result = await this.db.query("update speech_generations set status = 'SUCCEEDED', output_asset_id = $2, duration_ms = $3, latency_ms = $4, model_version = $5, provenance = $6, error = null, updated_at = now() where id = $1 and status in ('PENDING','RUNNING','WAITING_EXTERNAL','FAILED')", [id, input.outputAssetId, input.durationMs, input.latencyMs, input.modelVersion, JSON.stringify(input.provenance)]); return Boolean(result.rowCount); }
  async failSpeech(id: string, error: { code: string; message: string }): Promise<void> { await this.db.query("update speech_generations set status = 'FAILED', error = $2, updated_at = now() where id = $1 and status in ('PENDING','RUNNING','WAITING_EXTERNAL','FAILED')", [id, JSON.stringify(error)]); }
  async cancelSpeech(id: string): Promise<void> { await this.db.query("update speech_generations set status = 'CANCELLED', updated_at = now() where id = $1 and status in ('PENDING','RUNNING','WAITING_EXTERNAL')", [id]); }

  async createAvatarGeneration(input: CreateAvatarGenerationInput): Promise<{ generation: AvatarGenerationV1; job: JobRecord; created: boolean }> {
    const profile = await this.getAvatarProfile(input.projectId, input.avatarProfileId); if (!profile || profile.status === 'DISABLED') throw new Error('AVATAR_PROFILE_NOT_FOUND');
    const clip = await this.getAvatarClip(input.projectId, input.avatarClipId); if (!clip || clip.avatarProfileId !== profile.id || clip.status === 'DISABLED') throw new Error('AVATAR_CLIP_NOT_FOUND');
    const sourceVideo = await this.assets.getProjectAsset(input.projectId, clip.assetId); const speech = await this.assets.getProjectAsset(input.projectId, input.speechAssetId);
    if (!sourceVideo || sourceVideo.kind !== 'VIDEO' || sourceVideo.lifecycle !== 'READY') throw new Error('AVATAR_CLIP_ASSET_NOT_READY');
    if (!speech || speech.kind !== 'AUDIO' || speech.lifecycle !== 'READY') throw new Error('SPEECH_ASSET_NOT_READY');
    const timing = normalizeAvatarTiming(sourceVideo, speech, input.sourceInMs ?? 0);
    const provider = input.provider || 'hzagent'; const model = input.model || null; const parameters = input.parameters || {}; const requestHash = hash({ provider, model, avatarProfileId: profile.id, avatarClipId: clip.id, speechAssetId: input.speechAssetId, clipAssetChecksum: sourceVideo.checksum, speechAssetChecksum: speech.checksum, sourceInMs: timing.sourceInMs, targetDurationMs: timing.targetDurationMs, parameters });
    const existing = await this.db.query('select * from avatar_generations where project_id = $1 and request_hash = $2', [input.projectId, requestHash]);
    if (existing.rows[0]) {
      let generation = mapAvatarGeneration(existing.rows[0] as Record<string, unknown>); let job = await this.jobs.get(generation.jobId); if (!job) throw new Error('AVATAR_GENERATION_JOB_NOT_FOUND');
      if (['FAILED', 'CANCELLED'].includes(generation.status) && ['FAILED', 'CANCELLED'].includes(job.state)) {
        job = await this.jobs.requeueTerminal(job.id);
        if (job.state === 'QUEUED') {
          await this.db.query("update avatar_generations set status = 'PENDING', error = null, updated_at = now() where id = $1 and status in ('FAILED','CANCELLED')", [generation.id]);
          generation = (await this.getAvatarGeneration(input.projectId, generation.id)) || generation;
        }
      }
      return { generation, job, created: false };
    }
    const generationId = stableId('avatar-generation', input.projectId, requestHash);
    const job = await this.jobs.createIdempotent({ id: stableId('job-avatar', input.projectId, requestHash), projectId: input.projectId, type: 'AVATAR_LIPSYNC_GENERATE', idempotencyKey: `digital-human:avatar:${input.projectId}:${requestHash}`, payload: { schemaVersion: 'DIGITAL_HUMAN_JOB_PAYLOAD_V1', kind: 'AVATAR', generationId, projectId: input.projectId, correlationId: input.correlationId, timing: { sourceVideoAssetId: timing.sourceVideoAssetId, sourceInMs: timing.sourceInMs, sourceOutMs: timing.sourceOutMs, targetDurationMs: timing.targetDurationMs } }, maxAttempts: 5 });
    const result = await this.db.query('insert into avatar_generations (id, project_id, avatar_profile_id, avatar_clip_id, speech_asset_id, source_video_asset_id, source_in_ms, source_out_ms, target_duration_ms, provider, model, request_hash, provenance, job_id) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) on conflict (project_id, request_hash) do nothing returning *', [generationId, input.projectId, profile.id, clip.id, input.speechAssetId, timing.sourceVideoAssetId, timing.sourceInMs, timing.sourceOutMs, timing.targetDurationMs, provider, model, requestHash, JSON.stringify({ parameters, timing }), job.id]);
    const row = result.rows[0] || (await this.db.query('select * from avatar_generations where project_id = $1 and request_hash = $2', [input.projectId, requestHash])).rows[0];
    if (!row) throw new Error('AVATAR_GENERATION_INSERT_FAILED');
    if (result.rowCount === 1) await this.db.query('update avatar_clips set usage_count = usage_count + 1, last_used_at = now(), updated_at = now() where id = $1 and project_id = $2', [clip.id, input.projectId]);
    const generation = mapAvatarGeneration(row as Record<string, unknown>); return { generation, job, created: result.rowCount === 1 };
  }
  async getAvatarGeneration(projectId: string, id: string): Promise<AvatarGenerationV1 | null> { const result = await this.db.query('select * from avatar_generations where project_id = $1 and id = $2', [projectId, id]); return result.rows[0] ? mapAvatarGeneration(result.rows[0] as Record<string, unknown>) : null; }
  async hasOtherAvatarOutputReference(projectId: string, assetId: string, generationId: string): Promise<boolean> { const result = await this.db.query("select 1 from avatar_generations where project_id = $1 and output_asset_id = $2 and id <> $3 and status = 'SUCCEEDED' limit 1", [projectId, assetId, generationId]); return result.rows.length > 0; }
  async listAvatarGenerations(projectId: string): Promise<AvatarGenerationV1[]> { const result = await this.db.query('select * from avatar_generations where project_id = $1 order by created_at desc', [projectId]); return result.rows.map((row) => mapAvatarGeneration(row as Record<string, unknown>)); }
  async findAvatarGenerationForRequest(input: Pick<CreateAvatarGenerationInput, 'projectId' | 'avatarProfileId' | 'avatarClipId' | 'speechAssetId' | 'provider' | 'model' | 'parameters'>): Promise<AvatarGenerationV1 | null> {
    const clip = await this.getAvatarClip(input.projectId, input.avatarClipId); if (!clip || clip.avatarProfileId !== input.avatarProfileId) return null;
    const sourceVideo = await this.assets.getProjectAsset(input.projectId, clip.assetId); const speech = await this.assets.getProjectAsset(input.projectId, input.speechAssetId);
    if (!sourceVideo || !speech || sourceVideo.kind !== 'VIDEO' || speech.kind !== 'AUDIO' || sourceVideo.lifecycle !== 'READY' || speech.lifecycle !== 'READY') return null;
    const provider = input.provider || 'hzagent'; const model = input.model || null; const parameters = input.parameters || {}; let sourceInMs = 0; try { sourceInMs = normalizeAvatarTiming(sourceVideo, speech, 0).sourceInMs; } catch { /* legacy lookup remains best effort */ } const requestHash = hash({ provider, model, avatarProfileId: input.avatarProfileId, avatarClipId: input.avatarClipId, speechAssetId: input.speechAssetId, clipAssetChecksum: sourceVideo.checksum, speechAssetChecksum: speech.checksum, sourceInMs, targetDurationMs: Number(speech.metadata.durationMs), parameters });
    const result = await this.db.query('select * from avatar_generations where project_id = $1 and request_hash = $2', [input.projectId, requestHash]); return result.rows[0] ? mapAvatarGeneration(result.rows[0] as Record<string, unknown>) : null;
  }
  async markAvatarRunning(id: string): Promise<void> { await this.db.query("update avatar_generations set status = 'RUNNING', updated_at = now() where id = $1 and status in ('PENDING','RUNNING','WAITING_EXTERNAL','FAILED')", [id]); }
  async markAvatarWaiting(id: string, externalTaskId: string, provenance: Record<string, unknown>): Promise<void> { await this.db.query("update avatar_generations set status = 'WAITING_EXTERNAL', external_task_id = $2, provenance = $3, updated_at = now() where id = $1 and status in ('PENDING','RUNNING') and external_task_id is null", [id, externalTaskId, JSON.stringify(provenance)]); }
  async replaceAvatarWaiting(id: string, externalTaskId: string, provenance: Record<string, unknown>): Promise<void> { await this.db.query("update avatar_generations set status = 'WAITING_EXTERNAL', external_task_id = $2, provenance = $3, updated_at = now() where id = $1 and status in ('PENDING','RUNNING') and external_task_id is not null", [id, externalTaskId, JSON.stringify(provenance)]); }
  async completeAvatar(id: string, input: { outputAssetId: string; durationMs?: number | undefined; model?: string | undefined; modelVersion?: string | undefined; costAmount?: number | undefined; costCurrency?: string | undefined; billingQuantity?: number | undefined; billingUnit?: string | undefined; provenance?: Record<string, unknown> | undefined }): Promise<boolean> { const result = await this.db.query("update avatar_generations set status = 'SUCCEEDED', output_asset_id = $2, duration_ms = $3, model = coalesce($4, model), model_version = $5, cost_amount = $6, cost_currency = $7, billing_quantity = $8, billing_unit = $9, provenance = coalesce($10, provenance), error = null, updated_at = now() where id = $1 and status in ('PENDING','RUNNING','WAITING_EXTERNAL','FAILED')", [id, input.outputAssetId, input.durationMs ?? null, input.model || null, input.modelVersion || null, input.costAmount ?? null, input.costCurrency ?? null, input.billingQuantity ?? null, input.billingUnit || null, input.provenance ? JSON.stringify(input.provenance) : null]); return Boolean(result.rowCount); }
  async failAvatar(id: string, error: { code: string; message: string }): Promise<void> { await this.db.query("update avatar_generations set status = 'FAILED', error = $2, updated_at = now() where id = $1 and status in ('PENDING','RUNNING','WAITING_EXTERNAL','FAILED')", [id, JSON.stringify(error)]); }
  async cancelAvatar(id: string): Promise<void> { await this.db.query("update avatar_generations set status = 'CANCELLED', updated_at = now() where id = $1 and status in ('PENDING','RUNNING','WAITING_EXTERNAL')", [id]); }
}
